package tw.edu.chit.struts.action.report.teacher;

import java.io.PrintWriter;
import java.util.HashMap;
import java.util.Map;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import tw.edu.chit.service.CourseManager;
import tw.edu.chit.struts.action.BaseAction;

public class IntorDoc extends BaseAction{
	
	public ActionForward execute(ActionMapping mapping, ActionForm form, HttpServletRequest request, HttpServletResponse response)throws Exception {	
		
		response.setContentType("text/xml; charset=UTF-8");		
		
		
		
		
		PrintWriter out=response.getWriter();		
		Map intor;		
		response.setHeader("Content-disposition","attachment;filename=IntorDoc.doc");
		
		out.write("<?xml version='1.0' encoding='UTF-8' standalone='yes'?>");
		out.write("<?mso-application progid='Word.Document'?>");
		out.write("<w:wordDocument xmlns:w='http://schemas.microsoft.com/office/word/2003/wordml' xmlns:v='urn:schemas-microsoft-com:vml' xmlns:w10='urn:schemas-microsoft-com:office:word' xmlns:sl='http://schemas.microsoft.com/schemaLibrary/2003/core' xmlns:aml='http://schemas.microsoft.com/aml/2001/core' xmlns:wx='http://schemas.microsoft.com/office/word/2003/auxHint' xmlns:o='urn:schemas-microsoft-com:office:office' xmlns:dt='uuid:C2F41010-65B3-11d1-A29F-00AA00C14882' w:macrosPresent='no' w:embeddedObjPresent='no' w:ocxPresent='no' xml:space='preserve'>");
		out.write("  <o:DocumentProperties>");
		out.write("    <o:Title>系科名稱(Department)：四技電子一甲</o:Title>");
		out.write("    <o:Author>蕭國裕</o:Author>");
		out.write("    <o:LastAuthor>蕭國裕</o:LastAuthor>");
		out.write("    <o:Revision>2</o:Revision>");
		out.write("    <o:TotalTime>2</o:TotalTime>");
		out.write("    <o:Created>2011-10-19T07:24:00Z</o:Created>");
		out.write("    <o:LastSaved>2011-10-19T07:24:00Z</o:LastSaved>");
		out.write("    <o:Pages>1</o:Pages>");
		out.write("    <o:Words>39</o:Words>");
		out.write("    <o:Characters>225</o:Characters>");
		out.write("    <o:Lines>1</o:Lines>");
		out.write("    <o:Paragraphs>1</o:Paragraphs>");
		out.write("    <o:CharactersWithSpaces>263</o:CharactersWithSpaces>");
		out.write("    <o:Version>11.5604</o:Version>");
		out.write("  </o:DocumentProperties>");
		out.write("  <w:fonts>");
		out.write("    <w:defaultFonts w:ascii='Calibri' w:fareast='新細明體' w:h-ansi='Calibri' w:cs='Times New Roman'/>");
		out.write("    <w:font w:name='新細明體'>");
		out.write("      <w:altName w:val='PMingLiU'/>");
		out.write("      <w:panose-1 w:val='02020300000000000000'/>");
		out.write("      <w:charset w:val='88'/>");
		out.write("      <w:family w:val='Roman'/>");
		out.write("      <w:pitch w:val='variable'/>");
		out.write("      <w:sig w:usb-0='00000003' w:usb-1='082E0000' w:usb-2='00000016' w:usb-3='00000000' w:csb-0='00100001' w:csb-1='00000000'/>");
		out.write("    </w:font>");
		out.write("    <w:font w:name='Calibri'>");
		out.write("      <w:panose-1 w:val='020F0502020204030204'/>");
		out.write("      <w:charset w:val='00'/>");
		out.write("      <w:family w:val='Swiss'/>");
		out.write("      <w:pitch w:val='variable'/>");
		out.write("      <w:sig w:usb-0='A00002EF' w:usb-1='4000207B' w:usb-2='00000000' w:usb-3='00000000' w:csb-0='0000009F' w:csb-1='00000000'/>");
		out.write("    </w:font>");
		out.write("    <w:font w:name='標楷體'>");
		out.write("      <w:panose-1 w:val='03000509000000000000'/>");
		out.write("      <w:charset w:val='88'/>");
		out.write("      <w:family w:val='Script'/>");
		out.write("      <w:pitch w:val='fixed'/>");
		out.write("      <w:sig w:usb-0='00000003' w:usb-1='082E0000' w:usb-2='00000016' w:usb-3='00000000' w:csb-0='00100001' w:csb-1='00000000'/>");
		out.write("    </w:font>");
		out.write("    <w:font w:name='Cambria'>");
		out.write("      <w:panose-1 w:val='02040503050406030204'/>");
		out.write("      <w:charset w:val='00'/>");
		out.write("      <w:family w:val='Roman'/>");
		out.write("      <w:pitch w:val='variable'/>");
		out.write("      <w:sig w:usb-0='A00002EF' w:usb-1='4000004B' w:usb-2='00000000' w:usb-3='00000000' w:csb-0='0000009F' w:csb-1='00000000'/>");
		out.write("    </w:font>");
		out.write("    <w:font w:name='@標楷體'>");
		out.write("      <w:panose-1 w:val='03000509000000000000'/>");
		out.write("      <w:charset w:val='88'/>");
		out.write("      <w:family w:val='Script'/>");
		out.write("      <w:pitch w:val='fixed'/>");
		out.write("      <w:sig w:usb-0='00000003' w:usb-1='082E0000' w:usb-2='00000016' w:usb-3='00000000' w:csb-0='00100001' w:csb-1='00000000'/>");
		out.write("    </w:font>");
		out.write("    <w:font w:name='@新細明體'>");
		out.write("      <w:panose-1 w:val='02020300000000000000'/>");
		out.write("      <w:charset w:val='88'/>");
		out.write("      <w:family w:val='Roman'/>");
		out.write("      <w:pitch w:val='variable'/>");
		out.write("      <w:sig w:usb-0='00000003' w:usb-1='082E0000' w:usb-2='00000016' w:usb-3='00000000' w:csb-0='00100001' w:csb-1='00000000'/>");
		out.write("    </w:font>");
		out.write("  </w:fonts>");
		out.write("  <w:styles>");
		out.write("    <w:versionOfBuiltInStylenames w:val='4'/>");
		out.write("    <w:latentStyles w:defLockedState='off' w:latentStyleCount='156'/>");
		out.write("    <w:style w:type='paragraph' w:default='on' w:styleId='a'>");
		out.write("      <w:name w:val='Normal'/>");
		out.write("      <wx:uiName wx:val='內文'/>");
		out.write("      <w:rsid w:val='00135E4E'/>");
		out.write("      <w:pPr>");
		out.write("        <w:widowControl w:val='off'/>");
		out.write("      </w:pPr>");
		out.write("      <w:rPr>");
		out.write("        <wx:font wx:val='Calibri'/>");
		out.write("        <w:kern w:val='2'/>");
		out.write("        <w:sz w:val='24'/>");
		out.write("        <w:sz-cs w:val='22'/>");
		out.write("        <w:lang w:val='EN-US' w:fareast='ZH-TW' w:bidi='AR-SA'/>");
		out.write("      </w:rPr>");
		out.write("    </w:style>");
		out.write("    <w:style w:type='character' w:default='on' w:styleId='a0'>");
		out.write("      <w:name w:val='Default Paragraph Font'/>");
		out.write("      <wx:uiName wx:val='預設段落字型'/>");
		out.write("      <w:semiHidden/>");
		out.write("    </w:style>");
		out.write("    <w:style w:type='table' w:default='on' w:styleId='a1'>");
		out.write("      <w:name w:val='Normal Table'/>");
		out.write("      <wx:uiName wx:val='表格內文'/>");
		out.write("      <w:semiHidden/>");
		out.write("      <w:rPr>");
		out.write("        <wx:font wx:val='Calibri'/>");
		out.write("      </w:rPr>");
		out.write("      <w:tblPr>");
		out.write("        <w:tblInd w:w='0' w:type='dxa'/>");
		out.write("        <w:tblCellMar>");
		out.write("          <w:top w:w='0' w:type='dxa'/>");
		out.write("          <w:left w:w='108' w:type='dxa'/>");
		out.write("          <w:bottom w:w='0' w:type='dxa'/>");
		out.write("          <w:right w:w='108' w:type='dxa'/>");
		out.write("        </w:tblCellMar>");
		out.write("      </w:tblPr>");
		out.write("    </w:style>");
		out.write("    <w:style w:type='list' w:default='on' w:styleId='a2'>");
		out.write("      <w:name w:val='No List'/>");
		out.write("      <wx:uiName wx:val='無清單'/>");
		out.write("      <w:semiHidden/>");
		out.write("    </w:style>");
		out.write("    <w:style w:type='paragraph' w:styleId='a3'>");
		out.write("      <w:name w:val='header'/>");
		out.write("      <wx:uiName wx:val='頁首'/>");
		out.write("      <w:basedOn w:val='a'/>");
		out.write("      <w:link w:val='2'/>");
		out.write("      <w:rsid w:val='00135E4E'/>");
		out.write("      <w:pPr>");
		out.write("        <w:pStyle w:val='a3'/>");
		out.write("        <w:tabs>");
		out.write("          <w:tab w:val='center' w:pos='4153'/>");
		out.write("          <w:tab w:val='right' w:pos='8306'/>");
		out.write("        </w:tabs>");
		out.write("        <w:snapToGrid w:val='off'/>");
		out.write("      </w:pPr>");
		out.write("      <w:rPr>");
		out.write("        <wx:font wx:val='Calibri'/>");
		out.write("        <w:sz w:val='20'/>");
		out.write("        <w:sz-cs w:val='20'/>");
		out.write("      </w:rPr>");
		out.write("    </w:style>");
		out.write("    <w:style w:type='character' w:styleId='2'>");
		out.write("      <w:name w:val='字元 字元2'/>");
		out.write("      <w:link w:val='a3'/>");
		out.write("      <w:rsid w:val='00135E4E'/>");
		out.write("      <w:rPr>");
		out.write("        <w:sz w:val='20'/>");
		out.write("        <w:sz-cs w:val='20'/>");
		out.write("      </w:rPr>");
		out.write("    </w:style>");
		out.write("    <w:style w:type='paragraph' w:styleId='a4'>");
		out.write("      <w:name w:val='footer'/>");
		out.write("      <wx:uiName wx:val='頁尾'/>");
		out.write("      <w:basedOn w:val='a'/>");
		out.write("      <w:link w:val='1'/>");
		out.write("      <w:rsid w:val='00135E4E'/>");
		out.write("      <w:pPr>");
		out.write("        <w:pStyle w:val='a4'/>");
		out.write("        <w:tabs>");
		out.write("          <w:tab w:val='center' w:pos='4153'/>");
		out.write("          <w:tab w:val='right' w:pos='8306'/>");
		out.write("        </w:tabs>");
		out.write("        <w:snapToGrid w:val='off'/>");
		out.write("      </w:pPr>");
		out.write("      <w:rPr>");
		out.write("        <wx:font wx:val='Calibri'/>");
		out.write("        <w:sz w:val='20'/>");
		out.write("        <w:sz-cs w:val='20'/>");
		out.write("      </w:rPr>");
		out.write("    </w:style>");
		out.write("    <w:style w:type='character' w:styleId='1'>");
		out.write("      <w:name w:val='字元 字元1'/>");
		out.write("      <w:link w:val='a4'/>");
		out.write("      <w:rsid w:val='00135E4E'/>");
		out.write("      <w:rPr>");
		out.write("        <w:sz w:val='20'/>");
		out.write("        <w:sz-cs w:val='20'/>");
		out.write("      </w:rPr>");
		out.write("    </w:style>");
		out.write("    <w:style w:type='paragraph' w:styleId='a5'>");
		out.write("      <w:name w:val='Balloon Text'/>");
		out.write("      <wx:uiName wx:val='註解方塊文字'/>");
		out.write("      <w:basedOn w:val='a'/>");
		out.write("      <w:link w:val='a6'/>");
		out.write("      <w:rsid w:val='00135E4E'/>");
		out.write("      <w:pPr>");
		out.write("        <w:pStyle w:val='a5'/>");
		out.write("      </w:pPr>");
		out.write("      <w:rPr>");
		out.write("        <w:rFonts w:ascii='Cambria' w:h-ansi='Cambria'/>");
		out.write("        <wx:font wx:val='Cambria'/>");
		out.write("        <w:sz w:val='18'/>");
		out.write("        <w:sz-cs w:val='18'/>");
		out.write("      </w:rPr>");
		out.write("    </w:style>");
		out.write("    <w:style w:type='character' w:styleId='a6'>");
		out.write("      <w:name w:val='字元 字元'/>");
		out.write("      <w:link w:val='a5'/>");
		out.write("      <w:rsid w:val='00135E4E'/>");
		out.write("      <w:rPr>");
		out.write("        <w:rFonts w:ascii='Cambria' w:fareast='新細明體' w:h-ansi='Cambria' w:cs='Times New Roman'/>");
		out.write("        <w:sz w:val='18'/>");
		out.write("        <w:sz-cs w:val='18'/>");
		out.write("      </w:rPr>");
		out.write("    </w:style>");
		out.write("  </w:styles>");
		out.write("  <w:divs>");
		out.write("    <w:div w:id='565339826'>");
		out.write("      <w:bodyDiv w:val='on'/>");
		out.write("      <w:marLeft w:val='0'/>");
		out.write("      <w:marRight w:val='0'/>");
		out.write("      <w:marTop w:val='0'/>");
		out.write("      <w:marBottom w:val='0'/>");
		out.write("      <w:divBdr>");
		out.write("        <w:top w:val='none' w:sz='0' wx:bdrwidth='0' w:space='0' w:color='auto'/>");
		out.write("        <w:left w:val='none' w:sz='0' wx:bdrwidth='0' w:space='0' w:color='auto'/>");
		out.write("        <w:bottom w:val='none' w:sz='0' wx:bdrwidth='0' w:space='0' w:color='auto'/>");
		out.write("        <w:right w:val='none' w:sz='0' wx:bdrwidth='0' w:space='0' w:color='auto'/>");
		out.write("      </w:divBdr>");
		out.write("    </w:div>");
		out.write("    <w:div w:id='1113129682'>");
		out.write("      <w:bodyDiv w:val='on'/>");
		out.write("      <w:marLeft w:val='0'/>");
		out.write("      <w:marRight w:val='0'/>");
		out.write("      <w:marTop w:val='0'/>");
		out.write("      <w:marBottom w:val='0'/>");
		out.write("      <w:divBdr>");
		out.write("        <w:top w:val='none' w:sz='0' wx:bdrwidth='0' w:space='0' w:color='auto'/>");
		out.write("        <w:left w:val='none' w:sz='0' wx:bdrwidth='0' w:space='0' w:color='auto'/>");
		out.write("        <w:bottom w:val='none' w:sz='0' wx:bdrwidth='0' w:space='0' w:color='auto'/>");
		out.write("        <w:right w:val='none' w:sz='0' wx:bdrwidth='0' w:space='0' w:color='auto'/>");
		out.write("      </w:divBdr>");
		out.write("    </w:div>");
		out.write("    <w:div w:id='1836843097'>");
		out.write("      <w:bodyDiv w:val='on'/>");
		out.write("      <w:marLeft w:val='0'/>");
		out.write("      <w:marRight w:val='0'/>");
		out.write("      <w:marTop w:val='0'/>");
		out.write("      <w:marBottom w:val='0'/>");
		out.write("      <w:divBdr>");
		out.write("        <w:top w:val='none' w:sz='0' wx:bdrwidth='0' w:space='0' w:color='auto'/>");
		out.write("        <w:left w:val='none' w:sz='0' wx:bdrwidth='0' w:space='0' w:color='auto'/>");
		out.write("        <w:bottom w:val='none' w:sz='0' wx:bdrwidth='0' w:space='0' w:color='auto'/>");
		out.write("        <w:right w:val='none' w:sz='0' wx:bdrwidth='0' w:space='0' w:color='auto'/>");
		out.write("      </w:divBdr>");
		out.write("    </w:div>");
		out.write("  </w:divs>");
		out.write("  <w:shapeDefaults>");
		out.write("    <o:shapedefaults v:ext='edit' spidmax='4097'/>");
		out.write("    <o:shapelayout v:ext='edit'>");
		out.write("      <o:idmap v:ext='edit' data='1'/>");
		out.write("    </o:shapelayout>");
		out.write("  </w:shapeDefaults>");
		out.write("  <w:docPr>");
		out.write("    <w:view w:val='print'/>");
		out.write("    <w:zoom w:percent='100'/>");
		out.write("    <w:doNotEmbedSystemFonts/>");
		out.write("    <w:bordersDontSurroundHeader/>");
		out.write("    <w:bordersDontSurroundFooter/>");
		out.write("    <w:proofState w:spelling='clean' w:grammar='clean'/>");
		out.write("    <w:attachedTemplate w:val=''/>");
		out.write("    <w:stylePaneFormatFilter w:val='1004'/>");
		out.write("    <w:defaultTabStop w:val='480'/>");
		out.write("    <w:drawingGridHorizontalSpacing w:val='120'/>");
		out.write("    <w:displayHorizontalDrawingGridEvery w:val='0'/>");
		out.write("    <w:displayVerticalDrawingGridEvery w:val='2'/>");
		out.write("    <w:punctuationKerning/>");
		out.write("    <w:characterSpacingControl w:val='CompressPunctuation'/>");
		out.write("    <w:optimizeForBrowser/>");
		out.write("    <w:targetScreenSz w:val='1024x768'/>");
		out.write("    <w:validateAgainstSchema/>");
		out.write("    <w:saveInvalidXML w:val='off'/>");
		out.write("    <w:ignoreMixedContent w:val='off'/>");
		out.write("    <w:alwaysShowPlaceholderText w:val='off'/>");
		out.write("    <w:hdrShapeDefaults>");
		out.write("      <o:shapedefaults v:ext='edit' spidmax='4097'/>");
		out.write("    </w:hdrShapeDefaults>");
		out.write("    <w:footnotePr>");
		out.write("      <w:footnote w:type='separator'>");
		out.write("        <w:p>");
		out.write("          <w:pPr>");
		out.write("            <w:rPr>");
		out.write("              <w:rFonts w:hint='fareast'/>");
		out.write("            </w:rPr>");
		out.write("          </w:pPr>");
		out.write("          <w:r>");
		out.write("            <w:separator/>");
		out.write("          </w:r>");
		out.write("        </w:p>");
		out.write("      </w:footnote>");
		out.write("      <w:footnote w:type='continuation-separator'>");
		out.write("        <w:p>");
		out.write("          <w:pPr>");
		out.write("            <w:rPr>");
		out.write("              <w:rFonts w:hint='fareast'/>");
		out.write("            </w:rPr>");
		out.write("          </w:pPr>");
		out.write("          <w:r>");
		out.write("            <w:continuationSeparator/>");
		out.write("          </w:r>");
		out.write("        </w:p>");
		out.write("      </w:footnote>");
		out.write("    </w:footnotePr>");
		out.write("    <w:endnotePr>");
		out.write("      <w:endnote w:type='separator'>");
		out.write("        <w:p>");
		out.write("          <w:pPr>");
		out.write("            <w:rPr>");
		out.write("              <w:rFonts w:hint='fareast'/>");
		out.write("            </w:rPr>");
		out.write("          </w:pPr>");
		out.write("          <w:r>");
		out.write("            <w:separator/>");
		out.write("          </w:r>");
		out.write("        </w:p>");
		out.write("      </w:endnote>");
		out.write("      <w:endnote w:type='continuation-separator'>");
		out.write("        <w:p>");
		out.write("          <w:pPr>");
		out.write("            <w:rPr>");
		out.write("              <w:rFonts w:hint='fareast'/>");
		out.write("            </w:rPr>");
		out.write("          </w:pPr>");
		out.write("          <w:r>");
		out.write("            <w:continuationSeparator/>");
		out.write("          </w:r>");
		out.write("        </w:p>");
		out.write("      </w:endnote>");
		out.write("    </w:endnotePr>");
		out.write("    <w:compat>");
		out.write("      <w:spaceForUL/>");
		out.write("      <w:balanceSingleByteDoubleByteWidth/>");
		out.write("      <w:doNotLeaveBackslashAlone/>");
		out.write("      <w:ulTrailSpace/>");
		out.write("      <w:doNotExpandShiftReturn/>");
		out.write("      <w:adjustLineHeightInTable/>");
		out.write("      <w:breakWrappedTables/>");
		out.write("      <w:snapToGridInCell/>");
		out.write("      <w:wrapTextWithPunct/>");
		out.write("      <w:useAsianBreakRules/>");
		out.write("      <w:dontGrowAutofit/>");
		out.write("      <w:useFELayout/>");
		out.write("    </w:compat>");
		out.write("  </w:docPr>");
		out.write("  <w:body>");
		
		CourseManager manager = (CourseManager) getBean("courseManager");
		Map map=new HashMap();
		try{
			if(request.getParameter("Oid")!=null){
				//本學年
				map=manager.ezGetMap("SELECT d.Sterm, d.credit, d.introduction, c.ClassName, cs.chi_name, cs.eng_name, e.cname " +
				"FROM Dtime d, Class c, Csno cs, empl e WHERE d.depart_class=c.ClassNo AND " +
				"cs.cscode=d.cscode AND e.idno=d.techid AND d.Oid="+request.getParameter("Oid"));
				map.put("school_year", manager.getSchoolYear());
			}
			if(request.getParameter("sOid")!=null){
				//過去學年'				
				map=manager.ezGetMap("SELECT d.techid, d.school_year, d.school_term as Sterm, d.credit, d.introduction, c.ClassName, cs.chi_name, cs.eng_name, e.cname " +
				"FROM Savedtime d LEFT OUTER JOIN empl e ON e.idno=d.techid, Class c, Csno cs  WHERE d.depart_class=c.ClassNo AND " +
				"cs.cscode=d.cscode AND d.Oid="+request.getParameter("sOid"));
			}
		}catch(Exception e){
			e.printStackTrace();
			out.println ("    <w:br w:type='page'/>");
			out.println("  </w:body>");
			out.println("</w:wordDocument>");
			return null;
			
		}
		
		if(map==null){
			out.println ("    <w:br w:type='page'/>");
			out.println("  </w:body>");
			out.println("</w:wordDocument>");
			return null;
		}
		
		out.write("    <wx:sect>");
		out.write("      <w:tbl>");
		out.write("        <w:tblPr>");
		out.write("          <w:tblW w:w='10509' w:type='dxa'/>");
		out.write("          <w:tblInd w:w='13' w:type='dxa'/>");
		out.write("          <w:tblCellMar>");
		out.write("            <w:left w:w='28' w:type='dxa'/>");
		out.write("            <w:right w:w='28' w:type='dxa'/>");
		out.write("          </w:tblCellMar>");
		out.write("          <w:tblLook w:val='04A0'/>");
		out.write("        </w:tblPr>");
		out.write("        <w:tblGrid>");
		out.write("          <w:gridCol w:w='103'/>");
		out.write("          <w:gridCol w:w='10406'/>");
		out.write("        </w:tblGrid>");
		out.write("        <w:tr>");
		out.write("          <w:trPr>");
		out.write("            <w:trHeight w:val='402'/>");
		out.write("          </w:trPr>");
		out.write("          <w:tc>");
		out.write("            <w:tcPr>");
		out.write("              <w:tcW w:w='10509' w:type='dxa'/>");
		out.write("              <w:gridSpan w:val='2'/>");
		out.write("              <w:tcBorders>");
		out.write("                <w:top w:val='single' w:sz='4' wx:bdrwidth='10' w:space='0' w:color='auto'/>");
		out.write("                <w:left w:val='single' w:sz='4' wx:bdrwidth='10' w:space='0' w:color='auto'/>");
		out.write("                <w:bottom w:val='nil'/>");
		out.write("                <w:right w:val='single' w:sz='4' wx:bdrwidth='10' w:space='0' w:color='000000'/>");
		out.write("              </w:tcBorders>");
		out.write("              <w:shd w:val='clear' w:color='auto' w:fill='auto'/>");
		out.write("              <w:noWrap/>");
		out.write("              <w:vAlign w:val='center'/>");
		out.write("            </w:tcPr>");
		out.write("            <w:p>");
		out.write("              <w:pPr>");
		out.write("                <w:widowControl/>");
		out.write("                <w:rPr>");
		out.write("                  <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:cs='新細明體'/>");
		out.write("                  <wx:font wx:val='標楷體'/>");
		out.write("                  <w:kern w:val='0'/>");
		out.write("                  <w:sz-cs w:val='24'/>");
		out.write("                </w:rPr>");
		out.write("              </w:pPr>");
		out.write("              <w:r>");
		out.write("                <w:rPr>");
		out.write("                  <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:cs='新細明體' w:hint='fareast'/>");
		out.write("                  <wx:font wx:val='標楷體'/>");
		out.write("                  <w:kern w:val='0'/>");
		out.write("                  <w:sz-cs w:val='24'/>");
		out.write("                </w:rPr>");
		out.write("                <w:t>系科名稱(Department)：</w:t>");
		out.write("              </w:r>");
		out.write("              <w:proofErr w:type='spellStart'/>");
		out.write("              <w:r>");
		out.write("                <w:rPr>");
		out.write("                  <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:cs='新細明體' w:hint='fareast'/>");
		out.write("                  <wx:font wx:val='標楷體'/>");
		out.write("                  <w:kern w:val='0'/>");
		out.write("                  <w:sz-cs w:val='24'/>");
		out.write("                </w:rPr>");
		out.write("                <w:t>"+map.get("ClassName")+"</w:t>");
		out.write("              </w:r>");
		out.write("              <w:proofErr w:type='spellEnd'/>");
		out.write("              <w:r>");
		out.write("                <w:rPr>");
		out.write("                  <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:cs='新細明體' w:hint='fareast'/>");
		out.write("                  <wx:font wx:val='標楷體'/>");
		out.write("                  <w:kern w:val='0'/>");
		out.write("                  <w:sz-cs w:val='24'/>");
		out.write("                </w:rPr>");
		out.write("                <w:tab wx:wTab='120' wx:tlc='none' wx:cTlc='0'/>");
		out.write("              </w:r>");
		out.write("              <w:r>");
		out.write("                <w:rPr>");
		out.write("                  <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:cs='新細明體' w:hint='fareast'/>");
		out.write("                  <wx:font wx:val='標楷體'/>");
		out.write("                  <w:kern w:val='0'/>");
		out.write("                  <w:sz-cs w:val='24'/>");
		out.write("                </w:rPr>");
		out.write("                <w:tab wx:wTab='480' wx:tlc='none' wx:cTlc='3'/>");
		out.write("              </w:r>");
		out.write("              <w:r>");
		out.write("                <w:rPr>");
		out.write("                  <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:cs='新細明體' w:hint='fareast'/>");
		out.write("                  <wx:font wx:val='標楷體'/>");
		out.write("                  <w:kern w:val='0'/>");
		out.write("                  <w:sz-cs w:val='24'/>");
		out.write("                </w:rPr>");
		out.write("                <w:tab wx:wTab='480' wx:tlc='none' wx:cTlc='3'/>");
		out.write("                <w:t>教師(Instructor)：</w:t>");
		out.write("              </w:r>");
		out.write("              <w:proofErr w:type='spellStart'/>");
		out.write("              <w:r>");
		out.write("                <w:rPr>");
		out.write("                  <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:cs='新細明體' w:hint='fareast'/>");
		out.write("                  <wx:font wx:val='標楷體'/>");
		out.write("                  <w:kern w:val='0'/>");
		out.write("                  <w:sz-cs w:val='24'/>");
		out.write("                </w:rPr>");
		
		
		if(map.get("cname")==null){
			out.write("                <w:t>"+manager.replaceChar4XML(manager.ezGetString("SELECT cname FROM dempl WHERE idno='"+map.get("techid")+"'"))+"</w:t>");
		}else{
			out.write("                <w:t>"+map.get("cname")+"</w:t>");
		}
		//out.write("                <w:t>"+map.get("cname")+"</w:t>");
		
		
		
		out.write("              </w:r>");
		
		out.write("              <w:proofErr w:type='spellEnd'/>");
		out.write("            </w:p>");
		out.write("          </w:tc>");
		out.write("        </w:tr>");
		out.write("        <w:tr>");
		out.write("          <w:trPr>");
		out.write("            <w:trHeight w:val='402'/>");
		out.write("          </w:trPr>");
		out.write("          <w:tc>");
		out.write("            <w:tcPr>");
		out.write("              <w:tcW w:w='10509' w:type='dxa'/>");
		out.write("              <w:gridSpan w:val='2'/>");
		out.write("              <w:tcBorders>");
		out.write("                <w:top w:val='nil'/>");
		out.write("                <w:left w:val='single' w:sz='4' wx:bdrwidth='10' w:space='0' w:color='auto'/>");
		out.write("                <w:bottom w:val='nil'/>");
		out.write("                <w:right w:val='single' w:sz='4' wx:bdrwidth='10' w:space='0' w:color='000000'/>");
		out.write("              </w:tcBorders>");
		out.write("              <w:shd w:val='clear' w:color='auto' w:fill='auto'/>");
		out.write("              <w:noWrap/>");
		out.write("              <w:vAlign w:val='center'/>");
		out.write("            </w:tcPr>");
		out.write("            <w:p>");
		out.write("              <w:pPr>");
		out.write("                <w:widowControl/>");
		out.write("                <w:rPr>");
		out.write("                  <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:cs='新細明體'/>");
		out.write("                  <wx:font wx:val='標楷體'/>");
		out.write("                  <w:kern w:val='0'/>");
		out.write("                  <w:sz-cs w:val='24'/>");
		out.write("                </w:rPr>");
		out.write("              </w:pPr>");
		out.write("              <w:r>");
		out.write("                <w:rPr>");
		out.write("                  <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:cs='新細明體' w:hint='fareast'/>");
		out.write("                  <wx:font wx:val='標楷體'/>");
		out.write("                  <w:kern w:val='0'/>");
		out.write("                  <w:sz-cs w:val='24'/>");
		out.write("                </w:rPr>");
		out.write("                <w:t>科目名稱(Course Title)：</w:t>");
		out.write("              </w:r>");
		out.write("              <w:proofErr w:type='spellStart'/>");
		out.write("              <w:r>");
		out.write("                <w:rPr>");
		out.write("                  <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:cs='新細明體' w:hint='fareast'/>");
		out.write("                  <wx:font wx:val='標楷體'/>");
		out.write("                  <w:kern w:val='0'/>");
		out.write("                  <w:sz-cs w:val='24'/>");
		out.write("                </w:rPr>");
		out.write("                <w:t>"+manager.replaceChar4XML(map.get("chi_name").toString())+"</w:t>");
		out.write("              </w:r>");
		out.write("              <w:proofErr w:type='spellEnd'/>");
		out.write("            </w:p>");
		out.write("          </w:tc>");
		out.write("        </w:tr>");
		out.write("        <w:tr>");
		out.write("          <w:trPr>");
		out.write("            <w:trHeight w:val='402'/>");
		out.write("          </w:trPr>");
		out.write("          <w:tc>");
		out.write("            <w:tcPr>");
		out.write("              <w:tcW w:w='10509' w:type='dxa'/>");
		out.write("              <w:gridSpan w:val='2'/>");
		out.write("              <w:tcBorders>");
		out.write("                <w:top w:val='nil'/>");
		out.write("                <w:left w:val='single' w:sz='4' wx:bdrwidth='10' w:space='0' w:color='auto'/>");
		out.write("                <w:bottom w:val='nil'/>");
		out.write("                <w:right w:val='single' w:sz='4' wx:bdrwidth='10' w:space='0' w:color='000000'/>");
		out.write("              </w:tcBorders>");
		out.write("              <w:shd w:val='clear' w:color='auto' w:fill='auto'/>");
		out.write("              <w:noWrap/>");
		out.write("              <w:vAlign w:val='center'/>");
		out.write("            </w:tcPr>");
		out.write("            <w:p>");
		out.write("              <w:pPr>");
		out.write("                <w:widowControl/>");
		out.write("                <w:rPr>");
		out.write("                  <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:cs='新細明體'/>");
		out.write("                  <wx:font wx:val='標楷體'/>");
		out.write("                  <w:kern w:val='0'/>");
		out.write("                  <w:sz-cs w:val='24'/>");
		out.write("                </w:rPr>");
		out.write("              </w:pPr>");
		out.write("              <w:r>");
		out.write("                <w:rPr>");
		out.write("                  <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:cs='新細明體' w:hint='fareast'/>");
		out.write("                  <wx:font wx:val='標楷體'/>");
		out.write("                  <w:kern w:val='0'/>");
		out.write("                  <w:sz-cs w:val='24'/>");
		out.write("                </w:rPr>");
		out.write("                <w:t>英文科目名稱(Course in English)："+manager.replaceChar4XML((String)map.get("eng_name"))+"</w:t>");
		out.write("              </w:r>");
		out.write("            </w:p>");
		out.write("          </w:tc>");
		out.write("        </w:tr>");
		out.write("        <w:tr>");
		out.write("          <w:trPr>");
		out.write("            <w:trHeight w:val='402'/>");
		out.write("          </w:trPr>");
		out.write("          <w:tc>");
		out.write("            <w:tcPr>");
		out.write("              <w:tcW w:w='10509' w:type='dxa'/>");
		out.write("              <w:gridSpan w:val='2'/>");
		out.write("              <w:tcBorders>");
		out.write("                <w:top w:val='nil'/>");
		out.write("                <w:left w:val='single' w:sz='4' wx:bdrwidth='10' w:space='0' w:color='auto'/>");
		out.write("                <w:bottom w:val='single' w:sz='4' wx:bdrwidth='10' w:space='0' w:color='auto'/>");
		out.write("                <w:right w:val='single' w:sz='4' wx:bdrwidth='10' w:space='0' w:color='000000'/>");
		out.write("              </w:tcBorders>");
		out.write("              <w:shd w:val='clear' w:color='auto' w:fill='auto'/>");
		out.write("              <w:noWrap/>");
		out.write("              <w:vAlign w:val='center'/>");
		out.write("            </w:tcPr>");
		out.write("            <w:p>");
		out.write("              <w:pPr>");
		out.write("                <w:widowControl/>");
		out.write("                <w:rPr>");
		out.write("                  <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:cs='新細明體'/>");
		out.write("                  <wx:font wx:val='標楷體'/>");
		out.write("                  <w:kern w:val='0'/>");
		out.write("                  <w:sz-cs w:val='24'/>");
		out.write("                </w:rPr>");
		out.write("              </w:pPr>");
		out.write("              <w:r>");
		out.write("                <w:rPr>");
		out.write("                  <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:cs='新細明體' w:hint='fareast'/>");
		out.write("                  <wx:font wx:val='標楷體'/>");
		out.write("                  <w:kern w:val='0'/>");
		out.write("                  <w:sz-cs w:val='24'/>");
		out.write("                </w:rPr>");
		out.write("                <w:t>學年(School Year)：</w:t>");
		out.write("              </w:r>");
		out.write("              <w:proofErr w:type='spellStart'/>");
		out.write("              <w:r>");
		out.write("                <w:rPr>");
		out.write("                  <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:cs='新細明體' w:hint='fareast'/>");
		out.write("                  <wx:font wx:val='標楷體'/>");
		out.write("                  <w:kern w:val='0'/>");
		out.write("                  <w:sz-cs w:val='24'/>");
		out.write("                </w:rPr>");
		out.write("                <w:t>"+map.get("school_year")+"</w:t>");
		out.write("              </w:r>");
		out.write("              <w:proofErr w:type='spellEnd'/>");
		out.write("              <w:r>");
		out.write("                <w:rPr>");
		out.write("                  <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:cs='新細明體' w:hint='fareast'/>");
		out.write("                  <wx:font wx:val='標楷體'/>");
		out.write("                  <w:kern w:val='0'/>");
		out.write("                  <w:sz-cs w:val='24'/>");
		out.write("                </w:rPr>");
		out.write("                <w:tab wx:wTab='360' wx:tlc='none' wx:cTlc='2'/>");
		out.write("              </w:r>");
		out.write("              <w:r>");
		out.write("                <w:rPr>");
		out.write("                  <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:cs='新細明體' w:hint='fareast'/>");
		out.write("                  <wx:font wx:val='標楷體'/>");
		out.write("                  <w:kern w:val='0'/>");
		out.write("                  <w:sz-cs w:val='24'/>");
		out.write("                </w:rPr>");
		out.write("                <w:tab wx:wTab='480' wx:tlc='none' wx:cTlc='3'/>");
		out.write("              </w:r>");
		out.write("              <w:r>");
		out.write("                <w:rPr>");
		out.write("                  <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:cs='新細明體' w:hint='fareast'/>");
		out.write("                  <wx:font wx:val='標楷體'/>");
		out.write("                  <w:kern w:val='0'/>");
		out.write("                  <w:sz-cs w:val='24'/>");
		out.write("                </w:rPr>");
		out.write("                <w:tab wx:wTab='480' wx:tlc='none' wx:cTlc='3'/>");
		out.write("                <w:t>學期(Semester)：</w:t>");
		out.write("              </w:r>");
		out.write("              <w:proofErr w:type='spellStart'/>");
		out.write("              <w:r>");
		out.write("                <w:rPr>");
		out.write("                  <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:cs='新細明體' w:hint='fareast'/>");
		out.write("                  <wx:font wx:val='標楷體'/>");
		out.write("                  <w:kern w:val='0'/>");
		out.write("                  <w:sz-cs w:val='24'/>");
		out.write("                </w:rPr>");
		out.write("                <w:t>"+map.get("Sterm")+"</w:t>");
		out.write("              </w:r>");
		out.write("              <w:proofErr w:type='spellEnd'/>");
		out.write("              <w:r>");
		out.write("                <w:rPr>");
		out.write("                  <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:cs='新細明體' w:hint='fareast'/>");
		out.write("                  <wx:font wx:val='標楷體'/>");
		out.write("                  <w:kern w:val='0'/>");
		out.write("                  <w:sz-cs w:val='24'/>");
		out.write("                </w:rPr>");
		out.write("                <w:tab wx:wTab='240' wx:tlc='none' wx:cTlc='1'/>");
		out.write("              </w:r>");
		out.write("              <w:r>");
		out.write("                <w:rPr>");
		out.write("                  <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:cs='新細明體' w:hint='fareast'/>");
		out.write("                  <wx:font wx:val='標楷體'/>");
		out.write("                  <w:kern w:val='0'/>");
		out.write("                  <w:sz-cs w:val='24'/>");
		out.write("                </w:rPr>");
		out.write("                <w:tab wx:wTab='480' wx:tlc='none' wx:cTlc='3'/>");
		out.write("              </w:r>");
		out.write("              <w:r>");
		out.write("                <w:rPr>");
		out.write("                  <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:cs='新細明體' w:hint='fareast'/>");
		out.write("                  <wx:font wx:val='標楷體'/>");
		out.write("                  <w:kern w:val='0'/>");
		out.write("                  <w:sz-cs w:val='24'/>");
		out.write("                </w:rPr>");
		out.write("                <w:tab wx:wTab='480' wx:tlc='none' wx:cTlc='3'/>");
		out.write("                <w:t>學分數(Credit Hours)："+map.get("credit")+"</w:t>");
		out.write("              </w:r>");
		out.write("            </w:p>");
		out.write("          </w:tc>");
		out.write("        </w:tr>");
		out.write("        <w:tr>");
		out.write("          <w:trPr>");
		out.write("            <w:trHeight w:val='402'/>");
		out.write("          </w:trPr>");
		out.write("          <w:tc>");
		out.write("            <w:tcPr>");
		out.write("              <w:tcW w:w='10509' w:type='dxa'/>");
		out.write("              <w:gridSpan w:val='2'/>");
		out.write("              <w:tcBorders>");
		out.write("                <w:top w:val='single' w:sz='4' wx:bdrwidth='10' w:space='0' w:color='auto'/>");
		out.write("                <w:left w:val='nil'/>");
		out.write("                <w:bottom w:val='single' w:sz='4' wx:bdrwidth='10' w:space='0' w:color='auto'/>");
		out.write("                <w:right w:val='nil'/>");
		out.write("              </w:tcBorders>");
		out.write("              <w:shd w:val='clear' w:color='auto' w:fill='auto'/>");
		out.write("              <w:noWrap/>");
		out.write("              <w:vAlign w:val='center'/>");
		out.write("            </w:tcPr>");
		out.write("            <w:p>");
		out.write("              <w:pPr>");
		out.write("                <w:widowControl/>");
		out.write("                <w:jc w:val='center'/>");
		out.write("                <w:rPr>");
		out.write("                  <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:cs='新細明體'/>");
		out.write("                  <wx:font wx:val='標楷體'/>");
		out.write("                  <w:kern w:val='0'/>");
		out.write("                  <w:sz w:val='28'/>");
		out.write("                  <w:sz-cs w:val='28'/>");
		out.write("                </w:rPr>");
		out.write("              </w:pPr>");
		out.write("              <w:r>");
		out.write("                <w:rPr>");
		out.write("                  <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:cs='新細明體' w:hint='fareast'/>");
		out.write("                  <wx:font wx:val='標楷體'/>");
		out.write("                  <w:kern w:val='0'/>");
		out.write("                  <w:sz w:val='28'/>");
		out.write("                  <w:sz-cs w:val='28'/>");
		out.write("                </w:rPr>");
		out.write("                <w:t>中文課程簡介</w:t>");
		out.write("              </w:r>");
		out.write("            </w:p>");
		out.write("          </w:tc>");
		out.write("        </w:tr>");
		out.write("        <w:proofErr w:type='spellStart'/>");
		out.write("        <w:tr>");
		out.write("          <w:trPr>");
		out.write("            <w:trHeight w:val='582'/>");
		out.write("          </w:trPr>");
		out.write("          <w:tc>");
		out.write("            <w:tcPr>");
		out.write("              <w:tcW w:w='10509' w:type='dxa'/>");
		out.write("              <w:gridSpan w:val='2'/>");
		out.write("              <w:vmerge w:val='restart'/>");
		out.write("              <w:tcBorders>");
		out.write("                <w:top w:val='single' w:sz='4' wx:bdrwidth='10' w:space='0' w:color='auto'/>");
		out.write("                <w:left w:val='single' w:sz='4' wx:bdrwidth='10' w:space='0' w:color='auto'/>");
		out.write("                <w:bottom w:val='single' w:sz='4' wx:bdrwidth='10' w:space='0' w:color='000000'/>");
		out.write("                <w:right w:val='single' w:sz='4' wx:bdrwidth='10' w:space='0' w:color='000000'/>");
		out.write("              </w:tcBorders>");
		out.write("            </w:tcPr>");
		out.write("            <w:p>");
		out.write("              <w:pPr>");
		out.write("                <w:widowControl/>");
		out.write("                <w:jc w:val='both'/>");
		out.write("                <w:rPr>");
		out.write("                  <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:cs='新細明體'/>");
		out.write("                  <wx:font wx:val='標楷體'/>");
		out.write("                  <w:kern w:val='0'/>");
		out.write("                  <w:sz-cs w:val='24'/>");
		out.write("                </w:rPr>");
		out.write("              </w:pPr>");
		out.write("              <w:r>");
		out.write("                <w:rPr>");
		out.write("                  <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:cs='新細明體' w:hint='fareast'/>");
		out.write("                  <wx:font wx:val='標楷體'/>");
		out.write("                  <w:kern w:val='0'/>");
		out.write("                  <w:sz-cs w:val='24'/>");
		out.write("                </w:rPr>");
		
		
		intor=new HashMap();
		try{
			intor=manager.parseIntr(manager.replaceChar4XML((String)map.get("Introduction")));
		}catch(Exception e){
			intor.put("chi", "解析內容有誤");
			intor.put("eng", "解析內容有誤");
		}
		if(intor==null){
			intor=new HashMap();
			intor.put("chi", "解析內容有誤");
			intor.put("eng", "解析內容有誤");
		}
		
		out.write("                <w:t>"+intor.get("chi")+"</w:t>");
		out.write("              </w:r>");
		out.write("              <w:proofErr w:type='spellEnd'/>");
		out.write("            </w:p>");
		out.write("          </w:tc>");
		out.write("        </w:tr>");
		out.write("        <w:tr>");
		out.write("          <w:trPr>");
		out.write("            <w:trHeight w:val='582'/>");
		out.write("          </w:trPr>");
		out.write("          <w:tc>");
		out.write("            <w:tcPr>");
		out.write("              <w:tcW w:w='10509' w:type='dxa'/>");
		out.write("              <w:gridSpan w:val='2'/>");
		out.write("              <w:vmerge/>");
		out.write("              <w:tcBorders>");
		out.write("                <w:top w:val='single' w:sz='4' wx:bdrwidth='10' w:space='0' w:color='auto'/>");
		out.write("                <w:left w:val='single' w:sz='4' wx:bdrwidth='10' w:space='0' w:color='auto'/>");
		out.write("                <w:bottom w:val='single' w:sz='4' wx:bdrwidth='10' w:space='0' w:color='000000'/>");
		out.write("                <w:right w:val='single' w:sz='4' wx:bdrwidth='10' w:space='0' w:color='000000'/>");
		out.write("              </w:tcBorders>");
		out.write("              <w:vAlign w:val='center'/>");
		out.write("            </w:tcPr>");
		out.write("            <w:p>");
		out.write("              <w:pPr>");
		out.write("                <w:widowControl/>");
		out.write("                <w:rPr>");
		out.write("                  <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:cs='新細明體'/>");
		out.write("                  <wx:font wx:val='標楷體'/>");
		out.write("                  <w:kern w:val='0'/>");
		out.write("                  <w:sz-cs w:val='24'/>");
		out.write("                </w:rPr>");
		out.write("              </w:pPr>");
		out.write("            </w:p>");
		out.write("          </w:tc>");
		out.write("        </w:tr>");
		out.write("        <w:tr>");
		out.write("          <w:trPr>");
		out.write("            <w:trHeight w:val='582'/>");
		out.write("          </w:trPr>");
		out.write("          <w:tc>");
		out.write("            <w:tcPr>");
		out.write("              <w:tcW w:w='10509' w:type='dxa'/>");
		out.write("              <w:gridSpan w:val='2'/>");
		out.write("              <w:vmerge/>");
		out.write("              <w:tcBorders>");
		out.write("                <w:top w:val='single' w:sz='4' wx:bdrwidth='10' w:space='0' w:color='auto'/>");
		out.write("                <w:left w:val='single' w:sz='4' wx:bdrwidth='10' w:space='0' w:color='auto'/>");
		out.write("                <w:bottom w:val='single' w:sz='4' wx:bdrwidth='10' w:space='0' w:color='000000'/>");
		out.write("                <w:right w:val='single' w:sz='4' wx:bdrwidth='10' w:space='0' w:color='000000'/>");
		out.write("              </w:tcBorders>");
		out.write("              <w:vAlign w:val='center'/>");
		out.write("            </w:tcPr>");
		out.write("            <w:p>");
		out.write("              <w:pPr>");
		out.write("                <w:widowControl/>");
		out.write("                <w:rPr>");
		out.write("                  <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:cs='新細明體'/>");
		out.write("                  <wx:font wx:val='標楷體'/>");
		out.write("                  <w:kern w:val='0'/>");
		out.write("                  <w:sz-cs w:val='24'/>");
		out.write("                </w:rPr>");
		out.write("              </w:pPr>");
		out.write("            </w:p>");
		out.write("          </w:tc>");
		out.write("        </w:tr>");
		out.write("        <w:tr>");
		out.write("          <w:trPr>");
		out.write("            <w:trHeight w:val='582'/>");
		out.write("          </w:trPr>");
		out.write("          <w:tc>");
		out.write("            <w:tcPr>");
		out.write("              <w:tcW w:w='10509' w:type='dxa'/>");
		out.write("              <w:gridSpan w:val='2'/>");
		out.write("              <w:vmerge/>");
		out.write("              <w:tcBorders>");
		out.write("                <w:top w:val='single' w:sz='4' wx:bdrwidth='10' w:space='0' w:color='auto'/>");
		out.write("                <w:left w:val='single' w:sz='4' wx:bdrwidth='10' w:space='0' w:color='auto'/>");
		out.write("                <w:bottom w:val='single' w:sz='4' wx:bdrwidth='10' w:space='0' w:color='000000'/>");
		out.write("                <w:right w:val='single' w:sz='4' wx:bdrwidth='10' w:space='0' w:color='000000'/>");
		out.write("              </w:tcBorders>");
		out.write("              <w:vAlign w:val='center'/>");
		out.write("            </w:tcPr>");
		out.write("            <w:p>");
		out.write("              <w:pPr>");
		out.write("                <w:widowControl/>");
		out.write("                <w:rPr>");
		out.write("                  <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:cs='新細明體'/>");
		out.write("                  <wx:font wx:val='標楷體'/>");
		out.write("                  <w:kern w:val='0'/>");
		out.write("                  <w:sz-cs w:val='24'/>");
		out.write("                </w:rPr>");
		out.write("              </w:pPr>");
		out.write("            </w:p>");
		out.write("          </w:tc>");
		out.write("        </w:tr>");
		out.write("        <w:tr>");
		out.write("          <w:trPr>");
		out.write("            <w:trHeight w:val='582'/>");
		out.write("          </w:trPr>");
		out.write("          <w:tc>");
		out.write("            <w:tcPr>");
		out.write("              <w:tcW w:w='10509' w:type='dxa'/>");
		out.write("              <w:gridSpan w:val='2'/>");
		out.write("              <w:vmerge/>");
		out.write("              <w:tcBorders>");
		out.write("                <w:top w:val='single' w:sz='4' wx:bdrwidth='10' w:space='0' w:color='auto'/>");
		out.write("                <w:left w:val='single' w:sz='4' wx:bdrwidth='10' w:space='0' w:color='auto'/>");
		out.write("                <w:bottom w:val='single' w:sz='4' wx:bdrwidth='10' w:space='0' w:color='000000'/>");
		out.write("                <w:right w:val='single' w:sz='4' wx:bdrwidth='10' w:space='0' w:color='000000'/>");
		out.write("              </w:tcBorders>");
		out.write("              <w:vAlign w:val='center'/>");
		out.write("            </w:tcPr>");
		out.write("            <w:p>");
		out.write("              <w:pPr>");
		out.write("                <w:widowControl/>");
		out.write("                <w:rPr>");
		out.write("                  <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:cs='新細明體'/>");
		out.write("                  <wx:font wx:val='標楷體'/>");
		out.write("                  <w:kern w:val='0'/>");
		out.write("                  <w:sz-cs w:val='24'/>");
		out.write("                </w:rPr>");
		out.write("              </w:pPr>");
		out.write("            </w:p>");
		out.write("          </w:tc>");
		out.write("        </w:tr>");
		out.write("        <w:tr>");
		out.write("          <w:trPr>");
		out.write("            <w:trHeight w:val='582'/>");
		out.write("          </w:trPr>");
		out.write("          <w:tc>");
		out.write("            <w:tcPr>");
		out.write("              <w:tcW w:w='10509' w:type='dxa'/>");
		out.write("              <w:gridSpan w:val='2'/>");
		out.write("              <w:vmerge/>");
		out.write("              <w:tcBorders>");
		out.write("                <w:top w:val='single' w:sz='4' wx:bdrwidth='10' w:space='0' w:color='auto'/>");
		out.write("                <w:left w:val='single' w:sz='4' wx:bdrwidth='10' w:space='0' w:color='auto'/>");
		out.write("                <w:bottom w:val='single' w:sz='4' wx:bdrwidth='10' w:space='0' w:color='000000'/>");
		out.write("                <w:right w:val='single' w:sz='4' wx:bdrwidth='10' w:space='0' w:color='000000'/>");
		out.write("              </w:tcBorders>");
		out.write("              <w:vAlign w:val='center'/>");
		out.write("            </w:tcPr>");
		out.write("            <w:p>");
		out.write("              <w:pPr>");
		out.write("                <w:widowControl/>");
		out.write("                <w:rPr>");
		out.write("                  <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:cs='新細明體'/>");
		out.write("                  <wx:font wx:val='標楷體'/>");
		out.write("                  <w:kern w:val='0'/>");
		out.write("                  <w:sz-cs w:val='24'/>");
		out.write("                </w:rPr>");
		out.write("              </w:pPr>");
		out.write("            </w:p>");
		out.write("          </w:tc>");
		out.write("        </w:tr>");
		out.write("        <w:tr>");
		out.write("          <w:trPr>");
		out.write("            <w:trHeight w:val='917'/>");
		out.write("          </w:trPr>");
		out.write("          <w:tc>");
		out.write("            <w:tcPr>");
		out.write("              <w:tcW w:w='10509' w:type='dxa'/>");
		out.write("              <w:gridSpan w:val='2'/>");
		out.write("              <w:vmerge/>");
		out.write("              <w:tcBorders>");
		out.write("                <w:top w:val='single' w:sz='4' wx:bdrwidth='10' w:space='0' w:color='auto'/>");
		out.write("                <w:left w:val='single' w:sz='4' wx:bdrwidth='10' w:space='0' w:color='auto'/>");
		out.write("                <w:bottom w:val='single' w:sz='4' wx:bdrwidth='10' w:space='0' w:color='000000'/>");
		out.write("                <w:right w:val='single' w:sz='4' wx:bdrwidth='10' w:space='0' w:color='000000'/>");
		out.write("              </w:tcBorders>");
		out.write("              <w:vAlign w:val='center'/>");
		out.write("            </w:tcPr>");
		out.write("            <w:p>");
		out.write("              <w:pPr>");
		out.write("                <w:widowControl/>");
		out.write("                <w:rPr>");
		out.write("                  <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:cs='新細明體'/>");
		out.write("                  <wx:font wx:val='標楷體'/>");
		out.write("                  <w:kern w:val='0'/>");
		out.write("                  <w:sz-cs w:val='24'/>");
		out.write("                </w:rPr>");
		out.write("              </w:pPr>");
		out.write("            </w:p>");
		out.write("          </w:tc>");
		out.write("        </w:tr>");
		out.write("        <w:tr>");
		out.write("          <w:trPr>");
		out.write("            <w:trHeight w:val='70'/>");
		out.write("          </w:trPr>");
		out.write("          <w:tc>");
		out.write("            <w:tcPr>");
		out.write("              <w:tcW w:w='10509' w:type='dxa'/>");
		out.write("              <w:gridSpan w:val='2'/>");
		out.write("              <w:tcBorders>");
		out.write("                <w:top w:val='single' w:sz='4' wx:bdrwidth='10' w:space='0' w:color='auto'/>");
		out.write("                <w:left w:val='nil'/>");
		out.write("                <w:bottom w:val='single' w:sz='4' wx:bdrwidth='10' w:space='0' w:color='auto'/>");
		out.write("                <w:right w:val='nil'/>");
		out.write("              </w:tcBorders>");
		out.write("              <w:shd w:val='clear' w:color='auto' w:fill='auto'/>");
		out.write("              <w:noWrap/>");
		out.write("              <w:vAlign w:val='center'/>");
		out.write("            </w:tcPr>");
		out.write("            <w:p>");
		out.write("              <w:pPr>");
		out.write("                <w:widowControl/>");
		out.write("                <w:jc w:val='center'/>");
		out.write("                <w:rPr>");
		out.write("                  <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:cs='新細明體'/>");
		out.write("                  <wx:font wx:val='標楷體'/>");
		out.write("                  <w:kern w:val='0'/>");
		out.write("                  <w:sz w:val='28'/>");
		out.write("                  <w:sz-cs w:val='28'/>");
		out.write("                </w:rPr>");
		out.write("              </w:pPr>");
		out.write("              <w:r>");
		out.write("                <w:rPr>");
		out.write("                  <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:cs='新細明體' w:hint='fareast'/>");
		out.write("                  <wx:font wx:val='標楷體'/>");
		out.write("                  <w:kern w:val='0'/>");
		out.write("                  <w:sz w:val='28'/>");
		out.write("                  <w:sz-cs w:val='28'/>");
		out.write("                </w:rPr>");
		out.write("                <w:t>英文課程簡介</w:t>");
		out.write("              </w:r>");
		out.write("            </w:p>");
		out.write("          </w:tc>");
		out.write("        </w:tr>");
		out.write("        <w:proofErr w:type='spellStart'/>");
		out.write("        <w:tr>");
		out.write("          <w:trPr>");
		out.write("            <w:trHeight w:val='402'/>");
		out.write("          </w:trPr>");
		out.write("          <w:tc>");
		out.write("            <w:tcPr>");
		out.write("              <w:tcW w:w='10509' w:type='dxa'/>");
		out.write("              <w:gridSpan w:val='2'/>");
		out.write("              <w:vmerge w:val='restart'/>");
		out.write("              <w:tcBorders>");
		out.write("                <w:top w:val='single' w:sz='4' wx:bdrwidth='10' w:space='0' w:color='auto'/>");
		out.write("                <w:left w:val='single' w:sz='4' wx:bdrwidth='10' w:space='0' w:color='auto'/>");
		out.write("                <w:bottom w:val='single' w:sz='4' wx:bdrwidth='10' w:space='0' w:color='000000'/>");
		out.write("                <w:right w:val='single' w:sz='4' wx:bdrwidth='10' w:space='0' w:color='000000'/>");
		out.write("              </w:tcBorders>");
		out.write("              <w:shd w:val='clear' w:color='auto' w:fill='auto'/>");
		out.write("            </w:tcPr>");
		out.write("            <w:p>");
		out.write("              <w:pPr>");
		out.write("                <w:widowControl/>");
		out.write("                <w:rPr>");
		out.write("                  <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:cs='新細明體'/>");
		out.write("                  <wx:font wx:val='標楷體'/>");
		out.write("                  <w:kern w:val='0'/>");
		out.write("                  <w:sz-cs w:val='24'/>");
		out.write("                </w:rPr>");
		out.write("              </w:pPr>");
		out.write("              <w:r>");
		out.write("                <w:rPr>");
		out.write("                  <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:cs='新細明體' w:hint='fareast'/>");
		out.write("                  <wx:font wx:val='標楷體'/>");
		out.write("                  <w:kern w:val='0'/>");
		out.write("                  <w:sz-cs w:val='24'/>");
		out.write("                </w:rPr>");
		
		
		
		out.write("                <w:t>"+intor.get("eng")+"</w:t>");
		out.write("              </w:r>");
		out.write("              <w:proofErr w:type='spellEnd'/>");
		out.write("            </w:p>");
		out.write("          </w:tc>");
		out.write("        </w:tr>");
		out.write("        <w:tr>");
		out.write("          <w:trPr>");
		out.write("            <w:trHeight w:val='582'/>");
		out.write("          </w:trPr>");
		out.write("          <w:tc>");
		out.write("            <w:tcPr>");
		out.write("              <w:tcW w:w='10509' w:type='dxa'/>");
		out.write("              <w:gridSpan w:val='2'/>");
		out.write("              <w:vmerge/>");
		out.write("              <w:tcBorders>");
		out.write("                <w:top w:val='single' w:sz='4' wx:bdrwidth='10' w:space='0' w:color='auto'/>");
		out.write("                <w:left w:val='single' w:sz='4' wx:bdrwidth='10' w:space='0' w:color='auto'/>");
		out.write("                <w:bottom w:val='single' w:sz='4' wx:bdrwidth='10' w:space='0' w:color='000000'/>");
		out.write("                <w:right w:val='single' w:sz='4' wx:bdrwidth='10' w:space='0' w:color='000000'/>");
		out.write("              </w:tcBorders>");
		out.write("              <w:vAlign w:val='center'/>");
		out.write("            </w:tcPr>");
		out.write("            <w:p>");
		out.write("              <w:pPr>");
		out.write("                <w:widowControl/>");
		out.write("                <w:rPr>");
		out.write("                  <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:cs='新細明體'/>");
		out.write("                  <wx:font wx:val='標楷體'/>");
		out.write("                  <w:kern w:val='0'/>");
		out.write("                  <w:sz-cs w:val='24'/>");
		out.write("                </w:rPr>");
		out.write("              </w:pPr>");
		out.write("            </w:p>");
		out.write("          </w:tc>");
		out.write("        </w:tr>");
		out.write("        <w:tr>");
		out.write("          <w:trPr>");
		out.write("            <w:trHeight w:val='582'/>");
		out.write("          </w:trPr>");
		out.write("          <w:tc>");
		out.write("            <w:tcPr>");
		out.write("              <w:tcW w:w='10509' w:type='dxa'/>");
		out.write("              <w:gridSpan w:val='2'/>");
		out.write("              <w:vmerge/>");
		out.write("              <w:tcBorders>");
		out.write("                <w:top w:val='single' w:sz='4' wx:bdrwidth='10' w:space='0' w:color='auto'/>");
		out.write("                <w:left w:val='single' w:sz='4' wx:bdrwidth='10' w:space='0' w:color='auto'/>");
		out.write("                <w:bottom w:val='single' w:sz='4' wx:bdrwidth='10' w:space='0' w:color='000000'/>");
		out.write("                <w:right w:val='single' w:sz='4' wx:bdrwidth='10' w:space='0' w:color='000000'/>");
		out.write("              </w:tcBorders>");
		out.write("              <w:vAlign w:val='center'/>");
		out.write("            </w:tcPr>");
		out.write("            <w:p>");
		out.write("              <w:pPr>");
		out.write("                <w:widowControl/>");
		out.write("                <w:rPr>");
		out.write("                  <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:cs='新細明體'/>");
		out.write("                  <wx:font wx:val='標楷體'/>");
		out.write("                  <w:kern w:val='0'/>");
		out.write("                  <w:sz-cs w:val='24'/>");
		out.write("                </w:rPr>");
		out.write("              </w:pPr>");
		out.write("            </w:p>");
		out.write("          </w:tc>");
		out.write("        </w:tr>");
		out.write("        <w:tr>");
		out.write("          <w:trPr>");
		out.write("            <w:trHeight w:val='582'/>");
		out.write("          </w:trPr>");
		out.write("          <w:tc>");
		out.write("            <w:tcPr>");
		out.write("              <w:tcW w:w='10509' w:type='dxa'/>");
		out.write("              <w:gridSpan w:val='2'/>");
		out.write("              <w:vmerge/>");
		out.write("              <w:tcBorders>");
		out.write("                <w:top w:val='single' w:sz='4' wx:bdrwidth='10' w:space='0' w:color='auto'/>");
		out.write("                <w:left w:val='single' w:sz='4' wx:bdrwidth='10' w:space='0' w:color='auto'/>");
		out.write("                <w:bottom w:val='single' w:sz='4' wx:bdrwidth='10' w:space='0' w:color='000000'/>");
		out.write("                <w:right w:val='single' w:sz='4' wx:bdrwidth='10' w:space='0' w:color='000000'/>");
		out.write("              </w:tcBorders>");
		out.write("              <w:vAlign w:val='center'/>");
		out.write("            </w:tcPr>");
		out.write("            <w:p>");
		out.write("              <w:pPr>");
		out.write("                <w:widowControl/>");
		out.write("                <w:rPr>");
		out.write("                  <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:cs='新細明體'/>");
		out.write("                  <wx:font wx:val='標楷體'/>");
		out.write("                  <w:kern w:val='0'/>");
		out.write("                  <w:sz-cs w:val='24'/>");
		out.write("                </w:rPr>");
		out.write("              </w:pPr>");
		out.write("            </w:p>");
		out.write("          </w:tc>");
		out.write("        </w:tr>");
		out.write("        <w:tr>");
		out.write("          <w:trPr>");
		out.write("            <w:trHeight w:val='582'/>");
		out.write("          </w:trPr>");
		out.write("          <w:tc>");
		out.write("            <w:tcPr>");
		out.write("              <w:tcW w:w='10509' w:type='dxa'/>");
		out.write("              <w:gridSpan w:val='2'/>");
		out.write("              <w:vmerge/>");
		out.write("              <w:tcBorders>");
		out.write("                <w:top w:val='single' w:sz='4' wx:bdrwidth='10' w:space='0' w:color='auto'/>");
		out.write("                <w:left w:val='single' w:sz='4' wx:bdrwidth='10' w:space='0' w:color='auto'/>");
		out.write("                <w:bottom w:val='single' w:sz='4' wx:bdrwidth='10' w:space='0' w:color='000000'/>");
		out.write("                <w:right w:val='single' w:sz='4' wx:bdrwidth='10' w:space='0' w:color='000000'/>");
		out.write("              </w:tcBorders>");
		out.write("              <w:vAlign w:val='center'/>");
		out.write("            </w:tcPr>");
		out.write("            <w:p>");
		out.write("              <w:pPr>");
		out.write("                <w:widowControl/>");
		out.write("                <w:rPr>");
		out.write("                  <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:cs='新細明體'/>");
		out.write("                  <wx:font wx:val='標楷體'/>");
		out.write("                  <w:kern w:val='0'/>");
		out.write("                  <w:sz-cs w:val='24'/>");
		out.write("                </w:rPr>");
		out.write("              </w:pPr>");
		out.write("            </w:p>");
		out.write("          </w:tc>");
		out.write("        </w:tr>");
		out.write("        <w:tr>");
		out.write("          <w:trPr>");
		out.write("            <w:trHeight w:val='582'/>");
		out.write("          </w:trPr>");
		out.write("          <w:tc>");
		out.write("            <w:tcPr>");
		out.write("              <w:tcW w:w='10509' w:type='dxa'/>");
		out.write("              <w:gridSpan w:val='2'/>");
		out.write("              <w:vmerge/>");
		out.write("              <w:tcBorders>");
		out.write("                <w:top w:val='single' w:sz='4' wx:bdrwidth='10' w:space='0' w:color='auto'/>");
		out.write("                <w:left w:val='single' w:sz='4' wx:bdrwidth='10' w:space='0' w:color='auto'/>");
		out.write("                <w:bottom w:val='single' w:sz='4' wx:bdrwidth='10' w:space='0' w:color='000000'/>");
		out.write("                <w:right w:val='single' w:sz='4' wx:bdrwidth='10' w:space='0' w:color='000000'/>");
		out.write("              </w:tcBorders>");
		out.write("              <w:vAlign w:val='center'/>");
		out.write("            </w:tcPr>");
		out.write("            <w:p>");
		out.write("              <w:pPr>");
		out.write("                <w:widowControl/>");
		out.write("                <w:rPr>");
		out.write("                  <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:cs='新細明體'/>");
		out.write("                  <wx:font wx:val='標楷體'/>");
		out.write("                  <w:kern w:val='0'/>");
		out.write("                  <w:sz-cs w:val='24'/>");
		out.write("                </w:rPr>");
		out.write("              </w:pPr>");
		out.write("            </w:p>");
		out.write("          </w:tc>");
		out.write("        </w:tr>");
		out.write("        <w:tr>");
		out.write("          <w:trPr>");
		out.write("            <w:trHeight w:val='582'/>");
		out.write("          </w:trPr>");
		out.write("          <w:tc>");
		out.write("            <w:tcPr>");
		out.write("              <w:tcW w:w='10509' w:type='dxa'/>");
		out.write("              <w:gridSpan w:val='2'/>");
		out.write("              <w:vmerge/>");
		out.write("              <w:tcBorders>");
		out.write("                <w:top w:val='single' w:sz='4' wx:bdrwidth='10' w:space='0' w:color='auto'/>");
		out.write("                <w:left w:val='single' w:sz='4' wx:bdrwidth='10' w:space='0' w:color='auto'/>");
		out.write("                <w:bottom w:val='single' w:sz='4' wx:bdrwidth='10' w:space='0' w:color='000000'/>");
		out.write("                <w:right w:val='single' w:sz='4' wx:bdrwidth='10' w:space='0' w:color='000000'/>");
		out.write("              </w:tcBorders>");
		out.write("              <w:vAlign w:val='center'/>");
		out.write("            </w:tcPr>");
		out.write("            <w:p>");
		out.write("              <w:pPr>");
		out.write("                <w:widowControl/>");
		out.write("                <w:rPr>");
		out.write("                  <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:cs='新細明體'/>");
		out.write("                  <wx:font wx:val='標楷體'/>");
		out.write("                  <w:kern w:val='0'/>");
		out.write("                  <w:sz-cs w:val='24'/>");
		out.write("                </w:rPr>");
		out.write("              </w:pPr>");
		out.write("            </w:p>");
		out.write("          </w:tc>");
		out.write("        </w:tr>");
		out.write("        <w:tr>");
		out.write("          <w:trPr>");
		out.write("            <w:trHeight w:val='582'/>");
		out.write("          </w:trPr>");
		out.write("          <w:tc>");
		out.write("            <w:tcPr>");
		out.write("              <w:tcW w:w='10509' w:type='dxa'/>");
		out.write("              <w:gridSpan w:val='2'/>");
		out.write("              <w:vmerge/>");
		out.write("              <w:tcBorders>");
		out.write("                <w:top w:val='single' w:sz='4' wx:bdrwidth='10' w:space='0' w:color='auto'/>");
		out.write("                <w:left w:val='single' w:sz='4' wx:bdrwidth='10' w:space='0' w:color='auto'/>");
		out.write("                <w:bottom w:val='single' w:sz='4' wx:bdrwidth='10' w:space='0' w:color='000000'/>");
		out.write("                <w:right w:val='single' w:sz='4' wx:bdrwidth='10' w:space='0' w:color='000000'/>");
		out.write("              </w:tcBorders>");
		out.write("              <w:vAlign w:val='center'/>");
		out.write("            </w:tcPr>");
		out.write("            <w:p>");
		out.write("              <w:pPr>");
		out.write("                <w:widowControl/>");
		out.write("                <w:rPr>");
		out.write("                  <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:cs='新細明體'/>");
		out.write("                  <wx:font wx:val='標楷體'/>");
		out.write("                  <w:kern w:val='0'/>");
		out.write("                  <w:sz-cs w:val='24'/>");
		out.write("                </w:rPr>");
		out.write("              </w:pPr>");
		out.write("            </w:p>");
		out.write("          </w:tc>");
		out.write("        </w:tr>");
		out.write("        <w:tr>");
		out.write("          <w:trPr>");
		out.write("            <w:trHeight w:val='360'/>");
		out.write("          </w:trPr>");
		out.write("          <w:tc>");
		out.write("            <w:tcPr>");
		out.write("              <w:tcW w:w='10509' w:type='dxa'/>");
		out.write("              <w:gridSpan w:val='2'/>");
		out.write("              <w:vmerge/>");
		out.write("              <w:tcBorders>");
		out.write("                <w:top w:val='single' w:sz='4' wx:bdrwidth='10' w:space='0' w:color='auto'/>");
		out.write("                <w:left w:val='single' w:sz='4' wx:bdrwidth='10' w:space='0' w:color='auto'/>");
		out.write("                <w:bottom w:val='single' w:sz='4' wx:bdrwidth='10' w:space='0' w:color='000000'/>");
		out.write("                <w:right w:val='single' w:sz='4' wx:bdrwidth='10' w:space='0' w:color='000000'/>");
		out.write("              </w:tcBorders>");
		out.write("              <w:vAlign w:val='center'/>");
		out.write("            </w:tcPr>");
		out.write("            <w:p>");
		out.write("              <w:pPr>");
		out.write("                <w:widowControl/>");
		out.write("                <w:rPr>");
		out.write("                  <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:cs='新細明體'/>");
		out.write("                  <wx:font wx:val='標楷體'/>");
		out.write("                  <w:kern w:val='0'/>");
		out.write("                  <w:sz-cs w:val='24'/>");
		out.write("                </w:rPr>");
		out.write("              </w:pPr>");
		out.write("            </w:p>");
		out.write("          </w:tc>");
		out.write("        </w:tr>");
		out.write("        <w:tr>");
		out.write("          <w:trPr>");
		out.write("            <w:trHeight w:val='1127'/>");
		out.write("          </w:trPr>");
		out.write("          <w:tc>");
		out.write("            <w:tcPr>");
		out.write("              <w:tcW w:w='10509' w:type='dxa'/>");
		out.write("              <w:gridSpan w:val='2'/>");
		out.write("              <w:vmerge/>");
		out.write("              <w:tcBorders>");
		out.write("                <w:top w:val='single' w:sz='4' wx:bdrwidth='10' w:space='0' w:color='auto'/>");
		out.write("                <w:left w:val='single' w:sz='4' wx:bdrwidth='10' w:space='0' w:color='auto'/>");
		out.write("                <w:bottom w:val='single' w:sz='4' wx:bdrwidth='10' w:space='0' w:color='000000'/>");
		out.write("                <w:right w:val='single' w:sz='4' wx:bdrwidth='10' w:space='0' w:color='000000'/>");
		out.write("              </w:tcBorders>");
		out.write("              <w:vAlign w:val='center'/>");
		out.write("            </w:tcPr>");
		out.write("            <w:p>");
		out.write("              <w:pPr>");
		out.write("                <w:widowControl/>");
		out.write("                <w:rPr>");
		out.write("                  <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:cs='新細明體'/>");
		out.write("                  <wx:font wx:val='標楷體'/>");
		out.write("                  <w:kern w:val='0'/>");
		out.write("                  <w:sz-cs w:val='24'/>");
		out.write("                </w:rPr>");
		out.write("              </w:pPr>");
		out.write("            </w:p>");
		out.write("          </w:tc>");
		out.write("        </w:tr>");
		out.write("        <w:tr>");
		out.write("          <w:trPr>");
		out.write("            <w:trHeight w:val='330'/>");
		out.write("          </w:trPr>");
		out.write("          <w:tc>");
		out.write("            <w:tcPr>");
		out.write("              <w:tcW w:w='103' w:type='dxa'/>");
		out.write("              <w:tcBorders>");
		out.write("                <w:top w:val='nil'/>");
		out.write("                <w:left w:val='nil'/>");
		out.write("                <w:bottom w:val='nil'/>");
		out.write("                <w:right w:val='nil'/>");
		out.write("              </w:tcBorders>");
		out.write("              <w:shd w:val='clear' w:color='auto' w:fill='auto'/>");
		out.write("              <w:noWrap/>");
		out.write("              <w:vAlign w:val='center'/>");
		out.write("            </w:tcPr>");
		out.write("            <w:p>");
		out.write("              <w:pPr>");
		out.write("                <w:widowControl/>");
		out.write("                <w:rPr>");
		out.write("                  <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:cs='新細明體'/>");
		out.write("                  <wx:font wx:val='標楷體'/>");
		out.write("                  <w:kern w:val='0'/>");
		out.write("                  <w:sz-cs w:val='24'/>");
		out.write("                </w:rPr>");
		out.write("              </w:pPr>");
		out.write("            </w:p>");
		out.write("          </w:tc>");
		out.write("          <w:tc>");
		out.write("            <w:tcPr>");
		out.write("              <w:tcW w:w='10406' w:type='dxa'/>");
		out.write("              <w:tcBorders>");
		out.write("                <w:top w:val='nil'/>");
		out.write("                <w:left w:val='nil'/>");
		out.write("                <w:bottom w:val='nil'/>");
		out.write("                <w:right w:val='nil'/>");
		out.write("              </w:tcBorders>");
		out.write("              <w:shd w:val='clear' w:color='auto' w:fill='auto'/>");
		out.write("              <w:noWrap/>");
		out.write("              <w:vAlign w:val='center'/>");
		out.write("            </w:tcPr>");
		out.write("            <w:p>");
		out.write("              <w:pPr>");
		out.write("                <w:widowControl/>");
		out.write("                <w:jc w:val='right'/>");
		out.write("                <w:rPr>");
		out.write("                  <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:cs='新細明體'/>");
		out.write("                  <wx:font wx:val='標楷體'/>");
		out.write("                  <w:kern w:val='0'/>");
		out.write("                  <w:sz-cs w:val='24'/>");
		out.write("                </w:rPr>");
		out.write("              </w:pPr>");
		out.write("              <w:r>");
		out.write("                <w:rPr>");
		out.write("                  <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:cs='新細明體' w:hint='fareast'/>");
		out.write("                  <wx:font wx:val='標楷體'/>");
		out.write("                  <w:kern w:val='0'/>");
		out.write("                  <w:sz-cs w:val='24'/>");
		out.write("                </w:rPr>");
		out.write("                <w:t>遵守智慧財產權觀念，不得非法影印</w:t>");
		out.write("              </w:r>");
		out.write("            </w:p>");
		out.write("          </w:tc>");
		out.write("        </w:tr>");
		out.write("      </w:tbl>");
		out.write("      <w:p>");
		out.write("        <w:pPr>");
		out.write("          <w:rPr>");
		out.write("            <w:rFonts w:hint='fareast'/>");
		out.write("          </w:rPr>");
		out.write("        </w:pPr>");
		out.write("      </w:p>");
		out.write("      <w:sectPr>");
		out.write("        <w:hdr w:type='odd'>");
		out.write("          <w:p>");
		out.write("            <w:pPr>");
		out.write("              <w:pStyle w:val='a3'/>");
		out.write("              <w:jc w:val='center'/>");
		out.write("              <w:rPr>");
		out.write("                <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體'/>");
		out.write("                <wx:font wx:val='標楷體'/>");
		out.write("                <w:sz w:val='36'/>");
		out.write("                <w:sz-cs w:val='36'/>");
		out.write("              </w:rPr>");
		out.write("            </w:pPr>");
		out.write("            <w:r>");
		out.write("              <w:rPr>");
		out.write("                <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:hint='fareast'/>");
		out.write("                <wx:font wx:val='標楷體'/>");
		out.write("                <w:sz w:val='36'/>");
		out.write("                <w:sz-cs w:val='36'/>");
		out.write("              </w:rPr>");
		out.write("              <w:t>任教科目中英文課程簡介</w:t>");
		out.write("            </w:r>");
		out.write("          </w:p>");
		out.write("          <w:p>");
		out.write("            <w:pPr>");
		out.write("              <w:pStyle w:val='a3'/>");
		out.write("              <w:jc w:val='center'/>");
		out.write("              <w:rPr>");
		out.write("                <w:rFonts w:hint='fareast'/>");
		out.write("                <w:sz w:val='28'/>");
		out.write("                <w:sz-cs w:val='28'/>");
		out.write("              </w:rPr>");
		out.write("            </w:pPr>");
		out.write("            <w:r>");
		out.write("              <w:rPr>");
		out.write("                <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體'/>");
		out.write("                <wx:font wx:val='標楷體'/>");
		out.write("                <w:sz w:val='28'/>");
		out.write("                <w:sz-cs w:val='28'/>");
		out.write("              </w:rPr>");
		out.write("              <w:t>General and Specialized Course Introduction</w:t>");
		out.write("            </w:r>");
		out.write("          </w:p>");
		out.write("        </w:hdr>");
		out.write("        <w:pgSz w:w='11906' w:h='16838'/>");
		out.write("        <w:pgMar w:top='720' w:right='720' w:bottom='720' w:left='720' w:header='851' w:footer='992' w:gutter='0'/>");
		out.write("        <w:cols w:space='425'/>");
		out.write("        <w:docGrid w:type='lines' w:line-pitch='360'/>");
		out.write("      </w:sectPr>");
		out.write("    </wx:sect>");
		out.write("  </w:body>");
		out.write("</w:wordDocument>");
		
		out.close();
		return null;
	}
	
}