package tw.edu.chit.struts.action.report.registration.diploma;

import java.io.PrintWriter;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.Map;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import tw.edu.chit.service.CourseManager;
import tw.edu.chit.struts.action.BaseAction;

public class Diploma32 extends BaseAction{

/**
 * 學士學位證書橫(四技)
 *  "+yy+"

	"+aStudent.get("student_no")+"
	
	"+aStudent.get("idno")+"
	
	"+aStudent.get("student_name")+"
	
	"+aStudent.get("birth_year")+"
	
	"+aStudent.get("birth_month")+"
	
	"+aStudent.get("birth_day")+"
	
	"+aStudent.get("years")+"
	
	"+aStudent.get("deptName")+" "+aStudent.get("diviName")+"
	
	"+aStudent.get("title")+"
	
	"+year+"
	
	"+month+"
 */
public ActionForward execute(ActionMapping mapping, ActionForm form, HttpServletRequest request, HttpServletResponse response)throws Exception {	
		
		response.setContentType("text/xml; charset=UTF-8");		
		CourseManager manager = (CourseManager) getBean("courseManager");		
		PrintWriter out=response.getWriter();		
		Date date=new Date();
		response.setHeader("Content-disposition","attachment;filename=Diploma32"+date.getTime()+".doc");		
		
		
		
		out.println ("<?xml version='1.0' encoding='UTF-8' standalone='yes'?>");
		out.println ("<?mso-application progid='Word.Document'?>");
		out.println ("<w:wordDocument xmlns:aml='http://schemas.microsoft.com/aml/2001/core' xmlns:dt='uuid:C2F41010-65B3-11d1-A29F-00AA00C14882' xmlns:ve='http://schemas.openxmlformats.org/markup-compatibility/2006' xmlns:o='urn:schemas-microsoft-com:office:office' xmlns:v='urn:schemas-microsoft-com:vml' xmlns:w10='urn:schemas-microsoft-com:office:word' xmlns:w='http://schemas.microsoft.com/office/word/2003/wordml' xmlns:wx='http://schemas.microsoft.com/office/word/2003/auxHint' xmlns:wsp='http://schemas.microsoft.com/office/word/2003/wordml/sp2' xmlns:sl='http://schemas.microsoft.com/schemaLibrary/2003/core' w:macrosPresent='no' w:embeddedObjPresent='no' w:ocxPresent='no' xml:space='preserve'>");
		out.println ("  <w:ignoreSubtree w:val='http://schemas.microsoft.com/office/word/2003/wordml/sp2'/>");
		out.println ("  <o:DocumentProperties>");
		out.println ("    <o:Title>中華科技大學附設進修學院副學士學位證書</o:Title>");
		out.println ("    <o:Author>蕭國裕</o:Author>");
		out.println ("    <o:LastAuthor>蕭國裕</o:LastAuthor>");
		out.println ("    <o:Revision>2</o:Revision>");
		out.println ("    <o:TotalTime>1</o:TotalTime>");
		out.println ("    <o:LastPrinted>2010-02-03T02:30:00Z</o:LastPrinted>");
		out.println ("    <o:Created>2010-05-22T01:13:00Z</o:Created>");
		out.println ("    <o:LastSaved>2010-05-22T01:13:00Z</o:LastSaved>");
		out.println ("    <o:Pages>1</o:Pages>");
		out.println ("    <o:Words>28</o:Words>");
		out.println ("    <o:Characters>162</o:Characters>");
		out.println ("    <o:Company>中華科技大學</o:Company>");
		out.println ("    <o:Lines>1</o:Lines>");
		out.println ("    <o:Paragraphs>1</o:Paragraphs>");
		out.println ("    <o:CharactersWithSpaces>189</o:CharactersWithSpaces>");
		out.println ("    <o:Version>12</o:Version>");
		out.println ("  </o:DocumentProperties>");
		out.println ("  <w:fonts>");
		out.println ("    <w:defaultFonts w:ascii='Times New Roman' w:fareast='新細明體' w:h-ansi='Times New Roman' w:cs='Times New Roman'/>");
		out.println ("    <w:font w:name='Times New Roman'>");
		out.println ("      <w:panose-1 w:val='02020603050405020304'/>");
		out.println ("      <w:charset w:val='00'/>");
		out.println ("      <w:family w:val='Roman'/>");
		out.println ("      <w:pitch w:val='variable'/>");
		out.println ("      <w:sig w:usb-0='E0002AFF' w:usb-1='C0007841' w:usb-2='00000009' w:usb-3='00000000' w:csb-0='000001FF' w:csb-1='00000000'/>");
		out.println ("    </w:font>");
		out.println ("    <w:font w:name='Arial'>");
		out.println ("      <w:panose-1 w:val='020B0604020202020204'/>");
		out.println ("      <w:charset w:val='00'/>");
		out.println ("      <w:family w:val='Swiss'/>");
		out.println ("      <w:pitch w:val='variable'/>");
		out.println ("      <w:sig w:usb-0='E0002AFF' w:usb-1='C0007843' w:usb-2='00000009' w:usb-3='00000000' w:csb-0='000001FF' w:csb-1='00000000'/>");
		out.println ("    </w:font>");
		out.println ("    <w:font w:name='新細明體'>");
		out.println ("      <w:altName w:val='PMingLiU'/>");
		out.println ("      <w:panose-1 w:val='02020500000000000000'/>");
		out.println ("      <w:charset w:val='88'/>");
		out.println ("      <w:family w:val='Roman'/>");
		out.println ("      <w:pitch w:val='variable'/>");
		out.println ("      <w:sig w:usb-0='A00002FF' w:usb-1='28CFFCFA' w:usb-2='00000016' w:usb-3='00000000' w:csb-0='00100001' w:csb-1='00000000'/>");
		out.println ("    </w:font>");
		out.println ("    <w:font w:name='Cambria Math'>");
		out.println ("      <w:panose-1 w:val='02040503050406030204'/>");
		out.println ("      <w:charset w:val='01'/>");
		out.println ("      <w:family w:val='Roman'/>");
		out.println ("      <w:notTrueType/>");
		out.println ("      <w:pitch w:val='variable'/>");
		out.println ("      <w:sig w:usb-0='00000000' w:usb-1='00000000' w:usb-2='00000000' w:usb-3='00000000' w:csb-0='00000000' w:csb-1='00000000'/>");
		out.println ("    </w:font>");
		out.println ("    <w:font w:name='標楷體'>");
		out.println ("      <w:panose-1 w:val='03000509000000000000'/>");
		out.println ("      <w:charset w:val='88'/>");
		out.println ("      <w:family w:val='Script'/>");
		out.println ("      <w:pitch w:val='fixed'/>");
		out.println ("      <w:sig w:usb-0='00000003' w:usb-1='080E0000' w:usb-2='00000016' w:usb-3='00000000' w:csb-0='00100001' w:csb-1='00000000'/>");
		out.println ("    </w:font>");
		out.println ("    <w:font w:name='@標楷體'>");
		out.println ("      <w:panose-1 w:val='03000509000000000000'/>");
		out.println ("      <w:charset w:val='88'/>");
		out.println ("      <w:family w:val='Script'/>");
		out.println ("      <w:pitch w:val='fixed'/>");
		out.println ("      <w:sig w:usb-0='00000003' w:usb-1='080E0000' w:usb-2='00000016' w:usb-3='00000000' w:csb-0='00100001' w:csb-1='00000000'/>");
		out.println ("    </w:font>");
		out.println ("    <w:font w:name='@新細明體'>");
		out.println ("      <w:panose-1 w:val='02020500000000000000'/>");
		out.println ("      <w:charset w:val='88'/>");
		out.println ("      <w:family w:val='Roman'/>");
		out.println ("      <w:pitch w:val='variable'/>");
		out.println ("      <w:sig w:usb-0='A00002FF' w:usb-1='28CFFCFA' w:usb-2='00000016' w:usb-3='00000000' w:csb-0='00100001' w:csb-1='00000000'/>");
		out.println ("    </w:font>");
		out.println ("  </w:fonts>");
		out.println ("  <w:styles>");
		out.println ("    <w:versionOfBuiltInStylenames w:val='7'/>");
		out.println ("    <w:latentStyles w:defLockedState='off' w:latentStyleCount='267'>");
		out.println ("      <w:lsdException w:name='Normal'/>");
		out.println ("      <w:lsdException w:name='heading 1'/>");
		out.println ("      <w:lsdException w:name='heading 2'/>");
		out.println ("      <w:lsdException w:name='heading 3'/>");
		out.println ("      <w:lsdException w:name='heading 4'/>");
		out.println ("      <w:lsdException w:name='heading 5'/>");
		out.println ("      <w:lsdException w:name='heading 6'/>");
		out.println ("      <w:lsdException w:name='heading 7'/>");
		out.println ("      <w:lsdException w:name='heading 8'/>");
		out.println ("      <w:lsdException w:name='heading 9'/>");
		out.println ("      <w:lsdException w:name='caption'/>");
		out.println ("      <w:lsdException w:name='Title'/>");
		out.println ("      <w:lsdException w:name='Subtitle'/>");
		out.println ("      <w:lsdException w:name='Strong'/>");
		out.println ("      <w:lsdException w:name='Emphasis'/>");
		out.println ("      <w:lsdException w:name='Placeholder Text'/>");
		out.println ("      <w:lsdException w:name='No Spacing'/>");
		out.println ("      <w:lsdException w:name='Light Shading'/>");
		out.println ("      <w:lsdException w:name='Light List'/>");
		out.println ("      <w:lsdException w:name='Light Grid'/>");
		out.println ("      <w:lsdException w:name='Medium Shading 1'/>");
		out.println ("      <w:lsdException w:name='Medium Shading 2'/>");
		out.println ("      <w:lsdException w:name='Medium List 1'/>");
		out.println ("      <w:lsdException w:name='Medium List 2'/>");
		out.println ("      <w:lsdException w:name='Medium Grid 1'/>");
		out.println ("      <w:lsdException w:name='Medium Grid 2'/>");
		out.println ("      <w:lsdException w:name='Medium Grid 3'/>");
		out.println ("      <w:lsdException w:name='Dark List'/>");
		out.println ("      <w:lsdException w:name='Colorful Shading'/>");
		out.println ("      <w:lsdException w:name='Colorful List'/>");
		out.println ("      <w:lsdException w:name='Colorful Grid'/>");
		out.println ("      <w:lsdException w:name='Light Shading Accent 1'/>");
		out.println ("      <w:lsdException w:name='Light List Accent 1'/>");
		out.println ("      <w:lsdException w:name='Light Grid Accent 1'/>");
		out.println ("      <w:lsdException w:name='Medium Shading 1 Accent 1'/>");
		out.println ("      <w:lsdException w:name='Medium Shading 2 Accent 1'/>");
		out.println ("      <w:lsdException w:name='Medium List 1 Accent 1'/>");
		out.println ("      <w:lsdException w:name='Revision'/>");
		out.println ("      <w:lsdException w:name='List Paragraph'/>");
		out.println ("      <w:lsdException w:name='Quote'/>");
		out.println ("      <w:lsdException w:name='Intense Quote'/>");
		out.println ("      <w:lsdException w:name='Medium List 2 Accent 1'/>");
		out.println ("      <w:lsdException w:name='Medium Grid 1 Accent 1'/>");
		out.println ("      <w:lsdException w:name='Medium Grid 2 Accent 1'/>");
		out.println ("      <w:lsdException w:name='Medium Grid 3 Accent 1'/>");
		out.println ("      <w:lsdException w:name='Dark List Accent 1'/>");
		out.println ("      <w:lsdException w:name='Colorful Shading Accent 1'/>");
		out.println ("      <w:lsdException w:name='Colorful List Accent 1'/>");
		out.println ("      <w:lsdException w:name='Colorful Grid Accent 1'/>");
		out.println ("      <w:lsdException w:name='Light Shading Accent 2'/>");
		out.println ("      <w:lsdException w:name='Light List Accent 2'/>");
		out.println ("      <w:lsdException w:name='Light Grid Accent 2'/>");
		out.println ("      <w:lsdException w:name='Medium Shading 1 Accent 2'/>");
		out.println ("      <w:lsdException w:name='Medium Shading 2 Accent 2'/>");
		out.println ("      <w:lsdException w:name='Medium List 1 Accent 2'/>");
		out.println ("      <w:lsdException w:name='Medium List 2 Accent 2'/>");
		out.println ("      <w:lsdException w:name='Medium Grid 1 Accent 2'/>");
		out.println ("      <w:lsdException w:name='Medium Grid 2 Accent 2'/>");
		out.println ("      <w:lsdException w:name='Medium Grid 3 Accent 2'/>");
		out.println ("      <w:lsdException w:name='Dark List Accent 2'/>");
		out.println ("      <w:lsdException w:name='Colorful Shading Accent 2'/>");
		out.println ("      <w:lsdException w:name='Colorful List Accent 2'/>");
		out.println ("      <w:lsdException w:name='Colorful Grid Accent 2'/>");
		out.println ("      <w:lsdException w:name='Light Shading Accent 3'/>");
		out.println ("      <w:lsdException w:name='Light List Accent 3'/>");
		out.println ("      <w:lsdException w:name='Light Grid Accent 3'/>");
		out.println ("      <w:lsdException w:name='Medium Shading 1 Accent 3'/>");
		out.println ("      <w:lsdException w:name='Medium Shading 2 Accent 3'/>");
		out.println ("      <w:lsdException w:name='Medium List 1 Accent 3'/>");
		out.println ("      <w:lsdException w:name='Medium List 2 Accent 3'/>");
		out.println ("      <w:lsdException w:name='Medium Grid 1 Accent 3'/>");
		out.println ("      <w:lsdException w:name='Medium Grid 2 Accent 3'/>");
		out.println ("      <w:lsdException w:name='Medium Grid 3 Accent 3'/>");
		out.println ("      <w:lsdException w:name='Dark List Accent 3'/>");
		out.println ("      <w:lsdException w:name='Colorful Shading Accent 3'/>");
		out.println ("      <w:lsdException w:name='Colorful List Accent 3'/>");
		out.println ("      <w:lsdException w:name='Colorful Grid Accent 3'/>");
		out.println ("      <w:lsdException w:name='Light Shading Accent 4'/>");
		out.println ("      <w:lsdException w:name='Light List Accent 4'/>");
		out.println ("      <w:lsdException w:name='Light Grid Accent 4'/>");
		out.println ("      <w:lsdException w:name='Medium Shading 1 Accent 4'/>");
		out.println ("      <w:lsdException w:name='Medium Shading 2 Accent 4'/>");
		out.println ("      <w:lsdException w:name='Medium List 1 Accent 4'/>");
		out.println ("      <w:lsdException w:name='Medium List 2 Accent 4'/>");
		out.println ("      <w:lsdException w:name='Medium Grid 1 Accent 4'/>");
		out.println ("      <w:lsdException w:name='Medium Grid 2 Accent 4'/>");
		out.println ("      <w:lsdException w:name='Medium Grid 3 Accent 4'/>");
		out.println ("      <w:lsdException w:name='Dark List Accent 4'/>");
		out.println ("      <w:lsdException w:name='Colorful Shading Accent 4'/>");
		out.println ("      <w:lsdException w:name='Colorful List Accent 4'/>");
		out.println ("      <w:lsdException w:name='Colorful Grid Accent 4'/>");
		out.println ("      <w:lsdException w:name='Light Shading Accent 5'/>");
		out.println ("      <w:lsdException w:name='Light List Accent 5'/>");
		out.println ("      <w:lsdException w:name='Light Grid Accent 5'/>");
		out.println ("      <w:lsdException w:name='Medium Shading 1 Accent 5'/>");
		out.println ("      <w:lsdException w:name='Medium Shading 2 Accent 5'/>");
		out.println ("      <w:lsdException w:name='Medium List 1 Accent 5'/>");
		out.println ("      <w:lsdException w:name='Medium List 2 Accent 5'/>");
		out.println ("      <w:lsdException w:name='Medium Grid 1 Accent 5'/>");
		out.println ("      <w:lsdException w:name='Medium Grid 2 Accent 5'/>");
		out.println ("      <w:lsdException w:name='Medium Grid 3 Accent 5'/>");
		out.println ("      <w:lsdException w:name='Dark List Accent 5'/>");
		out.println ("      <w:lsdException w:name='Colorful Shading Accent 5'/>");
		out.println ("      <w:lsdException w:name='Colorful List Accent 5'/>");
		out.println ("      <w:lsdException w:name='Colorful Grid Accent 5'/>");
		out.println ("      <w:lsdException w:name='Light Shading Accent 6'/>");
		out.println ("      <w:lsdException w:name='Light List Accent 6'/>");
		out.println ("      <w:lsdException w:name='Light Grid Accent 6'/>");
		out.println ("      <w:lsdException w:name='Medium Shading 1 Accent 6'/>");
		out.println ("      <w:lsdException w:name='Medium Shading 2 Accent 6'/>");
		out.println ("      <w:lsdException w:name='Medium List 1 Accent 6'/>");
		out.println ("      <w:lsdException w:name='Medium List 2 Accent 6'/>");
		out.println ("      <w:lsdException w:name='Medium Grid 1 Accent 6'/>");
		out.println ("      <w:lsdException w:name='Medium Grid 2 Accent 6'/>");
		out.println ("      <w:lsdException w:name='Medium Grid 3 Accent 6'/>");
		out.println ("      <w:lsdException w:name='Dark List Accent 6'/>");
		out.println ("      <w:lsdException w:name='Colorful Shading Accent 6'/>");
		out.println ("      <w:lsdException w:name='Colorful List Accent 6'/>");
		out.println ("      <w:lsdException w:name='Colorful Grid Accent 6'/>");
		out.println ("      <w:lsdException w:name='Subtle Emphasis'/>");
		out.println ("      <w:lsdException w:name='Intense Emphasis'/>");
		out.println ("      <w:lsdException w:name='Subtle Reference'/>");
		out.println ("      <w:lsdException w:name='Intense Reference'/>");
		out.println ("      <w:lsdException w:name='Book Title'/>");
		out.println ("      <w:lsdException w:name='Bibliography'/>");
		out.println ("      <w:lsdException w:name='TOC Heading'/>");
		out.println ("    </w:latentStyles>");
		out.println ("    <w:style w:type='paragraph' w:default='on' w:styleId='a'>");
		out.println ("      <w:name w:val='Normal'/>");
		out.println ("      <wx:uiName wx:val='內文'/>");
		out.println ("      <w:pPr>");
		out.println ("        <w:widowControl w:val='off'/>");
		out.println ("      </w:pPr>");
		out.println ("      <w:rPr>");
		out.println ("        <wx:font wx:val='Times New Roman'/>");
		out.println ("        <w:kern w:val='2'/>");
		out.println ("        <w:sz w:val='24'/>");
		out.println ("        <w:sz-cs w:val='24'/>");
		out.println ("        <w:lang w:val='EN-US' w:fareast='ZH-TW' w:bidi='AR-SA'/>");
		out.println ("      </w:rPr>");
		out.println ("    </w:style>");
		out.println ("    <w:style w:type='character' w:default='on' w:styleId='a0'>");
		out.println ("      <w:name w:val='Default Paragraph Font'/>");
		out.println ("      <wx:uiName wx:val='預設段落字型'/>");
		out.println ("    </w:style>");
		out.println ("    <w:style w:type='table' w:default='on' w:styleId='a1'>");
		out.println ("      <w:name w:val='Normal Table'/>");
		out.println ("      <wx:uiName wx:val='表格內文'/>");
		out.println ("      <w:rPr>");
		out.println ("        <wx:font wx:val='Times New Roman'/>");
		out.println ("        <w:lang w:val='EN-US' w:fareast='ZH-TW' w:bidi='AR-SA'/>");
		out.println ("      </w:rPr>");
		out.println ("      <w:tblPr>");
		out.println ("        <w:tblInd w:w='0' w:type='dxa'/>");
		out.println ("        <w:tblCellMar>");
		out.println ("          <w:top w:w='0' w:type='dxa'/>");
		out.println ("          <w:left w:w='108' w:type='dxa'/>");
		out.println ("          <w:bottom w:w='0' w:type='dxa'/>");
		out.println ("          <w:right w:w='108' w:type='dxa'/>");
		out.println ("        </w:tblCellMar>");
		out.println ("      </w:tblPr>");
		out.println ("    </w:style>");
		out.println ("    <w:style w:type='list' w:default='on' w:styleId='a2'>");
		out.println ("      <w:name w:val='No List'/>");
		out.println ("      <wx:uiName wx:val='無清單'/>");
		out.println ("    </w:style>");
		out.println ("    <w:style w:type='paragraph' w:styleId='a3'>");
		out.println ("      <w:name w:val='Body Text'/>");
		out.println ("      <wx:uiName wx:val='本文'/>");
		out.println ("      <w:basedOn w:val='a'/>");
		out.println ("      <w:rPr>");
		out.println ("        <w:rFonts w:fareast='標楷體'/>");
		out.println ("        <wx:font wx:val='Times New Roman'/>");
		out.println ("        <w:spacing w:val='60'/>");
		out.println ("        <w:sz w:val='48'/>");
		out.println ("      </w:rPr>");
		out.println ("    </w:style>");
		out.println ("    <w:style w:type='paragraph' w:styleId='a4'>");
		out.println ("      <w:name w:val='Balloon Text'/>");
		out.println ("      <wx:uiName wx:val='註解方塊文字'/>");
		out.println ("      <w:basedOn w:val='a'/>");
		out.println ("      <w:rsid w:val='004517CE'/>");
		out.println ("      <w:rPr>");
		out.println ("        <w:rFonts w:ascii='Arial' w:h-ansi='Arial'/>");
		out.println ("        <wx:font wx:val='Arial'/>");
		out.println ("        <w:sz w:val='18'/>");
		out.println ("        <w:sz-cs w:val='18'/>");
		out.println ("      </w:rPr>");
		out.println ("    </w:style>");
		out.println ("  </w:styles>");
		out.println ("  <w:shapeDefaults>");
		out.println ("    <o:shapedefaults v:ext='edit' spidmax='2050'/>");
		out.println ("    <o:shapelayout v:ext='edit'>");
		out.println ("      <o:idmap v:ext='edit' data='1'/>");
		out.println ("    </o:shapelayout>");
		out.println ("  </w:shapeDefaults>");
		out.println ("  <w:docPr>");
		out.println ("    <w:view w:val='print'/>");
		out.println ("    <w:zoom w:percent='100'/>");
		out.println ("    <w:bordersDontSurroundHeader/>");
		out.println ("    <w:bordersDontSurroundFooter/>");
		out.println ("    <w:proofState w:spelling='clean' w:grammar='clean'/>");
		out.println ("    <w:stylePaneFormatFilter w:val='3F01'/>");
		out.println ("    <w:defaultTabStop w:val='480'/>");
		out.println ("    <w:displayHorizontalDrawingGridEvery w:val='0'/>");
		out.println ("    <w:displayVerticalDrawingGridEvery w:val='2'/>");
		out.println ("    <w:punctuationKerning/>");
		out.println ("    <w:characterSpacingControl w:val='CompressPunctuation'/>");
		out.println ("    <w:optimizeForBrowser/>");
		out.println ("    <w:validateAgainstSchema/>");
		out.println ("    <w:saveInvalidXML w:val='off'/>");
		out.println ("    <w:ignoreMixedContent w:val='off'/>");
		out.println ("    <w:alwaysShowPlaceholderText w:val='off'/>");
		out.println ("    <w:compat>");
		out.println ("      <w:spaceForUL/>");
		out.println ("      <w:balanceSingleByteDoubleByteWidth/>");
		out.println ("      <w:doNotLeaveBackslashAlone/>");
		out.println ("      <w:ulTrailSpace/>");
		out.println ("      <w:doNotExpandShiftReturn/>");
		out.println ("      <w:adjustLineHeightInTable/>");
		out.println ("      <w:dontAllowFieldEndSelect/>");
		out.println ("      <w:useWord2002TableStyleRules/>");
		out.println ("      <w:useFELayout/>");
		out.println ("    </w:compat>");
		out.println ("    <wsp:rsids>");
		out.println ("      <wsp:rsidRoot wsp:val='004F2ECA'/>");
		out.println ("      <wsp:rsid wsp:val='00027719'/>");
		out.println ("      <wsp:rsid wsp:val='0003107F'/>");
		out.println ("      <wsp:rsid wsp:val='00084A1D'/>");
		out.println ("      <wsp:rsid wsp:val='000F08CD'/>");
		out.println ("      <wsp:rsid wsp:val='0023194A'/>");
		out.println ("      <wsp:rsid wsp:val='00251E9F'/>");
		out.println ("      <wsp:rsid wsp:val='002B1324'/>");
		out.println ("      <wsp:rsid wsp:val='003114B0'/>");
		out.println ("      <wsp:rsid wsp:val='003940B9'/>");
		out.println ("      <wsp:rsid wsp:val='00394E9E'/>");
		out.println ("      <wsp:rsid wsp:val='00432D18'/>");
		out.println ("      <wsp:rsid wsp:val='004517CE'/>");
		out.println ("      <wsp:rsid wsp:val='004E2DB5'/>");
		out.println ("      <wsp:rsid wsp:val='004F2ECA'/>");
		out.println ("      <wsp:rsid wsp:val='00532E59'/>");
		out.println ("      <wsp:rsid wsp:val='005B4663'/>");
		out.println ("      <wsp:rsid wsp:val='005F48C6'/>");
		out.println ("      <wsp:rsid wsp:val='0062616F'/>");
		out.println ("      <wsp:rsid wsp:val='00672D5B'/>");
		out.println ("      <wsp:rsid wsp:val='00790DDC'/>");
		out.println ("      <wsp:rsid wsp:val='009852C6'/>");
		out.println ("      <wsp:rsid wsp:val='00AC0F84'/>");
		out.println ("      <wsp:rsid wsp:val='00B26B42'/>");
		out.println ("      <wsp:rsid wsp:val='00BA3C1B'/>");
		out.println ("      <wsp:rsid wsp:val='00C446DE'/>");
		out.println ("      <wsp:rsid wsp:val='00C978B8'/>");
		out.println ("      <wsp:rsid wsp:val='00CA4A0C'/>");
		out.println ("      <wsp:rsid wsp:val='00D45C87'/>");
		out.println ("      <wsp:rsid wsp:val='00D52E07'/>");
		out.println ("      <wsp:rsid wsp:val='00D67F2B'/>");
		out.println ("      <wsp:rsid wsp:val='00D771DB'/>");
		out.println ("      <wsp:rsid wsp:val='00DA33B3'/>");
		out.println ("      <wsp:rsid wsp:val='00DE3E00'/>");
		out.println ("      <wsp:rsid wsp:val='00E02237'/>");
		out.println ("      <wsp:rsid wsp:val='00E02C1F'/>");
		out.println ("      <wsp:rsid wsp:val='00F737A9'/>");
		out.println ("      <wsp:rsid wsp:val='00FB4CA0'/>");
		out.println ("      <wsp:rsid wsp:val='00FC7105'/>");
		out.println ("    </wsp:rsids>");
		out.println ("  </w:docPr>");
		out.println ("  <w:body>");
		
		StringBuilder deptName;
		
		HttpSession session = request.getSession(false);		
		List students=(List)session.getAttribute("students");
		String sy;
		Map aStudent;
		
		for(int i=0; i<students.size(); i++){
			try{
			aStudent=manager.getADiplomaInfo(((Map)students.get(i)).get("student_no").toString());
			
			try{
				sy=aStudent.get("occur_year").toString();
			}catch(Exception e){
				sy=manager.getSchoolYear().toString();
			}
			
			out.println ("    <w:p wsp:rsidR='00C446DE' wsp:rsidRDefault='00C446DE'>");
			out.println ("      <w:pPr>");
			out.println ("        <w:ind w:left-chars='20' w:left='48'/>");
			out.println ("        <w:jc w:val='center'/>");
			out.println ("        <w:rPr>");
			out.println ("          <w:rFonts w:fareast='標楷體' w:hint='fareast'/>");
			out.println ("          <w:spacing w:val='34'/>");
			out.println ("          <w:sz w:val='48'/>");
			out.println ("        </w:rPr>");
			out.println ("      </w:pPr>");
			out.println ("    </w:p>");
			out.println ("    <w:p wsp:rsidR='00C446DE' wsp:rsidRDefault='00C446DE'>");
			out.println ("      <w:pPr>");
			out.println ("        <w:ind w:left-chars='20' w:left='48'/>");
			out.println ("        <w:jc w:val='center'/>");
			out.println ("        <w:rPr>");
			out.println ("          <w:rFonts w:fareast='標楷體' w:hint='fareast'/>");
			out.println ("          <w:spacing w:val='34'/>");
			out.println ("          <w:sz w:val='48'/>");
			out.println ("        </w:rPr>");
			out.println ("      </w:pPr>");
			out.println ("    </w:p>");
			out.println ("    <w:p wsp:rsidR='00C446DE' wsp:rsidRDefault='00C446DE'>");
			out.println ("      <w:pPr>");
			out.println ("        <w:ind w:left-chars='20' w:left='48'/>");
			out.println ("        <w:jc w:val='center'/>");
			out.println ("        <w:rPr>");
			out.println ("          <w:rFonts w:fareast='標楷體' w:hint='fareast'/>");
			out.println ("          <w:spacing w:val='34'/>");
			out.println ("          <w:sz w:val='48'/>");
			out.println ("        </w:rPr>");
			out.println ("      </w:pPr>");
			out.println ("    </w:p>");
			out.println ("    <w:tbl>");
			out.println ("      <w:tblPr>");
			out.println ("        <w:tblW w:w='5034' w:type='pct'/>");
			out.println ("        <w:tblCellSpacing w:w='15' w:type='dxa'/>");
			out.println ("      </w:tblPr>");
			out.println ("      <w:tblGrid>");
			out.println ("        <w:gridCol w:w='4725'/>");
			out.println ("        <w:gridCol w:w='3774'/>");
			out.println ("      </w:tblGrid>");
			out.println ("      <w:tr wsp:rsidR='00C446DE' wsp:rsidTr='00532E59'>");
			out.println ("        <w:trPr>");
			out.println ("          <w:trHeight w:h-rule='exact' w:val='907'/>");
			out.println ("          <w:tblCellSpacing w:w='15' w:type='dxa'/>");
			out.println ("        </w:trPr>");
			out.println ("        <w:tc>");
			out.println ("          <w:tcPr>");
			out.println ("            <w:tcW w:w='0' w:type='auto'/>");
			out.println ("            <w:gridSpan w:val='2'/>");
			out.println ("            <w:noWrap/>");
			out.println ("            <w:tcMar>");
			out.println ("              <w:top w:w='15' w:type='dxa'/>");
			out.println ("              <w:left w:w='15' w:type='dxa'/>");
			out.println ("              <w:bottom w:w='15' w:type='dxa'/>");
			out.println ("              <w:right w:w='15' w:type='dxa'/>");
			out.println ("            </w:tcMar>");
			out.println ("            <w:vAlign w:val='center'/>");
			out.println ("          </w:tcPr>");
			out.println ("          <w:p wsp:rsidR='00C446DE' wsp:rsidRDefault='00C446DE' wsp:rsidP='00C978B8'>");
			out.println ("            <w:pPr>");
			out.println ("              <w:jc w:val='center'/>");
			out.println ("              <w:rPr>");
			out.println ("                <w:rFonts w:ascii='新細明體' w:h-ansi='新細明體' w:cs='新細明體'/>");
			out.println ("                <wx:font wx:val='新細明體'/>");
			out.println ("              </w:rPr>");
			out.println ("            </w:pPr>");
			out.println ("            <w:r>");
			out.println ("              <w:rPr>");
			out.println ("                <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:hint='fareast'/>");
			out.println ("                <wx:font wx:val='標楷體'/>");
			out.println ("                <w:b/>");
			out.println ("                <w:b-cs/>");
			out.println ("                <w:sz w:val='60'/>");
			out.println ("                <w:sz-cs w:val='60'/>");
			out.println ("              </w:rPr>");
			out.println ("              <w:t>中華科技大學附設專科進修學校</w:t>");
			out.println ("            </w:r>");
			out.println ("            <w:r>");
			out.println ("              <w:rPr>");
			out.println ("                <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:hint='fareast'/>");
			out.println ("                <wx:font wx:val='標楷體'/>");
			out.println ("                <w:sz w:val='60'/>");
			out.println ("                <w:sz-cs w:val='60'/>");
			out.println ("              </w:rPr>");
			out.println ("              <w:t></w:t>");
			out.println ("            </w:r>");
			out.println ("          </w:p>");
			out.println ("        </w:tc>");
			out.println ("      </w:tr>");
			out.println ("      <w:tr wsp:rsidR='00C446DE' wsp:rsidTr='00532E59'>");
			out.println ("        <w:trPr>");
			out.println ("          <w:trHeight w:h-rule='exact' w:val='907'/>");
			out.println ("          <w:tblCellSpacing w:w='15' w:type='dxa'/>");
			out.println ("        </w:trPr>");
			out.println ("        <w:tc>");
			out.println ("          <w:tcPr>");
			out.println ("            <w:tcW w:w='2753' w:type='pct'/>");
			out.println ("            <w:tcMar>");
			out.println ("              <w:top w:w='15' w:type='dxa'/>");
			out.println ("              <w:left w:w='15' w:type='dxa'/>");
			out.println ("              <w:bottom w:w='15' w:type='dxa'/>");
			out.println ("              <w:right w:w='15' w:type='dxa'/>");
			out.println ("            </w:tcMar>");
			out.println ("            <w:vAlign w:val='center'/>");
			out.println ("          </w:tcPr>");
			out.println ("          <w:p wsp:rsidR='00C446DE' wsp:rsidRDefault='00C446DE' wsp:rsidP='00C978B8'>");
			out.println ("            <w:pPr>");
			out.println ("              <w:jc w:val='right'/>");
			out.println ("              <w:rPr>");
			out.println ("                <w:rFonts w:ascii='新細明體' w:h-ansi='新細明體' w:cs='新細明體'/>");
			out.println ("                <wx:font wx:val='新細明體'/>");
			out.println ("              </w:rPr>");
			out.println ("            </w:pPr>");
			out.println ("            <w:r>");
			out.println ("              <w:rPr>");
			out.println ("                <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:hint='fareast'/>");
			out.println ("                <wx:font wx:val='標楷體'/>");
			out.println ("                <w:sz w:val='60'/>");
			out.println ("                <w:sz-cs w:val='60'/>");
			out.println ("              </w:rPr>");
			out.println ("              <w:t> </w:t>");
			out.println ("            </w:r>");
			out.println ("            <w:r>");
			out.println ("              <w:rPr>");
			out.println ("                <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:hint='fareast'/>");
			out.println ("                <wx:font wx:val='標楷體'/>");
			out.println ("                <w:b/>");
			out.println ("                <w:b-cs/>");
			out.println ("                <w:sz w:val='60'/>");
			out.println ("                <w:sz-cs w:val='60'/>");
			out.println ("              </w:rPr>");
			out.println ("              <w:t>副學士學位證書</w:t>");
			out.println ("            </w:r>");
			out.println ("          </w:p>");
			out.println ("        </w:tc>");
			out.println ("        <w:tc>");
			out.println ("          <w:tcPr>");
			out.println ("            <w:tcW w:w='2194' w:type='pct'/>");
			out.println ("            <w:tcMar>");
			out.println ("              <w:top w:w='15' w:type='dxa'/>");
			out.println ("              <w:left w:w='15' w:type='dxa'/>");
			out.println ("              <w:bottom w:w='15' w:type='dxa'/>");
			out.println ("              <w:right w:w='15' w:type='dxa'/>");
			out.println ("            </w:tcMar>");
			out.println ("            <w:vAlign w:val='center'/>");
			out.println ("          </w:tcPr>");
			out.println ("          <w:p wsp:rsidR='00C446DE' wsp:rsidRDefault='00C446DE' wsp:rsidP='00C978B8'>");
			out.println ("            <w:pPr>");
			out.println ("              <w:rPr>");
			out.println ("                <w:rFonts w:ascii='新細明體' w:h-ansi='新細明體' w:cs='新細明體'/>");
			out.println ("                <wx:font wx:val='新細明體'/>");
			out.println ("              </w:rPr>");
			out.println ("            </w:pPr>");
			out.println ("            <w:r>");
			out.println ("              <w:rPr>");
			out.println ("                <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:hint='fareast'/>");
			out.println ("                <wx:font wx:val='標楷體'/>");
			out.println ("                <w:sz w:val='22'/>");
			out.println ("                <w:sz-cs w:val='22'/>");
			out.println ("              </w:rPr>");
			out.println ("              <w:t>(</w:t>");
			out.println ("            </w:r>");
			out.println ("            <w:proofErr w:type='spellStart'/>");
			out.println ("            <w:r wsp:rsidR='003940B9'>");
			out.println ("              <w:rPr>");
			out.println ("                <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:hint='fareast'/>");
			out.println ("                <wx:font wx:val='標楷體'/>");
			out.println ("                <w:sz w:val='22'/>");
			out.println ("                <w:sz-cs w:val='22'/>");
			out.println ("              </w:rPr>");
			out.println ("              <w:t>"+sy+"</w:t>");
			out.println ("            </w:r>");
			out.println ("            <w:proofErr w:type='spellEnd'/>");
			out.println ("            <w:r>");
			out.println ("              <w:rPr>");
			out.println ("                <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:hint='fareast'/>");
			out.println ("                <wx:font wx:val='標楷體'/>");
			out.println ("                <w:sz w:val='22'/>");
			out.println ("                <w:sz-cs w:val='22'/>");
			out.println ("              </w:rPr>");
			out.println ("              <w:t>)華科</w:t>");
			out.println ("            </w:r>");
			out.println ("            <w:proofErr w:type='gramStart'/>");
			out.println ("            <w:r>");
			out.println ("              <w:rPr>");
			out.println ("                <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:hint='fareast'/>");
			out.println ("                <wx:font wx:val='標楷體'/>");
			out.println ("                <w:sz w:val='22'/>");
			out.println ("                <w:sz-cs w:val='22'/>");
			out.println ("              </w:rPr>");
			out.println ("              <w:t>大進專字</w:t>");
			out.println ("            </w:r>");
			out.println ("            <w:proofErr w:type='gramEnd'/>");
			out.println ("            <w:r>");
			out.println ("              <w:rPr>");
			out.println ("                <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:hint='fareast'/>");
			out.println ("                <wx:font wx:val='標楷體'/>");
			out.println ("                <w:sz w:val='22'/>");
			out.println ("                <w:sz-cs w:val='22'/>");
			out.println ("              </w:rPr>");
			out.println ("              <w:t>第</w:t>");
			out.println ("            </w:r>");
			out.println ("            <w:r wsp:rsidR='003940B9'>");
			out.println ("              <w:rPr>");
			out.println ("                <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:hint='fareast'/>");
			out.println ("                <wx:font wx:val='標楷體'/>");
			out.println ("                <w:noProof/>");
			out.println ("                <w:sz w:val='22'/>");
			out.println ("                <w:sz-cs w:val='22'/>");
			out.println ("              </w:rPr>");
			out.println ("              <w:t>"+aStudent.get("student_no")+"</w:t>");
			out.println ("            </w:r>");
			out.println ("            <w:r>");
			out.println ("              <w:rPr>");
			out.println ("                <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:hint='fareast'/>");
			out.println ("                <wx:font wx:val='標楷體'/>");
			out.println ("                <w:sz w:val='22'/>");
			out.println ("                <w:sz-cs w:val='22'/>");
			out.println ("              </w:rPr>");
			out.println ("              <w:t>號</w:t>");
			out.println ("            </w:r>");
			out.println ("            <w:r>");
			out.println ("              <w:rPr>");
			out.println ("                <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:hint='fareast'/>");
			out.println ("                <wx:font wx:val='標楷體'/>");
			out.println ("                <w:sz w:val='22'/>");
			out.println ("                <w:sz-cs w:val='22'/>");
			out.println ("              </w:rPr>");
			out.println ("              <w:br/>");
			out.println ("              <w:t>       身分證字號</w:t>");
			out.println ("            </w:r>");
			out.println ("            <w:r wsp:rsidR='003940B9'>");
			out.println ("              <w:rPr>");
			out.println ("                <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:hint='fareast'/>");
			out.println ("                <wx:font wx:val='標楷體'/>");
			out.println ("                <w:noProof/>");
			out.println ("                <w:sz w:val='22'/>");
			out.println ("                <w:sz-cs w:val='22'/>");
			out.println ("              </w:rPr>");
			out.println ("              <w:t>"+aStudent.get("idno")+"</w:t>");
			out.println ("            </w:r>");
			out.println ("          </w:p>");
			out.println ("        </w:tc>");
			out.println ("      </w:tr>");
			out.println ("    </w:tbl>");
			out.println ("    <w:p wsp:rsidR='00C446DE' wsp:rsidRPr='00084A1D' wsp:rsidRDefault='00C446DE' wsp:rsidP='00394E9E'>");
			out.println ("      <w:pPr>");
			out.println ("        <w:spacing w:line='640' w:line-rule='exact'/>");
			out.println ("        <w:ind w:left-chars='20' w:left='48'/>");
			out.println ("        <w:rPr>");
			out.println ("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:hint='fareast'/>");
			out.println ("          <wx:font wx:val='標楷體'/>");
			out.println ("          <w:b/>");
			out.println ("          <w:b-cs/>");
			out.println ("          <w:spacing w:val='54'/>");
			out.println ("          <w:sz w:val='44'/>");
			out.println ("          <w:sz-cs w:val='44'/>");
			out.println ("        </w:rPr>");
			out.println ("      </w:pPr>");
			out.println ("      <w:r wsp:rsidRPr='00084A1D'>");
			out.println ("        <w:rPr>");
			out.println ("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:hint='fareast'/>");
			out.println ("          <wx:font wx:val='標楷體'/>");
			out.println ("          <w:b/>");
			out.println ("          <w:b-cs/>");
			out.println ("          <w:spacing w:val='54'/>");
			out.println ("          <w:sz w:val='44'/>");
			out.println ("          <w:sz-cs w:val='44'/>");
			out.println ("        </w:rPr>");
			out.println ("        <w:t>學生</w:t>");
			out.println ("      </w:r>");
			out.println ("      <w:r wsp:rsidRPr='00394E9E'>");
			out.println ("        <w:rPr>");
			out.println ("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:hint='fareast'/>");
			out.println ("          <wx:font wx:val='標楷體'/>");
			out.println ("          <w:b/>");
			out.println ("          <w:b-cs/>");
			out.println ("          <w:spacing w:val='54'/>");
			out.println ("          <w:sz w:val='28'/>");
			out.println ("          <w:sz-cs w:val='28'/>");
			out.println ("        </w:rPr>");
			out.println ("        <w:t></w:t>");
			out.println ("      </w:r>");
			out.println ("      <w:r wsp:rsidR='00CA4A0C'>");
			out.println ("        <w:rPr>");
			out.println ("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:hint='fareast'/>");
			out.println ("          <wx:font wx:val='標楷體'/>");
			out.println ("          <w:b/>");
			out.println ("          <w:b-cs/>");
			out.println ("          <w:noProof/>");
			out.println ("          <w:spacing w:val='54'/>");
			out.println ("          <w:sz w:val='44'/>");
			out.println ("          <w:sz-cs w:val='44'/>");
			out.println ("        </w:rPr>");
			out.println ("        <w:t>"+aStudent.get("student_name")+"</w:t>");
			out.println ("      </w:r>");
			out.println ("      <w:r wsp:rsidRPr='00394E9E'>");
			out.println ("        <w:rPr>");
			out.println ("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:hint='fareast'/>");
			out.println ("          <wx:font wx:val='標楷體'/>");
			out.println ("          <w:b/>");
			out.println ("          <w:b-cs/>");
			out.println ("          <w:spacing w:val='54'/>");
			out.println ("          <w:sz w:val='28'/>");
			out.println ("          <w:sz-cs w:val='28'/>");
			out.println ("        </w:rPr>");
			out.println ("        <w:t></w:t>");
			out.println ("      </w:r>");
			out.println ("      <w:r wsp:rsidRPr='0003107F'>");
			out.println ("        <w:rPr>");
			out.println ("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:hint='fareast'/>");
			out.println ("          <wx:font wx:val='標楷體'/>");
			out.println ("          <w:b/>");
			out.println ("          <w:b-cs/>");
			out.println ("          <w:kern w:val='0'/>");
			out.println ("          <w:sz w:val='44'/>");
			out.println ("          <w:sz-cs w:val='44'/>");
			out.println ("        </w:rPr>");
			out.println ("        <w:t>中華民國</w:t>");
			out.println ("      </w:r>");
			out.println ("      <w:r wsp:rsidR='00CA4A0C'>");
			out.println ("        <w:rPr>");
			out.println ("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:hint='fareast'/>");
			out.println ("          <wx:font wx:val='標楷體'/>");
			out.println ("          <w:b/>");
			out.println ("          <w:b-cs/>");
			out.println ("          <w:noProof/>");
			out.println ("          <w:kern w:val='0'/>");
			out.println ("          <w:sz w:val='44'/>");
			out.println ("          <w:sz-cs w:val='44'/>");
			out.println ("        </w:rPr>");
			out.println ("        <w:t>"+aStudent.get("birth_year")+"</w:t>");
			out.println ("      </w:r>");
			out.println ("      <w:r wsp:rsidRPr='00CD5376'>");
			out.println ("        <w:rPr>");
			out.println ("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:hint='fareast'/>");
			out.println ("          <wx:font wx:val='標楷體'/>");
			out.println ("          <w:b/>");
			out.println ("          <w:b-cs/>");
			out.println ("          <w:noProof/>");
			out.println ("          <w:kern w:val='0'/>");
			out.println ("          <w:sz w:val='44'/>");
			out.println ("          <w:sz-cs w:val='44'/>");
			out.println ("        </w:rPr>");
			out.println ("        <w:t>年</w:t>");
			out.println ("      </w:r>");
			out.println ("      <w:r wsp:rsidR='00CA4A0C'>");
			out.println ("        <w:rPr>");
			out.println ("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:hint='fareast'/>");
			out.println ("          <wx:font wx:val='標楷體'/>");
			out.println ("          <w:b/>");
			out.println ("          <w:b-cs/>");
			out.println ("          <w:noProof/>");
			out.println ("          <w:kern w:val='0'/>");
			out.println ("          <w:sz w:val='44'/>");
			out.println ("          <w:sz-cs w:val='44'/>");
			out.println ("        </w:rPr>");
			out.println ("        <w:t>"+aStudent.get("birth_month")+"</w:t>");
			out.println ("      </w:r>");
			out.println ("      <w:r wsp:rsidRPr='00CD5376'>");
			out.println ("        <w:rPr>");
			out.println ("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:hint='fareast'/>");
			out.println ("          <wx:font wx:val='標楷體'/>");
			out.println ("          <w:b/>");
			out.println ("          <w:b-cs/>");
			out.println ("          <w:noProof/>");
			out.println ("          <w:kern w:val='0'/>");
			out.println ("          <w:sz w:val='44'/>");
			out.println ("          <w:sz-cs w:val='44'/>");
			out.println ("        </w:rPr>");
			out.println ("        <w:t>月</w:t>");
			out.println ("      </w:r>");
			out.println ("      <w:r wsp:rsidR='00CA4A0C'>");
			out.println ("        <w:rPr>");
			out.println ("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:hint='fareast'/>");
			out.println ("          <wx:font wx:val='標楷體'/>");
			out.println ("          <w:b/>");
			out.println ("          <w:b-cs/>");
			out.println ("          <w:noProof/>");
			out.println ("          <w:kern w:val='0'/>");
			out.println ("          <w:sz w:val='44'/>");
			out.println ("          <w:sz-cs w:val='44'/>");
			out.println ("        </w:rPr>");
			out.println ("        <w:t>"+aStudent.get("birth_day")+"</w:t>");
			out.println ("      </w:r>");
			out.println ("      <w:r wsp:rsidRPr='00CD5376'>");
			out.println ("        <w:rPr>");
			out.println ("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:hint='fareast'/>");
			out.println ("          <wx:font wx:val='標楷體'/>");
			out.println ("          <w:b/>");
			out.println ("          <w:b-cs/>");
			out.println ("          <w:noProof/>");
			out.println ("          <w:kern w:val='0'/>");
			out.println ("          <w:sz w:val='44'/>");
			out.println ("          <w:sz-cs w:val='44'/>");
			out.println ("        </w:rPr>");
			out.println ("        <w:t>日</w:t>");
			out.println ("      </w:r>");
			out.println ("      <w:r>");
			out.println ("        <w:rPr>");
			out.println ("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:hint='fareast'/>");
			out.println ("          <wx:font wx:val='標楷體'/>");
			out.println ("          <w:b/>");
			out.println ("          <w:b-cs/>");
			out.println ("          <w:kern w:val='0'/>");
			out.println ("          <w:sz w:val='44'/>");
			out.println ("          <w:sz-cs w:val='44'/>");
			out.println ("        </w:rPr>");
			out.println ("        <w:t>生</w:t>");
			out.println ("      </w:r>");
			out.println ("      <w:r wsp:rsidRPr='00084A1D'>");
			out.println ("        <w:rPr>");
			out.println ("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:hint='fareast'/>");
			out.println ("          <wx:font wx:val='標楷體'/>");
			out.println ("          <w:b/>");
			out.println ("          <w:b-cs/>");
			out.println ("          <w:spacing w:val='54'/>");
			out.println ("          <w:sz w:val='44'/>");
			out.println ("          <w:sz-cs w:val='44'/>");
			out.println ("        </w:rPr>");
			out.println ("        <w:t>在本校二年制</w:t>");
			out.println ("      </w:r>");
			out.println ("    </w:p>");
			out.println ("    <w:p wsp:rsidR='00C446DE' wsp:rsidRPr='00084A1D' wsp:rsidRDefault='00CA4A0C' wsp:rsidP='00DA33B3'>");
			out.println ("      <w:pPr>");
			out.println ("        <w:spacing w:line='640' w:line-rule='exact'/>");
			out.println ("        <w:ind w:left-chars='20' w:left='48'/>");
			out.println ("        <w:rPr>");
			out.println ("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:hint='fareast'/>");
			out.println ("          <wx:font wx:val='標楷體'/>");
			out.println ("          <w:b/>");
			out.println ("          <w:b-cs/>");
			out.println ("          <w:spacing w:val='54'/>");
			out.println ("          <w:sz w:val='44'/>");
			out.println ("          <w:sz-cs w:val='44'/>");
			out.println ("        </w:rPr>");
			out.println ("      </w:pPr>");
			out.println ("      <w:r>");
			out.println ("        <w:rPr>");
			out.println ("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:hint='fareast'/>");
			out.println ("          <wx:font wx:val='標楷體'/>");
			out.println ("          <w:b/>");
			out.println ("          <w:b-cs/>");
			out.println ("          <w:noProof/>");
			out.println ("          <w:spacing w:val='54'/>");
			out.println ("          <w:sz w:val='44'/>");
			out.println ("          <w:sz-cs w:val='44'/>");
			out.println ("        </w:rPr>");
			
			deptName=new StringBuilder(aStudent.get("deptName").toString());
			deptName.delete(deptName.length()-1, deptName.length());
			
			out.println ("        <w:t>"+deptName+"科</w:t>");
			out.println ("      </w:r>");
			out.println ("      <w:r wsp:rsidR='00C446DE' wsp:rsidRPr='00084A1D'>");
			out.println ("        <w:rPr>");
			out.println ("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:hint='fareast'/>");
			out.println ("          <wx:font wx:val='標楷體'/>");
			out.println ("          <w:b/>");
			out.println ("          <w:b-cs/>");
			out.println ("          <w:spacing w:val='54'/>");
			out.println ("          <w:sz w:val='44'/>");
			out.println ("          <w:sz-cs w:val='44'/>");
			out.println ("        </w:rPr>");
			out.println ("        <w:t>"+aStudent.get("diviName")+"</w:t>");
			out.println ("      </w:r>");
			out.println ("    </w:p>");
			out.println ("    <w:p wsp:rsidR='00C446DE' wsp:rsidRPr='00084A1D' wsp:rsidRDefault='00C446DE' wsp:rsidP='00DA33B3'>");
			out.println ("      <w:pPr>");
			out.println ("        <w:spacing w:line='640' w:line-rule='exact'/>");
			out.println ("        <w:ind w:left-chars='20' w:left='48'/>");
			out.println ("        <w:rPr>");
			out.println ("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:hint='fareast'/>");
			out.println ("          <wx:font wx:val='標楷體'/>");
			out.println ("          <w:b/>");
			out.println ("          <w:b-cs/>");
			out.println ("          <w:spacing w:val='9'/>");
			out.println ("          <w:kern w:val='0'/>");
			out.println ("          <w:sz w:val='44'/>");
			out.println ("          <w:sz-cs w:val='44'/>");
			out.println ("        </w:rPr>");
			out.println ("      </w:pPr>");
			out.println ("      <w:r wsp:rsidRPr='003940B9'>");
			out.println ("        <w:rPr>");
			out.println ("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:hint='fareast'/>");
			out.println ("          <wx:font wx:val='標楷體'/>");
			out.println ("          <w:b/>");
			out.println ("          <w:b-cs/>");
			out.println ("          <w:spacing w:val='22'/>");
			out.println ("          <w:w w:val='99'/>");
			out.println ("          <w:kern w:val='0'/>");
			out.println ("          <w:sz w:val='44'/>");
			out.println ("          <w:sz-cs w:val='44'/>");
			out.println ("          <w:fitText w:val='7891' w:id='-1238627839'/>");
			out.println ("        </w:rPr>");
			out.println ("        <w:t>修</w:t>");
			out.println ("      </w:r>");
			out.println ("      <w:r wsp:rsidRPr='003940B9'>");
			out.println ("        <w:rPr>");
			out.println ("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:hint='fareast'/>");
			out.println ("          <wx:font wx:val='標楷體'/>");
			out.println ("          <w:b/>");
			out.println ("          <w:b-cs/>");
			out.println ("          <w:w w:val='99'/>");
			out.println ("          <w:kern w:val='0'/>");
			out.println ("          <w:sz w:val='44'/>");
			out.println ("          <w:sz-cs w:val='44'/>");
			out.println ("          <w:fitText w:val='7891' w:id='-1238627839'/>");
			out.println ("        </w:rPr>");
			out.println ("        <w:t>業期滿成績及格准予畢業依學位授予法</w:t>");
			out.println ("      </w:r>");
			out.println ("    </w:p>");
			out.println ("    <w:p wsp:rsidR='00C446DE' wsp:rsidRPr='00084A1D' wsp:rsidRDefault='00C446DE' wsp:rsidP='00DA33B3'>");
			out.println ("      <w:pPr>");
			out.println ("        <w:spacing w:line='640' w:line-rule='exact'/>");
			out.println ("        <w:ind w:left-chars='20' w:left='48'/>");
			out.println ("        <w:rPr>");
			out.println ("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:hint='fareast'/>");
			out.println ("          <wx:font wx:val='標楷體'/>");
			out.println ("          <w:b/>");
			out.println ("          <w:b-cs/>");
			out.println ("          <w:spacing w:val='60'/>");
			out.println ("          <w:sz w:val='44'/>");
			out.println ("          <w:sz-cs w:val='44'/>");
			out.println ("        </w:rPr>");
			out.println ("      </w:pPr>");
			out.println ("      <w:r wsp:rsidRPr='00CA4A0C'>");
			out.println ("        <w:rPr>");
			out.println ("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:hint='fareast'/>");
			out.println ("          <wx:font wx:val='標楷體'/>");
			out.println ("          <w:b/>");
			out.println ("          <w:b-cs/>");
			out.println ("          <w:spacing w:val='4'/>");
			out.println ("          <w:w w:val='89'/>");
			out.println ("          <w:kern w:val='0'/>");
			out.println ("          <w:sz w:val='44'/>");
			out.println ("          <w:sz-cs w:val='44'/>");
			out.println ("          <w:fitText w:val='5549' w:id='-1238627838'/>");
			out.println ("        </w:rPr>");
			out.println ("        <w:t>之規定授予</w:t>");
			out.println ("      </w:r>");
			out.println ("      <w:r wsp:rsidR='00CA4A0C' wsp:rsidRPr='00CA4A0C'>");
			out.println ("        <w:rPr>");
			out.println ("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:hint='fareast'/>");
			out.println ("          <wx:font wx:val='標楷體'/>");
			out.println ("          <w:b/>");
			out.println ("          <w:b-cs/>");
			out.println ("          <w:noProof/>");
			out.println ("          <w:spacing w:val='4'/>");
			out.println ("          <w:w w:val='89'/>");
			out.println ("          <w:kern w:val='0'/>");
			out.println ("          <w:sz w:val='44'/>");
			out.println ("          <w:sz-cs w:val='44'/>");
			out.println ("          <w:fitText w:val='5549' w:id='-1238627838'/>");
			out.println ("        </w:rPr>");
			out.println ("        <w:t>"+aStudent.get("title")+"</w:t>");
			out.println ("      </w:r>");
			out.println ("      <w:r wsp:rsidRPr='00CA4A0C'>");
			out.println ("        <w:rPr>");
			out.println ("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:cs='Arial' w:hint='fareast'/>");
			out.println ("          <wx:font wx:val='標楷體'/>");
			out.println ("          <w:b/>");
			out.println ("          <w:b-cs/>");
			out.println ("          <w:spacing w:val='4'/>");
			out.println ("          <w:w w:val='89'/>");
			out.println ("          <w:kern w:val='0'/>");
			out.println ("          <w:sz w:val='44'/>");
			out.println ("          <w:sz-cs w:val='44'/>");
			out.println ("          <w:fitText w:val='5549' w:id='-1238627838'/>");
			out.println ("        </w:rPr>");
			out.println ("        <w:t>副學士</w:t>");
			out.println ("      </w:r>");
			out.println ("      <w:r wsp:rsidRPr='00CA4A0C'>");
			out.println ("        <w:rPr>");
			out.println ("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:hint='fareast'/>");
			out.println ("          <wx:font wx:val='標楷體'/>");
			out.println ("          <w:b/>");
			out.println ("          <w:b-cs/>");
			out.println ("          <w:spacing w:val='4'/>");
			out.println ("          <w:w w:val='89'/>");
			out.println ("          <w:kern w:val='0'/>");
			out.println ("          <w:sz w:val='44'/>");
			out.println ("          <w:sz-cs w:val='44'/>");
			out.println ("          <w:fitText w:val='5549' w:id='-1238627838'/>");
			out.println ("        </w:rPr>");
			out.println ("        <w:t>學</w:t>");
			out.println ("      </w:r>");
			out.println ("      <w:r wsp:rsidRPr='00CA4A0C'>");
			out.println ("        <w:rPr>");
			out.println ("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:hint='fareast'/>");
			out.println ("          <wx:font wx:val='標楷體'/>");
			out.println ("          <w:b/>");
			out.println ("          <w:b-cs/>");
			out.println ("          <w:spacing w:val='-27'/>");
			out.println ("          <w:w w:val='89'/>");
			out.println ("          <w:kern w:val='0'/>");
			out.println ("          <w:sz w:val='44'/>");
			out.println ("          <w:sz-cs w:val='44'/>");
			out.println ("          <w:fitText w:val='5549' w:id='-1238627838'/>");
			out.println ("        </w:rPr>");
			out.println ("        <w:t>位</w:t>");
			out.println ("      </w:r>");
			out.println ("    </w:p>");
			out.println ("    <w:p wsp:rsidR='00C446DE' wsp:rsidRPr='00084A1D' wsp:rsidRDefault='00C446DE' wsp:rsidP='00DA33B3'>");
			out.println ("      <w:pPr>");
			out.println ("        <w:spacing w:line='640' w:line-rule='exact'/>");
			out.println ("        <w:ind w:left-chars='20' w:left='48'/>");
			out.println ("        <w:rPr>");
			out.println ("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:hint='fareast'/>");
			out.println ("          <wx:font wx:val='標楷體'/>");
			out.println ("          <w:spacing w:val='60'/>");
			out.println ("          <w:sz w:val='44'/>");
			out.println ("          <w:sz-cs w:val='44'/>");
			out.println ("        </w:rPr>");
			out.println ("      </w:pPr>");
			out.println ("      <w:r wsp:rsidRPr='00084A1D'>");
			out.println ("        <w:rPr>");
			out.println ("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:hint='fareast'/>");
			out.println ("          <wx:font wx:val='標楷體'/>");
			out.println ("          <w:b/>");
			out.println ("          <w:b-cs/>");
			out.println ("          <w:spacing w:val='60'/>");
			out.println ("          <w:sz w:val='44'/>");
			out.println ("          <w:sz-cs w:val='44'/>");
			out.println ("        </w:rPr>");
			out.println ("        <w:t>此證</w:t>");
			out.println ("      </w:r>");
			out.println ("    </w:p>");
			out.println ("    <w:p wsp:rsidR='00C446DE' wsp:rsidRDefault='00C446DE' wsp:rsidP='00DA33B3'>");
			out.println ("      <w:pPr>");
			out.println ("        <w:spacing w:line='640' w:line-rule='exact'/>");
			out.println ("        <w:ind w:left='20' w:first-line-chars='200' w:first-line='1040'/>");
			out.println ("        <w:rPr>");
			out.println ("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:hint='fareast'/>");
			out.println ("          <wx:font wx:val='標楷體'/>");
			out.println ("          <w:spacing w:val='60'/>");
			out.println ("          <w:sz w:val='36'/>");
			out.println ("        </w:rPr>");
			out.println ("      </w:pPr>");
			out.println ("      <w:r>");
			out.println ("        <w:rPr>");
			out.println ("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:hint='fareast'/>");
			out.println ("          <wx:font wx:val='標楷體'/>");
			out.println ("          <w:spacing w:val='60'/>");
			out.println ("          <w:sz w:val='40'/>");
			out.println ("        </w:rPr>");
			out.println ("        <w:t>　　　</w:t>");
			out.println ("      </w:r>");
			out.println ("    </w:p>");
			out.println ("    <w:p wsp:rsidR='00C446DE' wsp:rsidRDefault='00C446DE' wsp:rsidP='00DA33B3'>");
			out.println ("      <w:pPr>");
			out.println ("        <w:spacing w:line='640' w:line-rule='exact'/>");
			out.println ("        <w:ind w:left='20'/>");
			out.println ("        <w:rPr>");
			out.println ("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:hint='fareast'/>");
			out.println ("          <wx:font wx:val='標楷體'/>");
			out.println ("          <w:spacing w:val='60'/>");
			out.println ("          <w:sz w:val='40'/>");
			out.println ("        </w:rPr>");
			out.println ("      </w:pPr>");
			out.println ("    </w:p>");
			out.println ("    <w:p wsp:rsidR='00C446DE' wsp:rsidRDefault='00C446DE' wsp:rsidP='00DA33B3'>");
			out.println ("      <w:pPr>");
			out.println ("        <w:spacing w:line='640' w:line-rule='exact'/>");
			out.println ("        <w:ind w:left='20'/>");
			out.println ("        <w:rPr>");
			out.println ("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:hint='fareast'/>");
			out.println ("          <wx:font wx:val='標楷體'/>");
			out.println ("          <w:spacing w:val='60'/>");
			out.println ("          <w:sz w:val='40'/>");
			out.println ("        </w:rPr>");
			out.println ("      </w:pPr>");
			out.println ("    </w:p>");
			out.println ("    <w:p wsp:rsidR='00C446DE' wsp:rsidRDefault='00C446DE' wsp:rsidP='00DA33B3'>");
			out.println ("      <w:pPr>");
			out.println ("        <w:spacing w:line='640' w:line-rule='exact'/>");
			out.println ("        <w:ind w:left='20'/>");
			out.println ("        <w:rPr>");
			out.println ("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:hint='fareast'/>");
			out.println ("          <wx:font wx:val='標楷體'/>");
			out.println ("          <w:spacing w:val='60'/>");
			out.println ("          <w:sz w:val='40'/>");
			out.println ("        </w:rPr>");
			out.println ("      </w:pPr>");
			out.println ("    </w:p>");
			out.println ("    <w:p wsp:rsidR='00C446DE' wsp:rsidRDefault='00C446DE' wsp:rsidP='00DA33B3'>");
			out.println ("      <w:pPr>");
			out.println ("        <w:spacing w:line='640' w:line-rule='exact'/>");
			out.println ("        <w:ind w:left='20'/>");
			out.println ("        <w:rPr>");
			out.println ("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:hint='fareast'/>");
			out.println ("          <wx:font wx:val='標楷體'/>");
			out.println ("          <w:spacing w:val='60'/>");
			out.println ("          <w:sz w:val='40'/>");
			out.println ("        </w:rPr>");
			out.println ("      </w:pPr>");
			out.println ("    </w:p>");
			out.println ("    <w:p wsp:rsidR='00C446DE' wsp:rsidRPr='00D771DB' wsp:rsidRDefault='00C446DE' wsp:rsidP='009852C6'>");
			out.println ("      <w:pPr>");
			out.println ("        <w:spacing w:line='640' w:line-rule='exact'/>");
			out.println ("        <w:ind w:left='20'/>");
			out.println ("        <w:jc w:val='distribute'/>");
			out.println ("        <w:rPr>");
			out.println ("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:hint='fareast'/>");
			out.println ("          <wx:font wx:val='標楷體'/>");
			out.println ("          <w:b/>");
			out.println ("          <w:spacing w:val='60'/>");
			out.println ("          <w:sz w:val='44'/>");
			out.println ("          <w:sz-cs w:val='44'/>");
			out.println ("        </w:rPr>");
			out.println ("      </w:pPr>");
			out.println ("      <w:r wsp:rsidRPr='00D771DB'>");
			out.println ("        <w:rPr>");
			out.println ("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:hint='fareast'/>");
			out.println ("          <wx:font wx:val='標楷體'/>");
			out.println ("          <w:b/>");
			out.println ("          <w:spacing w:val='60'/>");
			out.println ("          <w:sz w:val='44'/>");
			out.println ("          <w:sz-cs w:val='44'/>");
			out.println ("        </w:rPr>");
			out.println ("        <w:t>中華民國</w:t>");
			out.println ("      </w:r>");
			out.println ("      <w:proofErr w:type='gramStart'/>");
			out.println ("      <w:r wsp:rsidR='00CA4A0C'>");
			out.println ("        <w:rPr>");
			out.println ("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:hint='fareast'/>");
			out.println ("          <wx:font wx:val='標楷體'/>");
			out.println ("          <w:b/>");
			out.println ("          <w:spacing w:val='60'/>");
			out.println ("          <w:sz w:val='44'/>");
			out.println ("          <w:sz-cs w:val='44'/>");
			out.println ("        </w:rPr>");
			out.println ("        <w:t>"+aStudent.get("year")+"</w:t>");
			out.println ("      </w:r>");
			out.println ("      <w:proofErr w:type='gramEnd'/>");
			out.println ("      <w:r wsp:rsidRPr='00D771DB'>");
			out.println ("        <w:rPr>");
			out.println ("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:hint='fareast'/>");
			out.println ("          <wx:font wx:val='標楷體'/>");
			out.println ("          <w:b/>");
			out.println ("          <w:spacing w:val='60'/>");
			out.println ("          <w:sz w:val='44'/>");
			out.println ("          <w:sz-cs w:val='44'/>");
			out.println ("        </w:rPr>");
			out.println ("        <w:t>年</w:t>");
			out.println ("      </w:r>");
			out.println ("      <w:proofErr w:type='gramStart'/>");
			out.println ("      <w:r wsp:rsidR='00CA4A0C'>");
			out.println ("        <w:rPr>");
			out.println ("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:hint='fareast'/>");
			out.println ("          <wx:font wx:val='標楷體'/>");
			out.println ("          <w:b/>");
			out.println ("          <w:spacing w:val='60'/>");
			out.println ("          <w:sz w:val='44'/>");
			out.println ("          <w:sz-cs w:val='44'/>");
			out.println ("        </w:rPr>");
			out.println ("        <w:t>"+aStudent.get("month")+"</w:t>");
			out.println ("      </w:r>");
			out.println ("      <w:proofErr w:type='gramEnd'/>");
			out.println ("      <w:r wsp:rsidRPr='00D771DB'>");
			out.println ("        <w:rPr>");
			out.println ("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:hint='fareast'/>");
			out.println ("          <wx:font wx:val='標楷體'/>");
			out.println ("          <w:b/>");
			out.println ("          <w:spacing w:val='60'/>");
			out.println ("          <w:sz w:val='44'/>");
			out.println ("          <w:sz-cs w:val='44'/>");
			out.println ("        </w:rPr>");
			out.println ("        <w:t>月</w:t>");
			out.println ("      </w:r>");
			out.println ("      <w:r>");
			out.println ("        <w:rPr>");
			out.println ("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:hint='fareast'/>");
			out.println ("          <wx:font wx:val='標楷體'/>");
			out.println ("          <w:b/>");
			out.println ("          <w:spacing w:val='60'/>");
			out.println ("          <w:sz w:val='44'/>");
			out.println ("          <w:sz-cs w:val='44'/>");
			out.println ("        </w:rPr>");
			out.println ("        <w:t></w:t>");
			out.println ("      </w:r>");
			out.println ("      <w:r wsp:rsidRPr='00D771DB'>");
			out.println ("        <w:rPr>");
			out.println ("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:hint='fareast'/>");
			out.println ("          <wx:font wx:val='標楷體'/>");
			out.println ("          <w:b/>");
			out.println ("          <w:spacing w:val='60'/>");
			out.println ("          <w:sz w:val='44'/>");
			out.println ("          <w:sz-cs w:val='44'/>");
			out.println ("        </w:rPr>");
			out.println ("        <w:t>　日</w:t>");
			out.println ("      </w:r>");
			out.println ("    </w:p>");
			out.println ("    <w:p wsp:rsidR='00C446DE' wsp:rsidRDefault='00C446DE' wsp:rsidP='005F48C6'>");
			out.println ("      <w:pPr>");
			out.println ("        <w:ind w:left-chars='20' w:left='48'/>");
			out.println ("        <w:rPr>");
			out.println ("          <w:rFonts w:hint='fareast'/>");
			out.println ("        </w:rPr>");
			out.println ("      </w:pPr>");
			out.println ("    </w:p>");
			
			//2011-7-5，為符合2005-7-14更名
			out.println("<w:p wsp:rsidR='001B6D83' wsp:rsidRDefault='00946F4D' wsp:rsidP='001E3A0A'>");
			out.println("      <w:pPr>");
			out.println("        <w:spacing w:line='640' w:line-rule='exact'/>");
			out.println("        <w:ind w:left='20'/>");
			out.println("        <w:rPr>");
			out.println("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體'/>");
			out.println("          <wx:font wx:val='標楷體'/>");
			out.println("          <w:spacing w:val='60'/>");
			out.println("          <w:sz w:val='40'/>");
			out.println("        </w:rPr>");
			out.println("      </w:pPr>");
			out.println("      <w:r wsp:rsidRPr='00946F4D'>");
			out.println("        <w:rPr>");
			out.println("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體'/>");
			out.println("          <wx:font wx:val='標楷體'/>");
			out.println("          <w:noProof/>");
			out.println("          <w:spacing w:val='60'/>");
			out.println("          <w:sz w:val='44'/>");
			out.println("          <w:sz-cs w:val='44'/>");
			out.println("        </w:rPr>");
			out.println("        <w:pict>");
			out.println("          <v:shapetype id='_x0000_t202' coordsize='21600,21600' o:spt='202' path='m,l,21600r21600,l21600,xe'>");
			out.println("            <v:stroke joinstyle='miter'/>");
			out.println("            <v:path gradientshapeok='t' o:connecttype='rect'/>");
			out.println("          </v:shapetype>");
			out.println("          <v:shape id='_x0000_s1026' type='#_x0000_t202' style='position:absolute;left:-1;text-align:left;margin-left:66pt;margin-top:58.85pt;width:280pt;height:35.5pt;z-index:1;mso-width-relative:margin;mso-height-relative:margin' stroked='f'>");
			out.println("            <v:textbox>");
			out.println("              <w:txbxContent>");
			out.println("                <w:p wsp:rsidR='006848C8' wsp:rsidRPr='006848C8' wsp:rsidRDefault='00826C44'>");
			out.println("                  <w:pPr>");
			out.println("                    <w:rPr>");
			out.println("                      <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體'/>");
			out.println("                      <wx:font wx:val='標楷體'/>");
			out.println("                    </w:rPr>");
			out.println("                  </w:pPr>");
			out.println("                  <w:r>");
			out.println("                    <w:rPr>");
			out.println("                      <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:hint='fareast'/>");
			out.println("                      <wx:font wx:val='標楷體'/>");
			out.println("                    </w:rPr>");
			out.println("                    <w:t>【◎本校全銜為中華學校財團法人中華科技大學】</w:t>");
			out.println("                  </w:r>");
			out.println("                </w:p>");
			out.println("              </w:txbxContent>");
			out.println("            </v:textbox>");
			out.println("          </v:shape>");
			out.println("        </w:pict>");
			out.println("      </w:r>");
			out.println("    </w:p>");
			out.println ("    <w:sectPr wsp:rsidR='00C446DE' wsp:rsidSect='005F48C6'>");
			out.println ("      <w:pgSz w:w='11906' w:h='16838' w:code='9'/>");
			out.println ("      <w:pgMar w:top='1418' w:right='1758' w:bottom='567' w:left='1797' w:header='851' w:footer='992' w:gutter='0'/>");
			out.println ("      <w:pgNumType w:start='1'/>");
			out.println ("      <w:cols w:space='425'/>");
			out.println ("      <w:docGrid w:type='lines' w:line-pitch='360'/>");
			out.println ("    </w:sectPr>");
		
			}catch(Exception e){
				
			}
			if(i!=students.size()-1){
				out.println ("    <w:br w:type='page'/>");
			}
			
		}
		
		
		
		
		
		out.println ("  </w:body>");
		out.println ("</w:wordDocument>");
		
		
		
		out.close();
		
		
		return null;		
	}

}
