package tw.edu.chit.struts.action.report.registration.diploma;

import java.io.PrintWriter;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.Map;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import tw.edu.chit.service.CourseManager;
import tw.edu.chit.struts.action.BaseAction;

public class DropOutCht extends BaseAction{

/**
 * 中文修業證書
 */
public ActionForward execute(ActionMapping mapping, ActionForm form, HttpServletRequest request, HttpServletResponse response)throws Exception {	
		
		response.setContentType("text/xml; charset=UTF-8");		
		CourseManager manager = (CourseManager) getBean("courseManager");		
		PrintWriter out=response.getWriter();
		HttpSession session = request.getSession(false);
		Map map=(Map)((List)session.getAttribute("students")).get(0);
				
		Date date=new Date();
		response.setHeader("Content-disposition","attachment;filename=DropOutCht"+date.getTime()+".doc");
		
		out.println ("<?xml version='1.0' encoding='UTF-8' standalone='yes'?>");
		out.println ("<?mso-application progid='Word.Document'?>");
		out.println ("<w:wordDocument xmlns:aml='http://schemas.microsoft.com/aml/2001/core' xmlns:dt='uuid:C2F41010-65B3-11d1-A29F-00AA00C14882' xmlns:ve='http://schemas.openxmlformats.org/markup-compatibility/2006' xmlns:o='urn:schemas-microsoft-com:office:office' xmlns:v='urn:schemas-microsoft-com:vml' xmlns:w10='urn:schemas-microsoft-com:office:word' xmlns:w='http://schemas.microsoft.com/office/word/2003/wordml' xmlns:wx='http://schemas.microsoft.com/office/word/2003/auxHint' xmlns:wsp='http://schemas.microsoft.com/office/word/2003/wordml/sp2' xmlns:sl='http://schemas.microsoft.com/schemaLibrary/2003/core' w:macrosPresent='no' w:embeddedObjPresent='no' w:ocxPresent='no' xml:space='preserve'>");
		out.println ("  <w:ignoreSubtree w:val='http://schemas.microsoft.com/office/word/2003/wordml/sp2'/>");
		out.println ("  <o:DocumentProperties>");
		out.println ("    <o:Title>中華科技大學 修業證明書</o:Title>");
		out.println ("    <o:Author>JOHN</o:Author>");
		out.println ("    <o:LastAuthor>蕭國裕</o:LastAuthor>");
		out.println ("    <o:Revision>2</o:Revision>");
		out.println ("    <o:TotalTime>2</o:TotalTime>");
		out.println ("    <o:Created>2011-01-23T08:26:00Z</o:Created>");
		out.println ("    <o:LastSaved>2011-01-23T08:26:00Z</o:LastSaved>");
		out.println ("    <o:Pages>1</o:Pages>");
		out.println ("    <o:Words>26</o:Words>");
		out.println ("    <o:Characters>153</o:Characters>");
		out.println ("    <o:Lines>1</o:Lines>");
		out.println ("    <o:Paragraphs>1</o:Paragraphs>");
		out.println ("    <o:CharactersWithSpaces>178</o:CharactersWithSpaces>");
		out.println ("    <o:Version>12</o:Version>");
		out.println ("  </o:DocumentProperties>");
		out.println ("  <w:fonts>");
		out.println ("    <w:defaultFonts w:ascii='Times New Roman' w:fareast='新細明體' w:h-ansi='Times New Roman' w:cs='Times New Roman'/>");
		out.println ("    <w:font w:name='Times New Roman'>");
		out.println ("      <w:panose-1 w:val='02020603050405020304'/>");
		out.println ("      <w:charset w:val='00'/>");
		out.println ("      <w:family w:val='Roman'/>");
		out.println ("      <w:pitch w:val='variable'/>");
		out.println ("      <w:sig w:usb-0='20002A87' w:usb-1='80000000' w:usb-2='00000008' w:usb-3='00000000' w:csb-0='000001FF' w:csb-1='00000000'/>");
		out.println ("    </w:font>");
		out.println ("    <w:font w:name='Arial'>");
		out.println ("      <w:panose-1 w:val='020B0604020202020204'/>");
		out.println ("      <w:charset w:val='00'/>");
		out.println ("      <w:family w:val='Swiss'/>");
		out.println ("      <w:pitch w:val='variable'/>");
		out.println ("      <w:sig w:usb-0='20002A87' w:usb-1='80000000' w:usb-2='00000008' w:usb-3='00000000' w:csb-0='000001FF' w:csb-1='00000000'/>");
		out.println ("    </w:font>");
		out.println ("    <w:font w:name='新細明體'>");
		out.println ("      <w:altName w:val='PMingLiU'/>");
		out.println ("      <w:panose-1 w:val='02020300000000000000'/>");
		out.println ("      <w:charset w:val='88'/>");
		out.println ("      <w:family w:val='Roman'/>");
		out.println ("      <w:pitch w:val='variable'/>");
		out.println ("      <w:sig w:usb-0='00000003' w:usb-1='080E0000' w:usb-2='00000016' w:usb-3='00000000' w:csb-0='00100001' w:csb-1='00000000'/>");
		out.println ("    </w:font>");
		out.println ("    <w:font w:name='Cambria Math'>");
		out.println ("      <w:panose-1 w:val='00000000000000000000'/>");
		out.println ("      <w:charset w:val='01'/>");
		out.println ("      <w:family w:val='Roman'/>");
		out.println ("      <w:notTrueType/>");
		out.println ("      <w:pitch w:val='variable'/>");
		out.println ("      <w:sig w:usb-0='00000000' w:usb-1='00000000' w:usb-2='00000000' w:usb-3='00000000' w:csb-0='00000000' w:csb-1='00000000'/>");
		out.println ("    </w:font>");
		out.println ("    <w:font w:name='標楷體'>");
		out.println ("      <w:panose-1 w:val='03000509000000000000'/>");
		out.println ("      <w:charset w:val='88'/>");
		out.println ("      <w:family w:val='Script'/>");
		out.println ("      <w:pitch w:val='fixed'/>");
		out.println ("      <w:sig w:usb-0='00000003' w:usb-1='082E0000' w:usb-2='00000016' w:usb-3='00000000' w:csb-0='00100001' w:csb-1='00000000'/>");
		out.println ("    </w:font>");
		out.println ("    <w:font w:name='@標楷體'>");
		out.println ("      <w:panose-1 w:val='03000509000000000000'/>");
		out.println ("      <w:charset w:val='88'/>");
		out.println ("      <w:family w:val='Script'/>");
		out.println ("      <w:pitch w:val='fixed'/>");
		out.println ("      <w:sig w:usb-0='00000003' w:usb-1='082E0000' w:usb-2='00000016' w:usb-3='00000000' w:csb-0='00100001' w:csb-1='00000000'/>");
		out.println ("    </w:font>");
		out.println ("    <w:font w:name='@新細明體'>");
		out.println ("      <w:panose-1 w:val='02020300000000000000'/>");
		out.println ("      <w:charset w:val='88'/>");
		out.println ("      <w:family w:val='Roman'/>");
		out.println ("      <w:pitch w:val='variable'/>");
		out.println ("      <w:sig w:usb-0='00000003' w:usb-1='082E0000' w:usb-2='00000016' w:usb-3='00000000' w:csb-0='00100001' w:csb-1='00000000'/>");
		out.println ("    </w:font>");
		out.println ("    <w:font w:name='標���體'>");
		out.println ("      <w:panose-1 w:val='00000000000000000000'/>");
		out.println ("      <w:charset w:val='88'/>");
		out.println ("      <w:family w:val='Roman'/>");
		out.println ("      <w:notTrueType/>");
		out.println ("      <w:pitch w:val='default'/>");
		out.println ("      <w:sig w:usb-0='00000000' w:usb-1='00000000' w:usb-2='00000000' w:usb-3='00000000' w:csb-0='00000000' w:csb-1='00000000'/>");
		out.println ("    </w:font>");
		out.println ("    <w:font w:name='標楷���'>");
		out.println ("      <w:panose-1 w:val='00000000000000000000'/>");
		out.println ("      <w:charset w:val='88'/>");
		out.println ("      <w:family w:val='Roman'/>");
		out.println ("      <w:notTrueType/>");
		out.println ("      <w:pitch w:val='default'/>");
		out.println ("      <w:sig w:usb-0='00000000' w:usb-1='00000000' w:usb-2='00000000' w:usb-3='00000000' w:csb-0='00000000' w:csb-1='00000000'/>");
		out.println ("    </w:font>");
		out.println ("    <w:font w:name='標��體'>");
		out.println ("      <w:panose-1 w:val='00000000000000000000'/>");
		out.println ("      <w:charset w:val='88'/>");
		out.println ("      <w:family w:val='Roman'/>");
		out.println ("      <w:notTrueType/>");
		out.println ("      <w:pitch w:val='default'/>");
		out.println ("      <w:sig w:usb-0='00000000' w:usb-1='00000000' w:usb-2='00000000' w:usb-3='00000000' w:csb-0='00000000' w:csb-1='00000000'/>");
		out.println ("    </w:font>");
		out.println ("    <w:font w:name='標楷體'>");
		out.println ("      <w:panose-1 w:val='00000000000000000000'/>");
		out.println ("      <w:charset w:val='88'/>");
		out.println ("      <w:family w:val='Roman'/>");
		out.println ("      <w:notTrueType/>");
		out.println ("      <w:pitch w:val='default'/>");
		out.println ("      <w:sig w:usb-0='00000000' w:usb-1='00000000' w:usb-2='00000000' w:usb-3='00000000' w:csb-0='00000000' w:csb-1='00000000'/>");
		out.println ("    </w:font>");
		out.println ("    <w:font w:name='@標楷體'>");
		out.println ("      <w:panose-1 w:val='00000000000000000000'/>");
		out.println ("      <w:charset w:val='88'/>");
		out.println ("      <w:family w:val='Roman'/>");
		out.println ("      <w:notTrueType/>");
		out.println ("      <w:pitch w:val='default'/>");
		out.println ("      <w:sig w:usb-0='00000000' w:usb-1='00000000' w:usb-2='00000000' w:usb-3='00000000' w:csb-0='00000000' w:csb-1='00000000'/>");
		out.println ("    </w:font>");
		out.println ("    <w:font w:name='@標楷體'>");
		out.println ("      <w:panose-1 w:val='00000000000000000000'/>");
		out.println ("      <w:charset w:val='88'/>");
		out.println ("      <w:family w:val='Roman'/>");
		out.println ("      <w:notTrueType/>");
		out.println ("      <w:pitch w:val='default'/>");
		out.println ("      <w:sig w:usb-0='00000000' w:usb-1='00000000' w:usb-2='00000000' w:usb-3='00000000' w:csb-0='00000000' w:csb-1='00000000'/>");
		out.println ("    </w:font>");
		out.println ("    <w:font w:name='@標楷體'>");
		out.println ("      <w:panose-1 w:val='00000000000000000000'/>");
		out.println ("      <w:charset w:val='88'/>");
		out.println ("      <w:family w:val='Roman'/>");
		out.println ("      <w:notTrueType/>");
		out.println ("      <w:pitch w:val='default'/>");
		out.println ("      <w:sig w:usb-0='00000000' w:usb-1='00000000' w:usb-2='00000000' w:usb-3='00000000' w:csb-0='00000000' w:csb-1='00000000'/>");
		out.println ("    </w:font>");
		out.println ("    <w:font w:name='@標楷體'>");
		out.println ("      <w:panose-1 w:val='00000000000000000000'/>");
		out.println ("      <w:charset w:val='88'/>");
		out.println ("      <w:family w:val='Roman'/>");
		out.println ("      <w:notTrueType/>");
		out.println ("      <w:pitch w:val='default'/>");
		out.println ("      <w:sig w:usb-0='00000000' w:usb-1='00000000' w:usb-2='00000000' w:usb-3='00000000' w:csb-0='00000000' w:csb-1='00000000'/>");
		out.println ("    </w:font>");
		out.println ("  </w:fonts>");
		out.println ("  <w:styles>");
		out.println ("    <w:versionOfBuiltInStylenames w:val='7'/>");
		out.println ("    <w:latentStyles w:defLockedState='off' w:latentStyleCount='267'>");
		out.println ("      <w:lsdException w:name='Normal'/>");
		out.println ("      <w:lsdException w:name='heading 1'/>");
		out.println ("      <w:lsdException w:name='heading 2'/>");
		out.println ("      <w:lsdException w:name='heading 3'/>");
		out.println ("      <w:lsdException w:name='heading 4'/>");
		out.println ("      <w:lsdException w:name='heading 5'/>");
		out.println ("      <w:lsdException w:name='heading 6'/>");
		out.println ("      <w:lsdException w:name='heading 7'/>");
		out.println ("      <w:lsdException w:name='heading 8'/>");
		out.println ("      <w:lsdException w:name='heading 9'/>");
		out.println ("      <w:lsdException w:name='caption'/>");
		out.println ("      <w:lsdException w:name='Title'/>");
		out.println ("      <w:lsdException w:name='Subtitle'/>");
		out.println ("      <w:lsdException w:name='Strong'/>");
		out.println ("      <w:lsdException w:name='Emphasis'/>");
		out.println ("      <w:lsdException w:name='Placeholder Text'/>");
		out.println ("      <w:lsdException w:name='No Spacing'/>");
		out.println ("      <w:lsdException w:name='Light Shading'/>");
		out.println ("      <w:lsdException w:name='Light List'/>");
		out.println ("      <w:lsdException w:name='Light Grid'/>");
		out.println ("      <w:lsdException w:name='Medium Shading 1'/>");
		out.println ("      <w:lsdException w:name='Medium Shading 2'/>");
		out.println ("      <w:lsdException w:name='Medium List 1'/>");
		out.println ("      <w:lsdException w:name='Medium List 2'/>");
		out.println ("      <w:lsdException w:name='Medium Grid 1'/>");
		out.println ("      <w:lsdException w:name='Medium Grid 2'/>");
		out.println ("      <w:lsdException w:name='Medium Grid 3'/>");
		out.println ("      <w:lsdException w:name='Dark List'/>");
		out.println ("      <w:lsdException w:name='Colorful Shading'/>");
		out.println ("      <w:lsdException w:name='Colorful List'/>");
		out.println ("      <w:lsdException w:name='Colorful Grid'/>");
		out.println ("      <w:lsdException w:name='Light Shading Accent 1'/>");
		out.println ("      <w:lsdException w:name='Light List Accent 1'/>");
		out.println ("      <w:lsdException w:name='Light Grid Accent 1'/>");
		out.println ("      <w:lsdException w:name='Medium Shading 1 Accent 1'/>");
		out.println ("      <w:lsdException w:name='Medium Shading 2 Accent 1'/>");
		out.println ("      <w:lsdException w:name='Medium List 1 Accent 1'/>");
		out.println ("      <w:lsdException w:name='Revision'/>");
		out.println ("      <w:lsdException w:name='List Paragraph'/>");
		out.println ("      <w:lsdException w:name='Quote'/>");
		out.println ("      <w:lsdException w:name='Intense Quote'/>");
		out.println ("      <w:lsdException w:name='Medium List 2 Accent 1'/>");
		out.println ("      <w:lsdException w:name='Medium Grid 1 Accent 1'/>");
		out.println ("      <w:lsdException w:name='Medium Grid 2 Accent 1'/>");
		out.println ("      <w:lsdException w:name='Medium Grid 3 Accent 1'/>");
		out.println ("      <w:lsdException w:name='Dark List Accent 1'/>");
		out.println ("      <w:lsdException w:name='Colorful Shading Accent 1'/>");
		out.println ("      <w:lsdException w:name='Colorful List Accent 1'/>");
		out.println ("      <w:lsdException w:name='Colorful Grid Accent 1'/>");
		out.println ("      <w:lsdException w:name='Light Shading Accent 2'/>");
		out.println ("      <w:lsdException w:name='Light List Accent 2'/>");
		out.println ("      <w:lsdException w:name='Light Grid Accent 2'/>");
		out.println ("      <w:lsdException w:name='Medium Shading 1 Accent 2'/>");
		out.println ("      <w:lsdException w:name='Medium Shading 2 Accent 2'/>");
		out.println ("      <w:lsdException w:name='Medium List 1 Accent 2'/>");
		out.println ("      <w:lsdException w:name='Medium List 2 Accent 2'/>");
		out.println ("      <w:lsdException w:name='Medium Grid 1 Accent 2'/>");
		out.println ("      <w:lsdException w:name='Medium Grid 2 Accent 2'/>");
		out.println ("      <w:lsdException w:name='Medium Grid 3 Accent 2'/>");
		out.println ("      <w:lsdException w:name='Dark List Accent 2'/>");
		out.println ("      <w:lsdException w:name='Colorful Shading Accent 2'/>");
		out.println ("      <w:lsdException w:name='Colorful List Accent 2'/>");
		out.println ("      <w:lsdException w:name='Colorful Grid Accent 2'/>");
		out.println ("      <w:lsdException w:name='Light Shading Accent 3'/>");
		out.println ("      <w:lsdException w:name='Light List Accent 3'/>");
		out.println ("      <w:lsdException w:name='Light Grid Accent 3'/>");
		out.println ("      <w:lsdException w:name='Medium Shading 1 Accent 3'/>");
		out.println ("      <w:lsdException w:name='Medium Shading 2 Accent 3'/>");
		out.println ("      <w:lsdException w:name='Medium List 1 Accent 3'/>");
		out.println ("      <w:lsdException w:name='Medium List 2 Accent 3'/>");
		out.println ("      <w:lsdException w:name='Medium Grid 1 Accent 3'/>");
		out.println ("      <w:lsdException w:name='Medium Grid 2 Accent 3'/>");
		out.println ("      <w:lsdException w:name='Medium Grid 3 Accent 3'/>");
		out.println ("      <w:lsdException w:name='Dark List Accent 3'/>");
		out.println ("      <w:lsdException w:name='Colorful Shading Accent 3'/>");
		out.println ("      <w:lsdException w:name='Colorful List Accent 3'/>");
		out.println ("      <w:lsdException w:name='Colorful Grid Accent 3'/>");
		out.println ("      <w:lsdException w:name='Light Shading Accent 4'/>");
		out.println ("      <w:lsdException w:name='Light List Accent 4'/>");
		out.println ("      <w:lsdException w:name='Light Grid Accent 4'/>");
		out.println ("      <w:lsdException w:name='Medium Shading 1 Accent 4'/>");
		out.println ("      <w:lsdException w:name='Medium Shading 2 Accent 4'/>");
		out.println ("      <w:lsdException w:name='Medium List 1 Accent 4'/>");
		out.println ("      <w:lsdException w:name='Medium List 2 Accent 4'/>");
		out.println ("      <w:lsdException w:name='Medium Grid 1 Accent 4'/>");
		out.println ("      <w:lsdException w:name='Medium Grid 2 Accent 4'/>");
		out.println ("      <w:lsdException w:name='Medium Grid 3 Accent 4'/>");
		out.println ("      <w:lsdException w:name='Dark List Accent 4'/>");
		out.println ("      <w:lsdException w:name='Colorful Shading Accent 4'/>");
		out.println ("      <w:lsdException w:name='Colorful List Accent 4'/>");
		out.println ("      <w:lsdException w:name='Colorful Grid Accent 4'/>");
		out.println ("      <w:lsdException w:name='Light Shading Accent 5'/>");
		out.println ("      <w:lsdException w:name='Light List Accent 5'/>");
		out.println ("      <w:lsdException w:name='Light Grid Accent 5'/>");
		out.println ("      <w:lsdException w:name='Medium Shading 1 Accent 5'/>");
		out.println ("      <w:lsdException w:name='Medium Shading 2 Accent 5'/>");
		out.println ("      <w:lsdException w:name='Medium List 1 Accent 5'/>");
		out.println ("      <w:lsdException w:name='Medium List 2 Accent 5'/>");
		out.println ("      <w:lsdException w:name='Medium Grid 1 Accent 5'/>");
		out.println ("      <w:lsdException w:name='Medium Grid 2 Accent 5'/>");
		out.println ("      <w:lsdException w:name='Medium Grid 3 Accent 5'/>");
		out.println ("      <w:lsdException w:name='Dark List Accent 5'/>");
		out.println ("      <w:lsdException w:name='Colorful Shading Accent 5'/>");
		out.println ("      <w:lsdException w:name='Colorful List Accent 5'/>");
		out.println ("      <w:lsdException w:name='Colorful Grid Accent 5'/>");
		out.println ("      <w:lsdException w:name='Light Shading Accent 6'/>");
		out.println ("      <w:lsdException w:name='Light List Accent 6'/>");
		out.println ("      <w:lsdException w:name='Light Grid Accent 6'/>");
		out.println ("      <w:lsdException w:name='Medium Shading 1 Accent 6'/>");
		out.println ("      <w:lsdException w:name='Medium Shading 2 Accent 6'/>");
		out.println ("      <w:lsdException w:name='Medium List 1 Accent 6'/>");
		out.println ("      <w:lsdException w:name='Medium List 2 Accent 6'/>");
		out.println ("      <w:lsdException w:name='Medium Grid 1 Accent 6'/>");
		out.println ("      <w:lsdException w:name='Medium Grid 2 Accent 6'/>");
		out.println ("      <w:lsdException w:name='Medium Grid 3 Accent 6'/>");
		out.println ("      <w:lsdException w:name='Dark List Accent 6'/>");
		out.println ("      <w:lsdException w:name='Colorful Shading Accent 6'/>");
		out.println ("      <w:lsdException w:name='Colorful List Accent 6'/>");
		out.println ("      <w:lsdException w:name='Colorful Grid Accent 6'/>");
		out.println ("      <w:lsdException w:name='Subtle Emphasis'/>");
		out.println ("      <w:lsdException w:name='Intense Emphasis'/>");
		out.println ("      <w:lsdException w:name='Subtle Reference'/>");
		out.println ("      <w:lsdException w:name='Intense Reference'/>");
		out.println ("      <w:lsdException w:name='Book Title'/>");
		out.println ("      <w:lsdException w:name='Bibliography'/>");
		out.println ("      <w:lsdException w:name='TOC Heading'/>");
		out.println ("    </w:latentStyles>");
		out.println ("    <w:style w:type='paragraph' w:default='on' w:styleId='a'>");
		out.println ("      <w:name w:val='Normal'/>");
		out.println ("      <wx:uiName wx:val='內文'/>");
		out.println ("      <w:rsid w:val='002C2F1C'/>");
		out.println ("      <w:pPr>");
		out.println ("        <w:widowControl w:val='off'/>");
		out.println ("      </w:pPr>");
		out.println ("      <w:rPr>");
		out.println ("        <wx:font wx:val='Times New Roman'/>");
		out.println ("        <w:kern w:val='2'/>");
		out.println ("        <w:sz w:val='24'/>");
		out.println ("        <w:sz-cs w:val='24'/>");
		out.println ("        <w:lang w:val='EN-US' w:fareast='ZH-TW' w:bidi='AR-SA'/>");
		out.println ("      </w:rPr>");
		out.println ("    </w:style>");
		out.println ("    <w:style w:type='character' w:default='on' w:styleId='a0'>");
		out.println ("      <w:name w:val='Default Paragraph Font'/>");
		out.println ("      <wx:uiName wx:val='預設段落字型'/>");
		out.println ("    </w:style>");
		out.println ("    <w:style w:type='table' w:default='on' w:styleId='a1'>");
		out.println ("      <w:name w:val='Normal Table'/>");
		out.println ("      <wx:uiName wx:val='表格內文'/>");
		out.println ("      <w:rPr>");
		out.println ("        <wx:font wx:val='Times New Roman'/>");
		out.println ("        <w:lang w:val='EN-US' w:fareast='ZH-TW' w:bidi='AR-SA'/>");
		out.println ("      </w:rPr>");
		out.println ("      <w:tblPr>");
		out.println ("        <w:tblInd w:w='0' w:type='dxa'/>");
		out.println ("        <w:tblCellMar>");
		out.println ("          <w:top w:w='0' w:type='dxa'/>");
		out.println ("          <w:left w:w='108' w:type='dxa'/>");
		out.println ("          <w:bottom w:w='0' w:type='dxa'/>");
		out.println ("          <w:right w:w='108' w:type='dxa'/>");
		out.println ("        </w:tblCellMar>");
		out.println ("      </w:tblPr>");
		out.println ("    </w:style>");
		out.println ("    <w:style w:type='list' w:default='on' w:styleId='a2'>");
		out.println ("      <w:name w:val='No List'/>");
		out.println ("      <wx:uiName wx:val='無清單'/>");
		out.println ("    </w:style>");
		out.println ("    <w:style w:type='paragraph' w:styleId='a3'>");
		out.println ("      <w:name w:val='header'/>");
		out.println ("      <wx:uiName wx:val='頁首'/>");
		out.println ("      <w:basedOn w:val='a'/>");
		out.println ("      <w:link w:val='a4'/>");
		out.println ("      <w:rsid w:val='00900CEB'/>");
		out.println ("      <w:pPr>");
		out.println ("        <w:tabs>");
		out.println ("          <w:tab w:val='center' w:pos='4153'/>");
		out.println ("          <w:tab w:val='right' w:pos='8306'/>");
		out.println ("        </w:tabs>");
		out.println ("        <w:snapToGrid w:val='off'/>");
		out.println ("      </w:pPr>");
		out.println ("      <w:rPr>");
		out.println ("        <wx:font wx:val='Times New Roman'/>");
		out.println ("        <w:sz w:val='20'/>");
		out.println ("        <w:sz-cs w:val='20'/>");
		out.println ("      </w:rPr>");
		out.println ("    </w:style>");
		out.println ("    <w:style w:type='character' w:styleId='a4'>");
		out.println ("      <w:name w:val='頁首 字元'/>");
		out.println ("      <w:basedOn w:val='a0'/>");
		out.println ("      <w:link w:val='a3'/>");
		out.println ("      <w:rsid w:val='00900CEB'/>");
		out.println ("      <w:rPr>");
		out.println ("        <w:kern w:val='2'/>");
		out.println ("      </w:rPr>");
		out.println ("    </w:style>");
		out.println ("    <w:style w:type='paragraph' w:styleId='a5'>");
		out.println ("      <w:name w:val='footer'/>");
		out.println ("      <wx:uiName wx:val='頁尾'/>");
		out.println ("      <w:basedOn w:val='a'/>");
		out.println ("      <w:link w:val='a6'/>");
		out.println ("      <w:rsid w:val='00900CEB'/>");
		out.println ("      <w:pPr>");
		out.println ("        <w:tabs>");
		out.println ("          <w:tab w:val='center' w:pos='4153'/>");
		out.println ("          <w:tab w:val='right' w:pos='8306'/>");
		out.println ("        </w:tabs>");
		out.println ("        <w:snapToGrid w:val='off'/>");
		out.println ("      </w:pPr>");
		out.println ("      <w:rPr>");
		out.println ("        <wx:font wx:val='Times New Roman'/>");
		out.println ("        <w:sz w:val='20'/>");
		out.println ("        <w:sz-cs w:val='20'/>");
		out.println ("      </w:rPr>");
		out.println ("    </w:style>");
		out.println ("    <w:style w:type='character' w:styleId='a6'>");
		out.println ("      <w:name w:val='頁尾 字元'/>");
		out.println ("      <w:basedOn w:val='a0'/>");
		out.println ("      <w:link w:val='a5'/>");
		out.println ("      <w:rsid w:val='00900CEB'/>");
		out.println ("      <w:rPr>");
		out.println ("        <w:kern w:val='2'/>");
		out.println ("      </w:rPr>");
		out.println ("    </w:style>");
		out.println ("  </w:styles>");
		out.println ("  <w:shapeDefaults>");
		out.println ("    <o:shapedefaults v:ext='edit' spidmax='36866'/>");
		out.println ("    <o:shapelayout v:ext='edit'>");
		out.println ("      <o:idmap v:ext='edit' data='1'/>");
		out.println ("    </o:shapelayout>");
		out.println ("  </w:shapeDefaults>");
		out.println ("  <w:docPr>");
		out.println ("    <w:view w:val='print'/>");
		out.println ("    <w:zoom w:percent='100'/>");
		out.println ("    <w:doNotEmbedSystemFonts/>");
		out.println ("    <w:bordersDontSurroundHeader/>");
		out.println ("    <w:bordersDontSurroundFooter/>");
		out.println ("    <w:defaultTabStop w:val='480'/>");
		out.println ("    <w:displayHorizontalDrawingGridEvery w:val='0'/>");
		out.println ("    <w:displayVerticalDrawingGridEvery w:val='2'/>");
		out.println ("    <w:punctuationKerning/>");
		out.println ("    <w:characterSpacingControl w:val='CompressPunctuation'/>");
		out.println ("    <w:optimizeForBrowser/>");
		out.println ("    <w:validateAgainstSchema/>");
		out.println ("    <w:saveInvalidXML w:val='off'/>");
		out.println ("    <w:ignoreMixedContent w:val='off'/>");
		out.println ("    <w:alwaysShowPlaceholderText w:val='off'/>");
		out.println ("    <w:hdrShapeDefaults>");
		out.println ("      <o:shapedefaults v:ext='edit' spidmax='36866'/>");
		out.println ("    </w:hdrShapeDefaults>");
		out.println ("    <w:footnotePr>");
		out.println ("      <w:footnote w:type='separator'>");
		out.println ("        <w:p wsp:rsidR='00EF33BC' wsp:rsidRDefault='00EF33BC' wsp:rsidP='00900CEB'>");
		out.println ("          <w:r>");
		out.println ("            <w:separator/>");
		out.println ("          </w:r>");
		out.println ("        </w:p>");
		out.println ("      </w:footnote>");
		out.println ("      <w:footnote w:type='continuation-separator'>");
		out.println ("        <w:p wsp:rsidR='00EF33BC' wsp:rsidRDefault='00EF33BC' wsp:rsidP='00900CEB'>");
		out.println ("          <w:r>");
		out.println ("            <w:continuationSeparator/>");
		out.println ("          </w:r>");
		out.println ("        </w:p>");
		out.println ("      </w:footnote>");
		out.println ("    </w:footnotePr>");
		out.println ("    <w:endnotePr>");
		out.println ("      <w:endnote w:type='separator'>");
		out.println ("        <w:p wsp:rsidR='00EF33BC' wsp:rsidRDefault='00EF33BC' wsp:rsidP='00900CEB'>");
		out.println ("          <w:r>");
		out.println ("            <w:separator/>");
		out.println ("          </w:r>");
		out.println ("        </w:p>");
		out.println ("      </w:endnote>");
		out.println ("      <w:endnote w:type='continuation-separator'>");
		out.println ("        <w:p wsp:rsidR='00EF33BC' wsp:rsidRDefault='00EF33BC' wsp:rsidP='00900CEB'>");
		out.println ("          <w:r>");
		out.println ("            <w:continuationSeparator/>");
		out.println ("          </w:r>");
		out.println ("        </w:p>");
		out.println ("      </w:endnote>");
		out.println ("    </w:endnotePr>");
		out.println ("    <w:compat>");
		out.println ("      <w:spaceForUL/>");
		out.println ("      <w:balanceSingleByteDoubleByteWidth/>");
		out.println ("      <w:doNotLeaveBackslashAlone/>");
		out.println ("      <w:ulTrailSpace/>");
		out.println ("      <w:doNotExpandShiftReturn/>");
		out.println ("      <w:adjustLineHeightInTable/>");
		out.println ("      <w:breakWrappedTables/>");
		out.println ("      <w:dontAllowFieldEndSelect/>");
		out.println ("      <w:useWord2002TableStyleRules/>");
		out.println ("      <w:useFELayout/>");
		out.println ("    </w:compat>");
		out.println ("    <wsp:rsids>");
		out.println ("      <wsp:rsidRoot wsp:val='00172D8E'/>");
		out.println ("      <wsp:rsid wsp:val='00040005'/>");
		out.println ("      <wsp:rsid wsp:val='000F4049'/>");
		out.println ("      <wsp:rsid wsp:val='00116CBE'/>");
		out.println ("      <wsp:rsid wsp:val='00121C35'/>");
		out.println ("      <wsp:rsid wsp:val='00123DFA'/>");
		out.println ("      <wsp:rsid wsp:val='00155218'/>");
		out.println ("      <wsp:rsid wsp:val='00172D8E'/>");
		out.println ("      <wsp:rsid wsp:val='001A3EA1'/>");
		out.println ("      <wsp:rsid wsp:val='001A5F60'/>");
		out.println ("      <wsp:rsid wsp:val='001E7040'/>");
		out.println ("      <wsp:rsid wsp:val='0026789D'/>");
		out.println ("      <wsp:rsid wsp:val='00291DAB'/>");
		out.println ("      <wsp:rsid wsp:val='0029381A'/>");
		out.println ("      <wsp:rsid wsp:val='002A2750'/>");
		out.println ("      <wsp:rsid wsp:val='002A70D5'/>");
		out.println ("      <wsp:rsid wsp:val='002C2F1C'/>");
		out.println ("      <wsp:rsid wsp:val='002D2EB9'/>");
		out.println ("      <wsp:rsid wsp:val='002E3355'/>");
		out.println ("      <wsp:rsid wsp:val='002F099B'/>");
		out.println ("      <wsp:rsid wsp:val='00313E8F'/>");
		out.println ("      <wsp:rsid wsp:val='003252DF'/>");
		out.println ("      <wsp:rsid wsp:val='0035506B'/>");
		out.println ("      <wsp:rsid wsp:val='0036047E'/>");
		out.println ("      <wsp:rsid wsp:val='00382AD1'/>");
		out.println ("      <wsp:rsid wsp:val='0038426A'/>");
		out.println ("      <wsp:rsid wsp:val='003B0B0E'/>");
		out.println ("      <wsp:rsid wsp:val='003B6A2F'/>");
		out.println ("      <wsp:rsid wsp:val='003C1E32'/>");
		out.println ("      <wsp:rsid wsp:val='003D18DE'/>");
		out.println ("      <wsp:rsid wsp:val='003D6549'/>");
		out.println ("      <wsp:rsid wsp:val='0043591C'/>");
		out.println ("      <wsp:rsid wsp:val='00442431'/>");
		out.println ("      <wsp:rsid wsp:val='004815A0'/>");
		out.println ("      <wsp:rsid wsp:val='004819A7'/>");
		out.println ("      <wsp:rsid wsp:val='00485A34'/>");
		out.println ("      <wsp:rsid wsp:val='004A0182'/>");
		out.println ("      <wsp:rsid wsp:val='004B537F'/>");
		out.println ("      <wsp:rsid wsp:val='004B760B'/>");
		out.println ("      <wsp:rsid wsp:val='0050172F'/>");
		out.println ("      <wsp:rsid wsp:val='005809D0'/>");
		out.println ("      <wsp:rsid wsp:val='005D245E'/>");
		out.println ("      <wsp:rsid wsp:val='00610CEC'/>");
		out.println ("      <wsp:rsid wsp:val='006246AF'/>");
		out.println ("      <wsp:rsid wsp:val='0063405D'/>");
		out.println ("      <wsp:rsid wsp:val='006D2DFF'/>");
		out.println ("      <wsp:rsid wsp:val='00730F96'/>");
		out.println ("      <wsp:rsid wsp:val='00786952'/>");
		out.println ("      <wsp:rsid wsp:val='007D6D99'/>");
		out.println ("      <wsp:rsid wsp:val='008364C3'/>");
		out.println ("      <wsp:rsid wsp:val='00864FB4'/>");
		out.println ("      <wsp:rsid wsp:val='008E0D2B'/>");
		out.println ("      <wsp:rsid wsp:val='008E5A9D'/>");
		out.println ("      <wsp:rsid wsp:val='008F3EA9'/>");
		out.println ("      <wsp:rsid wsp:val='00900CEB'/>");
		out.println ("      <wsp:rsid wsp:val='0090138C'/>");
		out.println ("      <wsp:rsid wsp:val='00937508'/>");
		out.println ("      <wsp:rsid wsp:val='0096361E'/>");
		out.println ("      <wsp:rsid wsp:val='00975442'/>");
		out.println ("      <wsp:rsid wsp:val='009818DC'/>");
		out.println ("      <wsp:rsid wsp:val='009942E8'/>");
		out.println ("      <wsp:rsid wsp:val='009D3612'/>");
		out.println ("      <wsp:rsid wsp:val='00A0781A'/>");
		out.println ("      <wsp:rsid wsp:val='00A10981'/>");
		out.println ("      <wsp:rsid wsp:val='00A11FF4'/>");
		out.println ("      <wsp:rsid wsp:val='00A41952'/>");
		out.println ("      <wsp:rsid wsp:val='00A92F27'/>");
		out.println ("      <wsp:rsid wsp:val='00AA2DE0'/>");
		out.println ("      <wsp:rsid wsp:val='00B742D4'/>");
		out.println ("      <wsp:rsid wsp:val='00BA7247'/>");
		out.println ("      <wsp:rsid wsp:val='00BB08D6'/>");
		out.println ("      <wsp:rsid wsp:val='00BF4C09'/>");
		out.println ("      <wsp:rsid wsp:val='00C763CA'/>");
		out.println ("      <wsp:rsid wsp:val='00C937AF'/>");
		out.println ("      <wsp:rsid wsp:val='00CD6424'/>");
		out.println ("      <wsp:rsid wsp:val='00CD784C'/>");
		out.println ("      <wsp:rsid wsp:val='00CE04FC'/>");
		out.println ("      <wsp:rsid wsp:val='00CE3C65'/>");
		out.println ("      <wsp:rsid wsp:val='00D35C43'/>");
		out.println ("      <wsp:rsid wsp:val='00D93956'/>");
		out.println ("      <wsp:rsid wsp:val='00DE5436'/>");
		out.println ("      <wsp:rsid wsp:val='00E062CC'/>");
		out.println ("      <wsp:rsid wsp:val='00E13BAA'/>");
		out.println ("      <wsp:rsid wsp:val='00E40481'/>");
		out.println ("      <wsp:rsid wsp:val='00E74C4E'/>");
		out.println ("      <wsp:rsid wsp:val='00ED1F7F'/>");
		out.println ("      <wsp:rsid wsp:val='00EE0B04'/>");
		out.println ("      <wsp:rsid wsp:val='00EF33BC'/>");
		out.println ("      <wsp:rsid wsp:val='00EF6868'/>");
		out.println ("      <wsp:rsid wsp:val='00F0249C'/>");
		out.println ("      <wsp:rsid wsp:val='00F02B8A'/>");
		out.println ("      <wsp:rsid wsp:val='00F66838'/>");
		out.println ("      <wsp:rsid wsp:val='00F736B8'/>");
		out.println ("      <wsp:rsid wsp:val='00FA292A'/>");
		out.println ("      <wsp:rsid wsp:val='00FA5962'/>");
		out.println ("      <wsp:rsid wsp:val='00FE3394'/>");
		out.println ("      <wsp:rsid wsp:val='00FF41B0'/>");
		out.println ("    </wsp:rsids>");
		out.println ("  </w:docPr>");
		out.println ("  <w:body>");
		out.println ("    <w:p wsp:rsidR='002A2750' wsp:rsidRPr='00786952' wsp:rsidRDefault='00730F96' wsp:rsidP='002A2750'>");
		out.println ("      <w:pPr>");
		out.println ("        <w:jc w:val='center'/>");
		out.println ("        <w:rPr>");
		out.println ("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:cs='Arial'/>");
		out.println ("          <wx:font wx:val='標楷體'/>");
		out.println ("          <w:b/>");
		out.println ("          <w:sz w:val='40'/>");
		out.println ("          <w:sz-cs w:val='40'/>");
		out.println ("        </w:rPr>");
		out.println ("      </w:pPr>");
		out.println ("      <w:r wsp:rsidRPr='00786952'>");
		out.println ("        <w:rPr>");
		out.println ("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:cs='Arial'/>");
		out.println ("          <wx:font wx:val='標楷體'/>");
		out.println ("          <w:b/>");
		out.println ("          <w:sz w:val='40'/>");
		out.println ("          <w:sz-cs w:val='40'/>");
		out.println ("        </w:rPr>");
		out.println ("        <w:t>中華</w:t>");
		out.println ("      </w:r>");
		out.println ("      <w:r wsp:rsidR='00172D8E' wsp:rsidRPr='00786952'>");
		out.println ("        <w:rPr>");
		out.println ("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:cs='Arial'/>");
		out.println ("          <wx:font wx:val='標楷體'/>");
		out.println ("          <w:b/>");
		out.println ("          <w:sz w:val='40'/>");
		out.println ("          <w:sz-cs w:val='40'/>");
		out.println ("        </w:rPr>");
		out.println ("        <w:t>科技大學修業證明書</w:t>");
		out.println ("      </w:r>");
		out.println ("    </w:p>");
		out.println ("    <w:p wsp:rsidR='00172D8E' wsp:rsidRPr='00786952' wsp:rsidRDefault='00172D8E' wsp:rsidP='002A2750'>");
		out.println ("      <w:pPr>");
		out.println ("        <w:jc w:val='right'/>");
		out.println ("        <w:rPr>");
		out.println ("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:cs='Arial'/>");
		out.println ("          <wx:font wx:val='標楷體'/>");
		out.println ("          <w:b/>");
		out.println ("        </w:rPr>");
		out.println ("      </w:pPr>");
		out.println ("      <w:r wsp:rsidRPr='00786952'>");
		out.println ("        <w:rPr>");
		out.println ("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:cs='Arial'/>");
		out.println ("          <wx:font wx:val='標楷體'/>");
		out.println ("          <w:b/>");
		out.println ("          <w:sz w:val='20'/>");
		out.println ("          <w:sz-cs w:val='20'/>");
		out.println ("        </w:rPr>");
		out.println ("        <w:t>華科大教註字</w:t>");
		out.println ("      </w:r>");
		out.println ("      <w:r wsp:rsidR='00900CEB'>");
		out.println ("        <w:rPr>");
		out.println ("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:cs='Arial' w:hint='fareast'/>");
		out.println ("          <wx:font wx:val='標楷體'/>");
		out.println ("          <w:b/>");
		out.println ("          <w:sz w:val='20'/>");
		out.println ("          <w:sz-cs w:val='20'/>");
		out.println ("        </w:rPr>");
		
		String Oid=map.get("Oid").toString();
		String deptNo=manager.ezGetString("SELECT depart_class FROM Gstmd WHERE student_no='"+map.get("student_no")+"'").substring(0, 4);
		map=manager.ezGetMap("SELECT * FROM Gstmd WHERE Oid="+Oid);
		if(map==null){
			map=manager.ezGetMap("SELECT * FROM stmd WHERE Oid="+Oid);
			deptNo=manager.ezGetString("SELECT depart_class FROM stmd WHERE student_no='"+map.get("student_no")+"'").substring(0, 4);;
		}
		
		out.println ("        <w:t>"+map.get("student_no")+"</w:t>");
		out.println ("      </w:r>");
		out.println ("      <w:r wsp:rsidRPr='00786952'>");
		out.println ("        <w:rPr>");
		out.println ("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:cs='Arial'/>");
		out.println ("          <wx:font wx:val='標楷體'/>");
		out.println ("          <w:b/>");
		out.println ("          <w:sz w:val='20'/>");
		out.println ("          <w:sz-cs w:val='20'/>");
		out.println ("        </w:rPr>");
		out.println ("        <w:t>號</w:t>");
		out.println ("      </w:r>");
		out.println ("    </w:p>");
		out.println ("    <w:p wsp:rsidR='00172D8E' wsp:rsidRPr='00786952' wsp:rsidRDefault='00172D8E' wsp:rsidP='00172D8E'>");
		out.println ("      <w:pPr>");
		out.println ("        <w:rPr>");
		out.println ("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:cs='Arial'/>");
		out.println ("          <wx:font wx:val='標楷體'/>");
		out.println ("          <w:sz w:val='28'/>");
		out.println ("          <w:sz-cs w:val='28'/>");
		out.println ("        </w:rPr>");
		out.println ("      </w:pPr>");
		out.println ("    </w:p>");
		out.println ("    <w:p wsp:rsidR='00172D8E' wsp:rsidRPr='00786952' wsp:rsidRDefault='00172D8E' wsp:rsidP='00900CEB'>");
		out.println ("      <w:pPr>");
		out.println ("        <w:spacing w:line='320' w:line-rule='exact'/>");
		out.println ("        <w:ind w:left-chars='400' w:left='960'/>");
		out.println ("        <w:rPr>");
		out.println ("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:cs='Arial'/>");
		out.println ("          <wx:font wx:val='標楷體'/>");
		out.println ("          <w:b/>");
		out.println ("          <w:sz w:val='32'/>");
		out.println ("          <w:sz-cs w:val='32'/>");
		out.println ("        </w:rPr>");
		out.println ("      </w:pPr>");
		out.println ("      <w:r wsp:rsidRPr='00786952'>");
		out.println ("        <w:rPr>");
		out.println ("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:cs='Arial'/>");
		out.println ("          <wx:font wx:val='標楷體'/>");
		out.println ("          <w:b/>");
		out.println ("          <w:sz w:val='32'/>");
		out.println ("          <w:sz-cs w:val='32'/>");
		out.println ("        </w:rPr>");
		out.println ("        <w:t>學生</w:t>");
		out.println ("      </w:r>");
		out.println ("      <w:r wsp:rsidR='00900CEB'>");
		out.println ("        <w:rPr>");
		out.println ("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:cs='Arial' w:hint='fareast'/>");
		out.println ("          <wx:font wx:val='標楷體'/>");
		out.println ("          <w:b/>");
		out.println ("          <w:sz w:val='32'/>");
		out.println ("          <w:sz-cs w:val='32'/>");
		out.println ("        </w:rPr>");
		out.println ("        <w:t>"+map.get("student_name")+"</w:t>");
		out.println ("      </w:r>");
		out.println ("      <w:r wsp:rsidRPr='00786952'>");
		out.println ("        <w:rPr>");
		out.println ("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:cs='Arial'/>");
		out.println ("          <wx:font wx:val='標楷體'/>");
		out.println ("          <w:b/>");
		out.println ("          <w:sz w:val='32'/>");
		out.println ("          <w:sz-cs w:val='32'/>");
		out.println ("        </w:rPr>");
		out.println ("        <w:t>中華民國</w:t>");
		out.println ("      </w:r>");
		out.println ("      <w:r wsp:rsidR='00864FB4' wsp:rsidRPr='00786952'>");
		out.println ("        <w:rPr>");
		out.println ("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:cs='Arial' w:hint='fareast'/>");
		out.println ("          <wx:font wx:val='標楷體'/>");
		out.println ("          <w:b/>");
		out.println ("          <w:sz w:val='32'/>");
		out.println ("          <w:sz-cs w:val='32'/>");
		out.println ("        </w:rPr>");
		
		SimpleDateFormat sf=new SimpleDateFormat("yyyy-MM-dd");
		Calendar c=Calendar.getInstance();
		c.setTime(sf.parse(map.get("birthday").toString()));
		
		out.println ("        <w:t>"+(c.get(Calendar.YEAR)-1911)+"</w:t>");
		out.println ("      </w:r>");
		out.println ("      <w:r wsp:rsidRPr='00786952'>");
		out.println ("        <w:rPr>");
		out.println ("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:cs='Arial'/>");
		out.println ("          <wx:font wx:val='標楷體'/>");
		out.println ("          <w:b/>");
		out.println ("          <w:sz w:val='32'/>");
		out.println ("          <w:sz-cs w:val='32'/>");
		out.println ("        </w:rPr>");
		out.println ("        <w:t>年</w:t>");
		out.println ("      </w:r>");
		out.println ("      <w:r wsp:rsidR='0096361E' wsp:rsidRPr='00786952'>");
		out.println ("        <w:rPr>");
		out.println ("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:cs='Arial' w:hint='fareast'/>");
		out.println ("          <wx:font wx:val='標楷體'/>");
		out.println ("          <w:b/>");
		out.println ("          <w:sz w:val='32'/>");
		out.println ("          <w:sz-cs w:val='32'/>");
		out.println ("        </w:rPr>");
		out.println ("        <w:t>"+(c.get(Calendar.MONTH)+1)+"</w:t>");
		out.println ("      </w:r>");
		out.println ("      <w:r wsp:rsidRPr='00786952'>");
		out.println ("        <w:rPr>");
		out.println ("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標���體' w:cs='Arial'/>");
		out.println ("          <wx:font wx:val='標楷體'/>");
		out.println ("          <w:b/>");
		out.println ("          <w:sz w:val='32'/>");
		out.println ("          <w:sz-cs w:val='32'/>");
		out.println ("        </w:rPr>");
		out.println ("        <w:t>月</w:t>");
		out.println ("      </w:r>");
		out.println ("      <w:r wsp:rsidR='0096361E' wsp:rsidRPr='00786952'>");
		out.println ("        <w:rPr>");
		out.println ("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷���' w:cs='Arial' w:hint='fareast'/>");
		out.println ("          <wx:font wx:val='標楷體'/>");
		out.println ("          <w:b/>");
		out.println ("          <w:sz w:val='32'/>");
		out.println ("          <w:sz-cs w:val='32'/>");
		out.println ("        </w:rPr>");
		out.println ("        <w:t>"+(c.get(Calendar.DAY_OF_MONTH))+"</w:t>");
		out.println ("      </w:r>");
		out.println ("      <w:r wsp:rsidRPr='00786952'>");
		out.println ("        <w:rPr>");
		out.println ("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:cs='Arial'/>");
		out.println ("          <wx:font wx:val='標楷體'/>");
		out.println ("          <w:b/>");
		out.println ("          <w:sz w:val='32'/>");
		out.println ("          <w:sz-cs w:val='32'/>");
		out.println ("        </w:rPr>");
		out.println ("        <w:t>日生，</w:t>");
		out.println ("      </w:r>");
		out.println ("    </w:p>");
		out.println ("    <w:p wsp:rsidR='00172D8E' wsp:rsidRPr='00786952' wsp:rsidRDefault='00172D8E' wsp:rsidP='00900CEB'>");
		out.println ("      <w:pPr>");
		out.println ("        <w:spacing w:line='320' w:line-rule='exact'/>");
		out.println ("        <w:ind w:left-chars='400' w:left='960'/>");
		out.println ("        <w:rPr>");
		out.println ("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:cs='Arial'/>");
		out.println ("          <wx:font wx:val='標楷體'/>");
		out.println ("          <w:b/>");
		out.println ("          <w:sz w:val='32'/>");
		out.println ("          <w:sz-cs w:val='32'/>");
		out.println ("        </w:rPr>");
		out.println ("      </w:pPr>");
		out.println ("    </w:p>");
		out.println ("    <w:p wsp:rsidR='00172D8E' wsp:rsidRPr='00786952' wsp:rsidRDefault='00172D8E' wsp:rsidP='00900CEB'>");
		out.println ("      <w:pPr>");
		out.println ("        <w:spacing w:line='320' w:line-rule='exact'/>");
		out.println ("        <w:ind w:left-chars='400' w:left='960'/>");
		out.println ("        <w:rPr>");
		out.println ("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標��體' w:cs='Arial' w:hint='fareast'/>");
		out.println ("          <wx:font wx:val='標楷體'/>");
		out.println ("          <w:b/>");
		out.println ("          <w:sz w:val='32'/>");
		out.println ("          <w:sz-cs w:val='32'/>");
		out.println ("        </w:rPr>");
		out.println ("      </w:pPr>");
		out.println ("      <w:r wsp:rsidRPr='00786952'>");
		out.println ("        <w:rPr>");
		out.println ("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:cs='Arial'/>");
		out.println ("          <wx:font wx:val='標楷體'/>");
		out.println ("          <w:b/>");
		out.println ("          <w:sz w:val='32'/>");
		out.println ("          <w:sz-cs w:val='32'/>");
		out.println ("        </w:rPr>");
		out.println ("        <w:t>於</w:t>");
		out.println ("      </w:r>");
		out.println ("      <w:r wsp:rsidR='00900CEB'>");
		out.println ("        <w:rPr>");
		out.println ("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:cs='Arial' w:hint='fareast'/>");
		out.println ("          <wx:font wx:val='標楷體'/>");
		out.println ("          <w:b/>");
		out.println ("          <w:sz w:val='32'/>");
		out.println ("          <w:sz-cs w:val='32'/>");
		out.println ("        </w:rPr>");
		
		String entrance=map.get("entrance").toString();
		
		//System.out.println(entrance.length());
		if(entrance.length()>4){
			out.println ("        <w:t>"+entrance.substring(0, 3)+"</w:t>");
		}else{
			out.println ("        <w:t>"+entrance.substring(0, 2)+"</w:t>");
		}
		
		out.println ("      </w:r>");
		out.println ("      <w:r wsp:rsidRPr='00786952'>");
		out.println ("        <w:rPr>");
		out.println ("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:cs='Arial'/>");
		out.println ("          <wx:font wx:val='標楷體'/>");
		out.println ("          <w:b/>");
		out.println ("          <w:sz w:val='32'/>");
		out.println ("          <w:sz-cs w:val='32'/>");
		out.println ("        </w:rPr>");
		out.println ("        <w:t>年</w:t>");
		out.println ("      </w:r>");
		out.println ("      <w:r wsp:rsidR='00900CEB'>");
		out.println ("        <w:rPr>");
		out.println ("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:cs='Arial' w:hint='fareast'/>");
		out.println ("          <wx:font wx:val='標楷體'/>");
		out.println ("          <w:b/>");
		out.println ("          <w:sz w:val='32'/>");
		out.println ("          <w:sz-cs w:val='32'/>");
		out.println ("        </w:rPr>");
		out.println ("        <w:t>"+Integer.parseInt(entrance.substring(entrance.length()-2, entrance.length()))+"</w:t>");
		out.println ("      </w:r>");
		out.println ("      <w:r wsp:rsidRPr='00786952'>");
		out.println ("        <w:rPr>");
		out.println ("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:cs='Arial'/>");
		out.println ("          <wx:font wx:val='標楷體'/>");
		out.println ("          <w:b/>");
		out.println ("          <w:sz w:val='32'/>");
		out.println ("          <w:sz-cs w:val='32'/>");
		out.println ("        </w:rPr>");
		out.println ("        <w:t>月考入本校</w:t>");
		out.println ("      </w:r>");
		out.println ("      <w:r wsp:rsidR='00900CEB'>");
		out.println ("        <w:rPr>");
		out.println ("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:cs='Arial' w:hint='fareast'/>");
		out.println ("          <wx:font wx:val='標楷體'/>");
		out.println ("          <w:b/>");
		out.println ("          <w:sz w:val='32'/>");
		out.println ("          <w:sz-cs w:val='32'/>");
		out.println ("        </w:rPr>");
		out.println ("        <w:t>"+manager.ezGetString("SELECT fname FROM dept WHERE no='"+deptNo+"'")+"</w:t>");
		out.println ("      </w:r>");
		out.println ("    </w:p>");
		out.println ("    <w:p wsp:rsidR='00172D8E' wsp:rsidRPr='00786952' wsp:rsidRDefault='00172D8E' wsp:rsidP='00900CEB'>");
		out.println ("      <w:pPr>");
		out.println ("        <w:spacing w:line='320' w:line-rule='exact'/>");
		out.println ("        <w:ind w:left-chars='400' w:left='960'/>");
		out.println ("        <w:rPr>");
		out.println ("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:cs='Arial'/>");
		out.println ("          <wx:font wx:val='標楷體'/>");
		out.println ("          <w:b/>");
		out.println ("          <w:sz w:val='32'/>");
		out.println ("          <w:sz-cs w:val='32'/>");
		out.println ("        </w:rPr>");
		out.println ("      </w:pPr>");
		out.println ("    </w:p>");
		out.println ("    <w:p wsp:rsidR='00172D8E' wsp:rsidRPr='00786952' wsp:rsidRDefault='00900CEB' wsp:rsidP='00900CEB'>");
		out.println ("      <w:pPr>");
		out.println ("        <w:spacing w:line='320' w:line-rule='exact'/>");
		out.println ("        <w:ind w:left-chars='400' w:left='960'/>");
		out.println ("        <w:rPr>");
		out.println ("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:cs='Arial'/>");
		out.println ("          <wx:font wx:val='標楷體'/>");
		out.println ("          <w:b/>");
		out.println ("          <w:sz w:val='32'/>");
		out.println ("          <w:sz-cs w:val='32'/>");
		out.println ("        </w:rPr>");
		out.println ("      </w:pPr>");
		out.println ("      <w:r>");
		out.println ("        <w:rPr>");
		out.println ("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:cs='Arial' w:hint='fareast'/>");
		out.println ("          <wx:font wx:val='標楷體'/>");
		out.println ("          <w:b/>");
		out.println ("          <w:sz w:val='32'/>");
		out.println ("          <w:sz-cs w:val='32'/>");
		out.println ("        </w:rPr>");
		out.println ("        <w:t>1</w:t>");
		out.println ("      </w:r>");
		out.println ("      <w:r wsp:rsidR='00172D8E' wsp:rsidRPr='00786952'>");
		out.println ("        <w:rPr>");
		out.println ("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:cs='Arial'/>");
		out.println ("          <wx:font wx:val='標楷體'/>");
		out.println ("          <w:b/>");
		out.println ("          <w:sz w:val='32'/>");
		out.println ("          <w:sz-cs w:val='32'/>");
		out.println ("        </w:rPr>");
		out.println ("        <w:t>年級第</w:t>");
		out.println ("      </w:r>");
		out.println ("      <w:r>");
		out.println ("        <w:rPr>");
		out.println ("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:cs='Arial' w:hint='fareast'/>");
		out.println ("          <wx:font wx:val='標楷體'/>");
		out.println ("          <w:b/>");
		out.println ("          <w:sz w:val='32'/>");
		out.println ("          <w:sz-cs w:val='32'/>");
		out.println ("        </w:rPr>");
		out.println ("        <w:t>1</w:t>");
		out.println ("      </w:r>");
		out.println ("      <w:r wsp:rsidR='00172D8E' wsp:rsidRPr='00786952'>");
		out.println ("        <w:rPr>");
		out.println ("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:cs='Arial'/>");
		out.println ("          <wx:font wx:val='標楷體'/>");
		out.println ("          <w:b/>");
		out.println ("          <w:sz w:val='32'/>");
		out.println ("          <w:sz-cs w:val='32'/>");
		out.println ("        </w:rPr>");
		out.println ("        <w:t>學期肄業，至</w:t>");
		out.println ("      </w:r>");
		out.println ("      <w:r>");
		out.println ("        <w:rPr>");
		out.println ("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:cs='Arial' w:hint='fareast'/>");
		out.println ("          <wx:font wx:val='標楷體'/>");
		out.println ("          <w:b/>");
		out.println ("          <w:sz w:val='32'/>");
		out.println ("          <w:sz-cs w:val='32'/>");
		out.println ("        </w:rPr>");
		
		Calendar c1=Calendar.getInstance();
		c1.setTime(new Date());
		
		out.println ("        <w:t>"+(c1.get(Calendar.YEAR)-1911)+"</w:t>");
		out.println ("      </w:r>");
		out.println ("      <w:r wsp:rsidR='00172D8E' wsp:rsidRPr='00786952'>");
		out.println ("        <w:rPr>");
		out.println ("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:cs='Arial'/>");
		out.println ("          <wx:font wx:val='標楷體'/>");
		out.println ("          <w:b/>");
		out.println ("          <w:sz w:val='32'/>");
		out.println ("          <w:sz-cs w:val='32'/>");
		out.println ("        </w:rPr>");
		out.println ("        <w:t>年</w:t>");
		out.println ("      </w:r>");
		out.println ("      <w:r>");
		out.println ("        <w:rPr>");
		out.println ("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:cs='Arial' w:hint='fareast'/>");
		out.println ("          <wx:font wx:val='標楷體'/>");
		out.println ("          <w:b/>");
		out.println ("          <w:sz w:val='32'/>");
		out.println ("          <w:sz-cs w:val='32'/>");
		out.println ("        </w:rPr>");
		out.println ("        <w:t>"+(c1.get(Calendar.MONTH)+1)+"</w:t>");
		out.println ("      </w:r>");
		out.println ("      <w:r wsp:rsidR='00172D8E' wsp:rsidRPr='00786952'>");
		out.println ("        <w:rPr>");
		out.println ("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:cs='Arial'/>");
		out.println ("          <wx:font wx:val='標楷體'/>");
		out.println ("          <w:b/>");
		out.println ("          <w:sz w:val='32'/>");
		out.println ("          <w:sz-cs w:val='32'/>");
		out.println ("        </w:rPr>");
		out.println ("        <w:t>月止，修畢</w:t>");
		out.println ("      </w:r>");
		out.println ("    </w:p>");
		out.println ("    <w:p wsp:rsidR='00172D8E' wsp:rsidRPr='00786952' wsp:rsidRDefault='00172D8E' wsp:rsidP='00900CEB'>");
		out.println ("      <w:pPr>");
		out.println ("        <w:spacing w:line='320' w:line-rule='exact'/>");
		out.println ("        <w:ind w:left-chars='400' w:left='960'/>");
		out.println ("        <w:rPr>");
		out.println ("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:cs='Arial'/>");
		out.println ("          <wx:font wx:val='標楷體'/>");
		out.println ("          <w:b/>");
		out.println ("          <w:sz w:val='32'/>");
		out.println ("          <w:sz-cs w:val='32'/>");
		out.println ("        </w:rPr>");
		out.println ("      </w:pPr>");
		out.println ("    </w:p>");
		
		out.println ("    <w:p wsp:rsidR='00172D8E' wsp:rsidRPr='00786952' wsp:rsidRDefault='00900CEB' wsp:rsidP='00900CEB'>");
		out.println ("      <w:pPr>");
		out.println ("        <w:spacing w:line='320' w:line-rule='exact'/>");
		out.println ("        <w:ind w:left-chars='400' w:left='960'/>");
		out.println ("        <w:rPr>");
		out.println ("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:cs='Arial'/>");
		out.println ("          <wx:font wx:val='標楷體'/>");
		out.println ("          <w:b/>");
		out.println ("          <w:sz w:val='32'/>");
		out.println ("          <w:sz-cs w:val='32'/>");
		out.println ("        </w:rPr>");
		out.println ("      </w:pPr>");
		out.println ("      <w:r>");
		out.println ("        <w:rPr>");
		out.println ("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:cs='Arial' w:hint='fareast'/>");
		out.println ("          <wx:font wx:val='標楷體'/>");
		out.println ("          <w:b/>");
		out.println ("          <w:sz w:val='32'/>");
		out.println ("          <w:sz-cs w:val='32'/>");
		out.println ("        </w:rPr>");
		out.println ("        <w:t>"+manager.ezGetString("SELECT Grade FROM Class WHERE ClassNo='"+map.get("depart_class")+"'")+"</w:t>");
		out.println ("      </w:r>");
		out.println ("      <w:r wsp:rsidR='00172D8E' wsp:rsidRPr='00786952'>");
		out.println ("        <w:rPr>");
		out.println ("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:cs='Arial'/>");
		out.println ("          <wx:font wx:val='標楷體'/>");
		out.println ("          <w:b/>");
		out.println ("          <w:sz w:val='32'/>");
		out.println ("          <w:sz-cs w:val='32'/>");
		out.println ("        </w:rPr>");
		out.println ("        <w:t>年級第</w:t>");
		out.println ("      </w:r>");
		out.println ("      <w:r>");
		out.println ("        <w:rPr>");
		out.println ("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:cs='Arial' w:hint='fareast'/>");
		out.println ("          <wx:font wx:val='標楷體'/>");
		out.println ("          <w:b/>");
		out.println ("          <w:sz w:val='32'/>");
		out.println ("          <w:sz-cs w:val='32'/>");
		out.println ("        </w:rPr>");
		out.println ("        <w:t>"+manager.ezGetString("SELECT school_term FROM ScoreHist WHERE student_no='"+map.get("student_no")+"' ORDER BY school_year, school_term DESC LIMIT 1")+"</w:t>");
		out.println ("      </w:r>");
		out.println ("      <w:r wsp:rsidR='00EE0B04' wsp:rsidRPr='00786952'>");
		out.println ("        <w:rPr>");
		out.println ("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:cs='Arial'/>");
		out.println ("          <wx:font wx:val='標楷體'/>");
		out.println ("          <w:b/>");
		out.println ("          <w:sz w:val='32'/>");
		out.println ("          <w:sz-cs w:val='32'/>");
		out.println ("        </w:rPr>");
		out.println ("        <w:t>學期課程，</w:t>");
		out.println ("      </w:r>");
		
		out.println ("      <w:r wsp:rsidR='00172D8E' wsp:rsidRPr='00786952'>");
		out.println ("        <w:rPr>");
		out.println ("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:cs='Arial'/>");
		out.println ("          <wx:font wx:val='標楷體'/>");
		out.println ("          <w:b/>");
		out.println ("          <w:sz w:val='32'/>");
		out.println ("          <w:sz-cs w:val='32'/>");
		out.println ("        </w:rPr>");
		out.println ("        <w:t>其入學資格經本校查核無誤</w:t>");
		out.println ("      </w:r>");
		out.println ("    </w:p>");
		
		
		
		
		out.println ("    <w:p wsp:rsidR='00172D8E' wsp:rsidRPr='00786952' wsp:rsidRDefault='00172D8E' wsp:rsidP='00900CEB'>");
		out.println ("      <w:pPr>");
		out.println ("        <w:spacing w:line='320' w:line-rule='exact'/>");
		out.println ("        <w:ind w:left-chars='400' w:left='960'/>");
		out.println ("        <w:rPr>");
		out.println ("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:cs='Arial'/>");
		out.println ("          <wx:font wx:val='標楷體'/>");
		out.println ("          <w:b/>");
		out.println ("          <w:sz w:val='32'/>");
		out.println ("          <w:sz-cs w:val='32'/>");
		out.println ("        </w:rPr>");
		out.println ("      </w:pPr>");
		out.println ("    </w:p>");
		
		
		out.println ("    <w:p wsp:rsidR='00172D8E' wsp:rsidRPr='00786952' wsp:rsidRDefault='00172D8E' wsp:rsidP='00172D8E'>");
		out.println ("      <w:r wsp:rsidRPr='00786952'>");
		out.println ("        <w:rPr>");
		out.println ("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:cs='Arial'/>");
		out.println ("          <wx:font wx:val='標楷體'/>");
		out.println ("          <w:b/>");
		out.println ("          <w:sz w:val='32'/>");
		out.println ("          <w:sz-cs w:val='32'/>");
		out.println ("        </w:rPr>");
		out.println ("        <w:t>		特此證明。附該生在校肄業成績表。</w:t>");
		out.println ("      </w:r>");
		out.println ("    </w:p>");
		
		
		out.println ("    <w:p wsp:rsidR='00172D8E' wsp:rsidRPr='00786952' wsp:rsidRDefault='00172D8E' wsp:rsidP='00172D8E'>");
		out.println ("      <w:pPr>");
		out.println ("        <w:rPr>");
		out.println ("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:cs='Arial'/>");
		out.println ("          <wx:font wx:val='標楷體'/>");
		out.println ("        </w:rPr>");
		out.println ("      </w:pPr>");
		out.println ("    </w:p>");
		out.println ("    <w:p wsp:rsidR='00172D8E' wsp:rsidRPr='00786952' wsp:rsidRDefault='00172D8E' wsp:rsidP='00172D8E'>");
		out.println ("      <w:pPr>");
		out.println ("        <w:rPr>");
		out.println ("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:cs='Arial'/>");
		out.println ("          <wx:font wx:val='標楷體'/>");
		out.println ("        </w:rPr>");
		out.println ("      </w:pPr>");
		out.println ("    </w:p>");
		out.println ("    <w:p wsp:rsidR='00172D8E' wsp:rsidRPr='00786952' wsp:rsidRDefault='00172D8E' wsp:rsidP='00172D8E'>");
		out.println ("      <w:pPr>");
		out.println ("        <w:rPr>");
		out.println ("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:cs='Arial'/>");
		out.println ("          <wx:font wx:val='標楷體'/>");
		out.println ("        </w:rPr>");
		out.println ("      </w:pPr>");
		out.println ("    </w:p>");
		out.println ("    <w:p wsp:rsidR='00172D8E' wsp:rsidRPr='00786952' wsp:rsidRDefault='00172D8E' wsp:rsidP='00172D8E'>");
		out.println ("      <w:pPr>");
		out.println ("        <w:rPr>");
		out.println ("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:cs='Arial'/>");
		out.println ("          <wx:font wx:val='標楷體'/>");
		out.println ("        </w:rPr>");
		out.println ("      </w:pPr>");
		out.println ("    </w:p>");
		out.println ("    <w:p wsp:rsidR='00172D8E' wsp:rsidRPr='00786952' wsp:rsidRDefault='00E40481' wsp:rsidP='00900CEB'>");
		out.println ("      <w:pPr>");
		out.println ("        <w:ind w:left-chars='1500' w:left='3600'/>");
		out.println ("        <w:jc w:val='both'/>");
		out.println ("        <w:rPr>");
		out.println ("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:cs='Arial'/>");
		out.println ("          <wx:font wx:val='標楷體'/>");
		out.println ("          <w:b/>");
		out.println ("          <w:sz w:val='32'/>");
		out.println ("          <w:sz-cs w:val='32'/>");
		out.println ("        </w:rPr>");
		out.println ("      </w:pPr>");
		out.println ("      <w:r wsp:rsidRPr='00786952'>");
		out.println ("        <w:rPr>");
		out.println ("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:cs='Arial' w:hint='fareast'/>");
		out.println ("          <wx:font wx:val='標楷體'/>");
		out.println ("          <w:b/>");
		out.println ("          <w:sz w:val='32'/>");
		out.println ("          <w:sz-cs w:val='32'/>");
		out.println ("        </w:rPr>");
		out.println ("        <w:t>教 務 長</w:t>");
		out.println ("      </w:r>");
		out.println ("    </w:p>");
		out.println ("    <w:p wsp:rsidR='00172D8E' wsp:rsidRPr='00786952' wsp:rsidRDefault='00172D8E' wsp:rsidP='00900CEB'>");
		out.println ("      <w:pPr>");
		out.println ("        <w:ind w:left-chars='1500' w:left='3600'/>");
		out.println ("        <w:jc w:val='both'/>");
		out.println ("        <w:rPr>");
		out.println ("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:cs='Arial'/>");
		out.println ("          <wx:font wx:val='標楷體'/>");
		out.println ("          <w:b/>");
		out.println ("          <w:sz w:val='32'/>");
		out.println ("          <w:sz-cs w:val='32'/>");
		out.println ("        </w:rPr>");
		out.println ("      </w:pPr>");
		out.println ("    </w:p>");
		out.println ("    <w:p wsp:rsidR='002A2750' wsp:rsidRPr='00786952' wsp:rsidRDefault='002A2750' wsp:rsidP='00900CEB'>");
		out.println ("      <w:pPr>");
		out.println ("        <w:ind w:left-chars='1500' w:left='3600'/>");
		out.println ("        <w:jc w:val='both'/>");
		out.println ("        <w:rPr>");
		out.println ("          <w:rFonts w:ascii='標楷體' w:fareast='���楷體' w:h-ansi='標楷體' w:cs='Arial'/>");
		out.println ("          <wx:font wx:val='標楷體'/>");
		out.println ("          <w:b/>");
		out.println ("          <w:sz w:val='32'/>");
		out.println ("          <w:sz-cs w:val='32'/>");
		out.println ("        </w:rPr>");
		out.println ("      </w:pPr>");
		out.println ("    </w:p>");
		out.println ("    <w:p wsp:rsidR='00172D8E' wsp:rsidRPr='00786952' wsp:rsidRDefault='00172D8E' wsp:rsidP='00900CEB'>");
		out.println ("      <w:pPr>");
		out.println ("        <w:ind w:left-chars='1500' w:left='3600'/>");
		out.println ("        <w:jc w:val='both'/>");
		out.println ("        <w:rPr>");
		out.println ("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:cs='Arial'/>");
		out.println ("          <wx:font wx:val='標楷體'/>");
		out.println ("          <w:b/>");
		out.println ("          <w:sz w:val='32'/>");
		out.println ("          <w:sz-cs w:val='32'/>");
		out.println ("        </w:rPr>");
		out.println ("      </w:pPr>");
		out.println ("      <w:r wsp:rsidRPr='00786952'>");
		out.println ("        <w:rPr>");
		out.println ("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:cs='Arial'/>");
		out.println ("          <wx:font wx:val='標楷體'/>");
		out.println ("          <w:b/>");
		out.println ("          <w:sz w:val='32'/>");
		out.println ("          <w:sz-cs w:val='32'/>");
		out.println ("        </w:rPr>");
		out.println ("        <w:t>校 長</w:t>");
		out.println ("      </w:r>");
		out.println ("    </w:p>");
		out.println ("    <w:p wsp:rsidR='002A2750' wsp:rsidRPr='00786952' wsp:rsidRDefault='002A2750' wsp:rsidP='002A2750'>");
		out.println ("      <w:pPr>");
		out.println ("        <w:rPr>");
		out.println ("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:cs='Arial'/>");
		out.println ("          <wx:font wx:val='標楷體'/>");
		out.println ("          <w:b/>");
		out.println ("          <w:sz w:val='32'/>");
		out.println ("          <w:sz-cs w:val='32'/>");
		out.println ("        </w:rPr>");
		out.println ("      </w:pPr>");
		out.println ("    </w:p>");
		out.println ("    <w:p wsp:rsidR='00EF6868' wsp:rsidRPr='00786952' wsp:rsidRDefault='00EF6868' wsp:rsidP='002A2750'>");
		out.println ("      <w:pPr>");
		out.println ("        <w:rPr>");
		out.println ("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:cs='Arial'/>");
		out.println ("          <wx:font wx:val='標楷體'/>");
		out.println ("          <w:b/>");
		out.println ("          <w:sz w:val='32'/>");
		out.println ("          <w:sz-cs w:val='32'/>");
		out.println ("        </w:rPr>");
		out.println ("      </w:pPr>");
		out.println ("    </w:p>");
		out.println ("    <w:p wsp:rsidR='006D2DFF' wsp:rsidRPr='00786952' wsp:rsidRDefault='006D2DFF' wsp:rsidP='002A2750'>");
		out.println ("      <w:pPr>");
		out.println ("        <w:rPr>");
		out.println ("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:cs='Arial'/>");
		out.println ("          <wx:font wx:val='標楷體'/>");
		out.println ("          <w:b/>");
		out.println ("          <w:sz w:val='32'/>");
		out.println ("          <w:sz-cs w:val='32'/>");
		out.println ("        </w:rPr>");
		out.println ("      </w:pPr>");
		out.println ("    </w:p>");
		out.println ("    <w:p wsp:rsidR='00D93956' wsp:rsidRPr='00786952' wsp:rsidRDefault='00D93956' wsp:rsidP='002A2750'>");
		out.println ("      <w:pPr>");
		out.println ("        <w:rPr>");
		out.println ("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:cs='Arial'/>");
		out.println ("          <wx:font wx:val='標楷體'/>");
		out.println ("          <w:b/>");
		out.println ("          <w:sz w:val='32'/>");
		out.println ("          <w:sz-cs w:val='32'/>");
		out.println ("        </w:rPr>");
		out.println ("      </w:pPr>");
		out.println ("    </w:p>");
		out.println ("    <w:p wsp:rsidR='00172D8E' wsp:rsidRPr='00786952' wsp:rsidRDefault='00172D8E' wsp:rsidP='002A2750'>");
		out.println ("      <w:pPr>");
		out.println ("        <w:jc w:val='center'/>");
		out.println ("        <w:rPr>");
		out.println ("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:cs='Arial'/>");
		out.println ("          <wx:font wx:val='標楷體'/>");
		out.println ("          <w:b/>");
		out.println ("          <w:spacing w:val='58'/>");
		out.println ("          <w:kern w:val='0'/>");
		out.println ("          <w:sz w:val='32'/>");
		out.println ("          <w:sz-cs w:val='32'/>");
		out.println ("        </w:rPr>");
		out.println ("      </w:pPr>");
		out.println ("      <w:r wsp:rsidRPr='00786952'>");
		out.println ("        <w:rPr>");
		out.println ("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:cs='Arial'/>");
		out.println ("          <wx:font wx:val='標楷體'/>");
		out.println ("          <w:b/>");
		out.println ("          <w:spacing w:val='13'/>");
		out.println ("          <w:kern w:val='0'/>");
		out.println ("          <w:sz w:val='32'/>");
		out.println ("          <w:sz-cs w:val='32'/>");
		out.println ("          <w:fitText w:val='1920' w:id='-928867327'/>");
		out.println ("        </w:rPr>");
		out.println ("        <w:t>中 華 民</w:t>");
		out.println ("      </w:r>");
		out.println ("      <w:r wsp:rsidRPr='00786952'>");
		out.println ("        <w:rPr>");
		out.println ("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:cs='Arial'/>");
		out.println ("          <wx:font wx:val='標楷體'/>");
		out.println ("          <w:b/>");
		out.println ("          <w:spacing w:val='1'/>");
		out.println ("          <w:kern w:val='0'/>");
		out.println ("          <w:sz w:val='32'/>");
		out.println ("          <w:sz-cs w:val='32'/>");
		out.println ("          <w:fitText w:val='1920' w:id='-928867327'/>");
		out.println ("        </w:rPr>");
		out.println ("        <w:t>國</w:t>");
		out.println ("      </w:r>");
		out.println ("      <w:r wsp:rsidR='00ED1F7F' wsp:rsidRPr='00786952'>");
		out.println ("        <w:rPr>");
		out.println ("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:cs='Arial' w:hint='fareast'/>");
		out.println ("          <wx:font wx:val='標楷體'/>");
		out.println ("          <w:b/>");
		out.println ("          <w:kern w:val='0'/>");
		out.println ("          <w:sz w:val='32'/>");
		out.println ("          <w:sz-cs w:val='32'/>");
		out.println ("        </w:rPr>");
		out.println ("        <w:t></w:t>");
		out.println ("      </w:r>");
		out.println ("      <w:r wsp:rsidR='00900CEB'>");
		out.println ("        <w:rPr>");
		out.println ("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:cs='Arial' w:hint='fareast'/>");
		out.println ("          <wx:font wx:val='標楷體'/>");
		out.println ("          <w:b/>");
		out.println ("          <w:spacing w:val='58'/>");
		out.println ("          <w:kern w:val='0'/>");
		out.println ("          <w:sz w:val='32'/>");
		out.println ("          <w:sz-cs w:val='32'/>");
		out.println ("        </w:rPr>");
		out.println ("        <w:t> "+(c1.get(Calendar.YEAR)-1911)+"</w:t>");
		out.println ("      </w:r>");
		out.println ("      <w:r wsp:rsidR='00BB08D6' wsp:rsidRPr='00786952'>");
		out.println ("        <w:rPr>");
		out.println ("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:cs='Arial'/>");
		out.println ("          <wx:font wx:val='標楷體'/>");
		out.println ("          <w:b/>");
		out.println ("          <w:spacing w:val='58'/>");
		out.println ("          <w:kern w:val='0'/>");
		out.println ("          <w:sz w:val='32'/>");
		out.println ("          <w:sz-cs w:val='32'/>");
		out.println ("        </w:rPr>");
		out.println ("        <w:t>年</w:t>");
		out.println ("      </w:r>");
		out.println ("      <w:r wsp:rsidR='00900CEB'>");
		out.println ("        <w:rPr>");
		out.println ("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:cs='Arial' w:hint='fareast'/>");
		out.println ("          <wx:font wx:val='標楷體'/>");
		out.println ("          <w:b/>");
		out.println ("          <w:spacing w:val='58'/>");
		out.println ("          <w:kern w:val='0'/>");
		out.println ("          <w:sz w:val='32'/>");
		out.println ("          <w:sz-cs w:val='32'/>");
		out.println ("        </w:rPr>");
		out.println ("        <w:t>"+(c1.get(Calendar.MONTH)+1)+"</w:t>");
		out.println ("      </w:r>");
		out.println ("      <w:r wsp:rsidR='00BB08D6' wsp:rsidRPr='00786952'>");
		out.println ("        <w:rPr>");
		out.println ("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:cs='Arial'/>");
		out.println ("          <wx:font wx:val='標楷體'/>");
		out.println ("          <w:b/>");
		out.println ("          <w:spacing w:val='58'/>");
		out.println ("          <w:kern w:val='0'/>");
		out.println ("          <w:sz w:val='32'/>");
		out.println ("          <w:sz-cs w:val='32'/>");
		out.println ("        </w:rPr>");
		out.println ("        <w:t>月</w:t>");
		out.println ("      </w:r>");
		out.println ("      <w:r wsp:rsidR='00900CEB'>");
		out.println ("        <w:rPr>");
		out.println ("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:cs='Arial' w:hint='fareast'/>");
		out.println ("          <wx:font wx:val='標楷體'/>");
		out.println ("          <w:b/>");
		out.println ("          <w:spacing w:val='58'/>");
		out.println ("          <w:kern w:val='0'/>");
		out.println ("          <w:sz w:val='32'/>");
		out.println ("          <w:sz-cs w:val='32'/>");
		out.println ("        </w:rPr>");
		out.println ("        <w:t>"+(c1.get(Calendar.DAY_OF_MONTH))+"</w:t>");
		out.println ("      </w:r>");
		out.println ("      <w:r wsp:rsidR='00BB08D6' wsp:rsidRPr='00786952'>");
		out.println ("        <w:rPr>");
		out.println ("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:cs='Arial'/>");
		out.println ("          <wx:font wx:val='標楷體'/>");
		out.println ("          <w:b/>");
		out.println ("          <w:spacing w:val='58'/>");
		out.println ("          <w:kern w:val='0'/>");
		out.println ("          <w:sz w:val='32'/>");
		out.println ("          <w:sz-cs w:val='32'/>");
		out.println ("        </w:rPr>");
		out.println ("        <w:t>日</w:t>");
		out.println ("      </w:r>");
		out.println ("    </w:p>");
		

		//2011-7-5，為符合2005-7-14更名
		out.println("<w:p wsp:rsidR='001B6D83' wsp:rsidRDefault='00946F4D' wsp:rsidP='001E3A0A'>");
		out.println("      <w:pPr>");
		out.println("        <w:spacing w:line='640' w:line-rule='exact'/>");
		out.println("        <w:ind w:left='20'/>");
		out.println("        <w:rPr>");
		out.println("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體'/>");
		out.println("          <wx:font wx:val='標楷體'/>");
		out.println("          <w:spacing w:val='60'/>");
		out.println("          <w:sz w:val='40'/>");
		out.println("        </w:rPr>");
		out.println("      </w:pPr>");
		out.println("      <w:r wsp:rsidRPr='00946F4D'>");
		out.println("        <w:rPr>");
		out.println("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體'/>");
		out.println("          <wx:font wx:val='標楷體'/>");
		out.println("          <w:noProof/>");
		out.println("          <w:spacing w:val='60'/>");
		out.println("          <w:sz w:val='44'/>");
		out.println("          <w:sz-cs w:val='44'/>");
		out.println("        </w:rPr>");
		out.println("        <w:pict>");
		out.println("          <v:shapetype id='_x0000_t202' coordsize='21600,21600' o:spt='202' path='m,l,21600r21600,l21600,xe'>");
		out.println("            <v:stroke joinstyle='miter'/>");
		out.println("            <v:path gradientshapeok='t' o:connecttype='rect'/>");
		out.println("          </v:shapetype>");
		out.println("          <v:shape id='_x0000_s1026' type='#_x0000_t202' style='position:absolute;top:-68;left:-1;text-align:left;margin-left:66pt;margin-top:58.85pt;width:280pt;height:35.5pt;z-index:1;mso-width-relative:margin;mso-height-relative:margin' stroked='f'>");
		out.println("            <v:textbox>");
		out.println("              <w:txbxContent>");
		out.println("                <w:p wsp:rsidR='006848C8' wsp:rsidRPr='006848C8' wsp:rsidRDefault='00826C44'>");
		out.println("                  <w:pPr>");
		out.println("                    <w:rPr>");
		out.println("                      <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體'/>");
		out.println("                      <wx:font wx:val='標楷體'/>");
		out.println("                    </w:rPr>");
		out.println("                  </w:pPr>");
		out.println("                  <w:r>");
		out.println("                    <w:rPr>");
		out.println("                      <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:hint='fareast'/>");
		out.println("                      <wx:font wx:val='標楷體'/>");
		out.println("                    </w:rPr>");
		out.println("                    <w:t>【◎本校全銜為中華學校財團法人中華科技大學】</w:t>");
		out.println("                  </w:r>");
		out.println("                </w:p>");
		out.println("              </w:txbxContent>");
		out.println("            </v:textbox>");
		out.println("          </v:shape>");
		out.println("        </w:pict>");
		out.println("      </w:r>");
		out.println("    </w:p>");
		
		out.println ("    <w:sectPr wsp:rsidR='00172D8E' wsp:rsidRPr='00786952' wsp:rsidSect='002C2F1C'>");
		out.println ("      <w:pgSz w:w='11906' w:h='16838'/>");
		out.println ("      <w:pgMar w:top='1440' w:right='1800' w:bottom='1440' w:left='1800' w:header='851' w:footer='992' w:gutter='0'/>");
		out.println ("      <w:cols w:space='425'/>");
		out.println ("      <w:docGrid w:type='lines' w:line-pitch='360'/>");
		out.println ("    </w:sectPr>");
		out.println ("  </w:body>");
		out.println ("</w:wordDocument>");
		
		
		
		
		
		
		
		
		
		
		return null;
	}
}