package tw.edu.chit.struts.action.report.registration.csgroup;

import java.io.PrintWriter;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.Map;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import tw.edu.chit.service.CourseManager;
import tw.edu.chit.struts.action.BaseAction;

public class Diploma4Csgroup extends BaseAction{

public ActionForward execute(ActionMapping mapping, ActionForm form, HttpServletRequest request, HttpServletResponse response)throws Exception {	
		
		response.setContentType("text/xml; charset=UTF-8");		
		CourseManager manager = (CourseManager) getBean("courseManager");		
		PrintWriter out=response.getWriter();		
		Date date=new Date();
		response.setHeader("Content-disposition","attachment;filename=Diploma4Csgroup"+date.getTime()+".doc");		
		Calendar now=Calendar.getInstance();
		now.setTime(date);
		out.println("<?xml version='1.0' encoding='UTF-8' standalone='yes'?>");
		out.println("<?mso-application progid='Word.Document'?>");
		out.println("<w:wordDocument xmlns:aml='http://schemas.microsoft.com/aml/2001/core' xmlns:dt='uuid:C2F41010-65B3-11d1-A29F-00AA00C14882' xmlns:ve='http://schemas.openxmlformats.org/markup-compatibility/2006' xmlns:o='urn:schemas-microsoft-com:office:office' xmlns:v='urn:schemas-microsoft-com:vml' xmlns:w10='urn:schemas-microsoft-com:office:word' xmlns:w='http://schemas.microsoft.com/office/word/2003/wordml' xmlns:wx='http://schemas.microsoft.com/office/word/2003/auxHint' xmlns:wsp='http://schemas.microsoft.com/office/word/2003/wordml/sp2' xmlns:sl='http://schemas.microsoft.com/schemaLibrary/2003/core' w:macrosPresent='no' w:embeddedObjPresent='no' w:ocxPresent='no' xml:space='preserve'>");
		out.println("  <w:ignoreSubtree w:val='http://schemas.microsoft.com/office/word/2003/wordml/sp2'/>");
		out.println("  <o:DocumentProperties>");
		out.println("    <o:Author>蕭國裕</o:Author>");
		out.println("    <o:LastAuthor>蕭國裕</o:LastAuthor>");
		out.println("    <o:Revision>2</o:Revision>");
		out.println("    <o:TotalTime>4</o:TotalTime>");
		out.println("    <o:LastPrinted>2011-06-21T04:13:00Z</o:LastPrinted>");
		out.println("    <o:Created>2011-06-22T01:18:00Z</o:Created>");
		out.println("    <o:LastSaved>2011-06-22T01:18:00Z</o:LastSaved>");
		out.println("    <o:Pages>1</o:Pages>");
		out.println("    <o:Words>20</o:Words>");
		out.println("    <o:Characters>116</o:Characters>");
		out.println("    <o:Company>chit</o:Company>");
		out.println("    <o:Lines>1</o:Lines>");
		out.println("    <o:Paragraphs>1</o:Paragraphs>");
		out.println("    <o:CharactersWithSpaces>135</o:CharactersWithSpaces>");
		out.println("    <o:Version>12</o:Version>");
		out.println("  </o:DocumentProperties>");
		out.println("  <w:fonts>");
		out.println("    <w:defaultFonts w:ascii='Times New Roman' w:fareast='新細明體' w:h-ansi='Times New Roman' w:cs='Times New Roman'/>");
		out.println("    <w:font w:name='Times New Roman'>");
		out.println("      <w:panose-1 w:val='02020603050405020304'/>");
		out.println("      <w:charset w:val='00'/>");
		out.println("      <w:family w:val='Roman'/>");
		out.println("      <w:pitch w:val='variable'/>");
		out.println("      <w:sig w:usb-0='20002A87' w:usb-1='80000000' w:usb-2='00000008' w:usb-3='00000000' w:csb-0='000001FF' w:csb-1='00000000'/>");
		out.println("    </w:font>");
		out.println("    <w:font w:name='Arial'>");
		out.println("      <w:panose-1 w:val='020B0604020202020204'/>");
		out.println("      <w:charset w:val='00'/>");
		out.println("      <w:family w:val='Swiss'/>");
		out.println("      <w:pitch w:val='variable'/>");
		out.println("      <w:sig w:usb-0='20002A87' w:usb-1='80000000' w:usb-2='00000008' w:usb-3='00000000' w:csb-0='000001FF' w:csb-1='00000000'/>");
		out.println("    </w:font>");
		out.println("    <w:font w:name='新細明體'>");
		out.println("      <w:altName w:val='PMingLiU'/>");
		out.println("      <w:panose-1 w:val='02020300000000000000'/>");
		out.println("      <w:charset w:val='88'/>");
		out.println("      <w:family w:val='Roman'/>");
		out.println("      <w:pitch w:val='variable'/>");
		out.println("      <w:sig w:usb-0='00000003' w:usb-1='080E0000' w:usb-2='00000016' w:usb-3='00000000' w:csb-0='00100001' w:csb-1='00000000'/>");
		out.println("    </w:font>");
		out.println("    <w:font w:name='Cambria Math'>");
		out.println("      <w:panose-1 w:val='02040503050406030204'/>");
		out.println("      <w:charset w:val='00'/>");
		out.println("      <w:family w:val='Roman'/>");
		out.println("      <w:pitch w:val='variable'/>");
		out.println("      <w:sig w:usb-0='A00002EF' w:usb-1='420020EB' w:usb-2='00000000' w:usb-3='00000000' w:csb-0='0000009F' w:csb-1='00000000'/>");
		out.println("    </w:font>");
		out.println("    <w:font w:name='標楷體'>");
		out.println("      <w:panose-1 w:val='03000509000000000000'/>");
		out.println("      <w:charset w:val='88'/>");
		out.println("      <w:family w:val='Script'/>");
		out.println("      <w:pitch w:val='fixed'/>");
		out.println("      <w:sig w:usb-0='00000003' w:usb-1='080E0000' w:usb-2='00000016' w:usb-3='00000000' w:csb-0='00100001' w:csb-1='00000000'/>");
		out.println("    </w:font>");
		out.println("    <w:font w:name='華康特粗楷體'>");
		out.println("      <w:altName w:val='Arial Unicode MS'/>");
		out.println("      <w:charset w:val='88'/>");
		out.println("      <w:family w:val='Script'/>");
		out.println("      <w:pitch w:val='fixed'/>");
		out.println("      <w:sig w:usb-0='00000000' w:usb-1='28091800' w:usb-2='00000016' w:usb-3='00000000' w:csb-0='00100000' w:csb-1='00000000'/>");
		out.println("    </w:font>");
		out.println("    <w:font w:name='@標楷體'>");
		out.println("      <w:panose-1 w:val='03000509000000000000'/>");
		out.println("      <w:charset w:val='88'/>");
		out.println("      <w:family w:val='Script'/>");
		out.println("      <w:pitch w:val='fixed'/>");
		out.println("      <w:sig w:usb-0='00000003' w:usb-1='080E0000' w:usb-2='00000016' w:usb-3='00000000' w:csb-0='00100001' w:csb-1='00000000'/>");
		out.println("    </w:font>");
		out.println("    <w:font w:name='@新細明體'>");
		out.println("      <w:panose-1 w:val='02020300000000000000'/>");
		out.println("      <w:charset w:val='88'/>");
		out.println("      <w:family w:val='Roman'/>");
		out.println("      <w:pitch w:val='variable'/>");
		out.println("      <w:sig w:usb-0='00000003' w:usb-1='080E0000' w:usb-2='00000016' w:usb-3='00000000' w:csb-0='00100001' w:csb-1='00000000'/>");
		out.println("    </w:font>");
		out.println("    <w:font w:name='@華康特粗楷體'>");
		out.println("      <w:charset w:val='88'/>");
		out.println("      <w:family w:val='Script'/>");
		out.println("      <w:pitch w:val='fixed'/>");
		out.println("      <w:sig w:usb-0='00000000' w:usb-1='28091800' w:usb-2='00000016' w:usb-3='00000000' w:csb-0='00100000' w:csb-1='00000000'/>");
		out.println("    </w:font>");
		out.println("  </w:fonts>");
		out.println("  <w:styles>");
		out.println("    <w:versionOfBuiltInStylenames w:val='7'/>");
		out.println("    <w:latentStyles w:defLockedState='off' w:latentStyleCount='267'>");
		out.println("      <w:lsdException w:name='Normal'/>");
		out.println("      <w:lsdException w:name='heading 1'/>");
		out.println("      <w:lsdException w:name='heading 2'/>");
		out.println("      <w:lsdException w:name='heading 3'/>");
		out.println("      <w:lsdException w:name='heading 4'/>");
		out.println("      <w:lsdException w:name='heading 5'/>");
		out.println("      <w:lsdException w:name='heading 6'/>");
		out.println("      <w:lsdException w:name='heading 7'/>");
		out.println("      <w:lsdException w:name='heading 8'/>");
		out.println("      <w:lsdException w:name='heading 9'/>");
		out.println("      <w:lsdException w:name='caption'/>");
		out.println("      <w:lsdException w:name='Title'/>");
		out.println("      <w:lsdException w:name='Subtitle'/>");
		out.println("      <w:lsdException w:name='Strong'/>");
		out.println("      <w:lsdException w:name='Emphasis'/>");
		out.println("      <w:lsdException w:name='No Spacing'/>");
		out.println("      <w:lsdException w:name='List Paragraph'/>");
		out.println("      <w:lsdException w:name='Quote'/>");
		out.println("      <w:lsdException w:name='Intense Quote'/>");
		out.println("      <w:lsdException w:name='Subtle Emphasis'/>");
		out.println("      <w:lsdException w:name='Intense Emphasis'/>");
		out.println("      <w:lsdException w:name='Subtle Reference'/>");
		out.println("      <w:lsdException w:name='Intense Reference'/>");
		out.println("      <w:lsdException w:name='Book Title'/>");
		out.println("      <w:lsdException w:name='TOC Heading'/>");
		out.println("    </w:latentStyles>");
		out.println("    <w:style w:type='paragraph' w:default='on' w:styleId='a'>");
		out.println("      <w:name w:val='Normal'/>");
		out.println("      <wx:uiName wx:val='內文'/>");
		out.println("      <w:rsid w:val='002958BE'/>");
		out.println("      <w:rPr>");
		out.println("        <w:rFonts w:ascii='新細明體' w:h-ansi='新細明體' w:cs='新細明體'/>");
		out.println("        <wx:font wx:val='新細明體'/>");
		out.println("        <w:sz w:val='24'/>");
		out.println("        <w:sz-cs w:val='24'/>");
		out.println("        <w:lang w:val='EN-US' w:fareast='ZH-TW' w:bidi='AR-SA'/>");
		out.println("      </w:rPr>");
		out.println("    </w:style>");
		out.println("    <w:style w:type='character' w:default='on' w:styleId='a0'>");
		out.println("      <w:name w:val='Default Paragraph Font'/>");
		out.println("      <wx:uiName wx:val='預設段落字型'/>");
		out.println("    </w:style>");
		out.println("    <w:style w:type='table' w:default='on' w:styleId='a1'>");
		out.println("      <w:name w:val='Normal Table'/>");
		out.println("      <wx:uiName wx:val='表格內文'/>");
		out.println("      <w:rPr>");
		out.println("        <wx:font wx:val='Times New Roman'/>");
		out.println("        <w:lang w:val='EN-US' w:fareast='ZH-TW' w:bidi='AR-SA'/>");
		out.println("      </w:rPr>");
		out.println("      <w:tblPr>");
		out.println("        <w:tblInd w:w='0' w:type='dxa'/>");
		out.println("        <w:tblCellMar>");
		out.println("          <w:top w:w='0' w:type='dxa'/>");
		out.println("          <w:left w:w='108' w:type='dxa'/>");
		out.println("          <w:bottom w:w='0' w:type='dxa'/>");
		out.println("          <w:right w:w='108' w:type='dxa'/>");
		out.println("        </w:tblCellMar>");
		out.println("      </w:tblPr>");
		out.println("    </w:style>");
		out.println("    <w:style w:type='list' w:default='on' w:styleId='a2'>");
		out.println("      <w:name w:val='No List'/>");
		out.println("      <wx:uiName wx:val='無清單'/>");
		out.println("    </w:style>");
		out.println("    <w:style w:type='paragraph' w:styleId='Web'>");
		out.println("      <w:name w:val='Normal (Web)'/>");
		out.println("      <wx:uiName wx:val='內文 (Web)'/>");
		out.println("      <w:basedOn w:val='a'/>");
		out.println("      <w:rsid w:val='002958BE'/>");
		out.println("      <w:pPr>");
		out.println("        <w:spacing w:before='100' w:before-autospacing='on' w:after='100' w:after-autospacing='on'/>");
		out.println("      </w:pPr>");
		out.println("      <w:rPr>");
		out.println("        <wx:font wx:val='新細明體'/>");
		out.println("      </w:rPr>");
		out.println("    </w:style>");
		out.println("    <w:style w:type='paragraph' w:styleId='a3'>");
		out.println("      <w:name w:val='header'/>");
		out.println("      <wx:uiName wx:val='頁首'/>");
		out.println("      <w:basedOn w:val='a'/>");
		out.println("      <w:link w:val='a4'/>");
		out.println("      <w:rsid w:val='00871D92'/>");
		out.println("      <w:pPr>");
		out.println("        <w:tabs>");
		out.println("          <w:tab w:val='center' w:pos='4153'/>");
		out.println("          <w:tab w:val='right' w:pos='8306'/>");
		out.println("        </w:tabs>");
		out.println("        <w:snapToGrid w:val='off'/>");
		out.println("      </w:pPr>");
		out.println("      <w:rPr>");
		out.println("        <wx:font wx:val='新細明體'/>");
		out.println("        <w:sz w:val='20'/>");
		out.println("        <w:sz-cs w:val='20'/>");
		out.println("      </w:rPr>");
		out.println("    </w:style>");
		out.println("    <w:style w:type='character' w:styleId='a4'>");
		out.println("      <w:name w:val='頁首 字元'/>");
		out.println("      <w:basedOn w:val='a0'/>");
		out.println("      <w:link w:val='a3'/>");
		out.println("      <w:rsid w:val='00871D92'/>");
		out.println("      <w:rPr>");
		out.println("        <w:rFonts w:ascii='新細明體' w:h-ansi='新細明體' w:cs='新細明體'/>");
		out.println("      </w:rPr>");
		out.println("    </w:style>");
		out.println("    <w:style w:type='paragraph' w:styleId='a5'>");
		out.println("      <w:name w:val='footer'/>");
		out.println("      <wx:uiName wx:val='頁尾'/>");
		out.println("      <w:basedOn w:val='a'/>");
		out.println("      <w:link w:val='a6'/>");
		out.println("      <w:rsid w:val='00871D92'/>");
		out.println("      <w:pPr>");
		out.println("        <w:tabs>");
		out.println("          <w:tab w:val='center' w:pos='4153'/>");
		out.println("          <w:tab w:val='right' w:pos='8306'/>");
		out.println("        </w:tabs>");
		out.println("        <w:snapToGrid w:val='off'/>");
		out.println("      </w:pPr>");
		out.println("      <w:rPr>");
		out.println("        <wx:font wx:val='新細明體'/>");
		out.println("        <w:sz w:val='20'/>");
		out.println("        <w:sz-cs w:val='20'/>");
		out.println("      </w:rPr>");
		out.println("    </w:style>");
		out.println("    <w:style w:type='character' w:styleId='a6'>");
		out.println("      <w:name w:val='頁尾 字元'/>");
		out.println("      <w:basedOn w:val='a0'/>");
		out.println("      <w:link w:val='a5'/>");
		out.println("      <w:rsid w:val='00871D92'/>");
		out.println("      <w:rPr>");
		out.println("        <w:rFonts w:ascii='新細明體' w:h-ansi='新細明體' w:cs='新細明體'/>");
		out.println("      </w:rPr>");
		out.println("    </w:style>");
		out.println("    <w:style w:type='paragraph' w:styleId='a7'>");
		out.println("      <w:name w:val='Balloon Text'/>");
		out.println("      <wx:uiName wx:val='註解方塊文字'/>");
		out.println("      <w:basedOn w:val='a'/>");
		out.println("      <w:rsid w:val='00132B0D'/>");
		out.println("      <w:rPr>");
		out.println("        <w:rFonts w:ascii='Arial' w:h-ansi='Arial' w:cs='Times New Roman'/>");
		out.println("        <wx:font wx:val='Arial'/>");
		out.println("        <w:sz w:val='18'/>");
		out.println("        <w:sz-cs w:val='18'/>");
		out.println("      </w:rPr>");
		out.println("    </w:style>");
		out.println("  </w:styles>");
		out.println("  <w:shapeDefaults>");
		out.println("    <o:shapedefaults v:ext='edit' spidmax='8194'/>");
		out.println("    <o:shapelayout v:ext='edit'>");
		out.println("      <o:idmap v:ext='edit' data='1'/>");
		out.println("    </o:shapelayout>");
		out.println("  </w:shapeDefaults>");
		out.println("  <w:bgPict>");
		out.println("    <w:background w:bgcolor='white'/>");
		out.println("  </w:bgPict>");
		out.println("  <w:docPr>");
		out.println("    <w:view w:val='print'/>");
		out.println("    <w:zoom w:percent='100'/>");
		out.println("    <w:bordersDontSurroundHeader/>");
		out.println("    <w:bordersDontSurroundFooter/>");
		out.println("    <w:proofState w:spelling='clean'/>");
		out.println("    <w:stylePaneFormatFilter w:val='3F01'/>");
		out.println("    <w:defaultTabStop w:val='480'/>");
		out.println("    <w:characterSpacingControl w:val='DontCompress'/>");
		out.println("    <w:webPageEncoding w:val='utf-8'/>");
		out.println("    <w:optimizeForBrowser/>");
		out.println("    <w:validateAgainstSchema/>");
		out.println("    <w:saveInvalidXML w:val='off'/>");
		out.println("    <w:ignoreMixedContent w:val='off'/>");
		out.println("    <w:alwaysShowPlaceholderText w:val='off'/>");
		out.println("    <w:hdrShapeDefaults>");
		out.println("      <o:shapedefaults v:ext='edit' spidmax='8194'/>");
		out.println("    </w:hdrShapeDefaults>");
		out.println("    <w:footnotePr>");
		out.println("      <w:footnote w:type='separator'>");
		out.println("        <w:p wsp:rsidR='003956F9' wsp:rsidRDefault='003956F9' wsp:rsidP='00871D92'>");
		out.println("          <w:r>");
		out.println("            <w:separator/>");
		out.println("          </w:r>");
		out.println("        </w:p>");
		out.println("      </w:footnote>");
		out.println("      <w:footnote w:type='continuation-separator'>");
		out.println("        <w:p wsp:rsidR='003956F9' wsp:rsidRDefault='003956F9' wsp:rsidP='00871D92'>");
		out.println("          <w:r>");
		out.println("            <w:continuationSeparator/>");
		out.println("          </w:r>");
		out.println("        </w:p>");
		out.println("      </w:footnote>");
		out.println("    </w:footnotePr>");
		out.println("    <w:endnotePr>");
		out.println("      <w:endnote w:type='separator'>");
		out.println("        <w:p wsp:rsidR='003956F9' wsp:rsidRDefault='003956F9' wsp:rsidP='00871D92'>");
		out.println("          <w:r>");
		out.println("            <w:separator/>");
		out.println("          </w:r>");
		out.println("        </w:p>");
		out.println("      </w:endnote>");
		out.println("      <w:endnote w:type='continuation-separator'>");
		out.println("        <w:p wsp:rsidR='003956F9' wsp:rsidRDefault='003956F9' wsp:rsidP='00871D92'>");
		out.println("          <w:r>");
		out.println("            <w:continuationSeparator/>");
		out.println("          </w:r>");
		out.println("        </w:p>");
		out.println("      </w:endnote>");
		out.println("    </w:endnotePr>");
		out.println("    <w:compat>");
		out.println("      <w:breakWrappedTables/>");
		out.println("      <w:useFELayout/>");
		out.println("    </w:compat>");
		out.println("    <wsp:rsids>");
		out.println("      <wsp:rsidRoot wsp:val='00590795'/>");
		out.println("      <wsp:rsid wsp:val='0005604F'/>");
		out.println("      <wsp:rsid wsp:val='00062088'/>");
		out.println("      <wsp:rsid wsp:val='000C6181'/>");
		out.println("      <wsp:rsid wsp:val='00132B0D'/>");
		out.println("      <wsp:rsid wsp:val='00146E1E'/>");
		out.println("      <wsp:rsid wsp:val='0015077F'/>");
		out.println("      <wsp:rsid wsp:val='001B10AA'/>");
		out.println("      <wsp:rsid wsp:val='001D521A'/>");
		out.println("      <wsp:rsid wsp:val='001E6161'/>");
		out.println("      <wsp:rsid wsp:val='001F7108'/>");
		out.println("      <wsp:rsid wsp:val='002838E0'/>");
		out.println("      <wsp:rsid wsp:val='002958BE'/>");
		out.println("      <wsp:rsid wsp:val='00314F09'/>");
		out.println("      <wsp:rsid wsp:val='00352928'/>");
		out.println("      <wsp:rsid wsp:val='003956F9'/>");
		out.println("      <wsp:rsid wsp:val='00451D93'/>");
		out.println("      <wsp:rsid wsp:val='0057015B'/>");
		out.println("      <wsp:rsid wsp:val='00590795'/>");
		out.println("      <wsp:rsid wsp:val='006018BB'/>");
		out.println("      <wsp:rsid wsp:val='00707336'/>");
		out.println("      <wsp:rsid wsp:val='007373D2'/>");
		out.println("      <wsp:rsid wsp:val='00783740'/>");
		out.println("      <wsp:rsid wsp:val='007A7ADE'/>");
		out.println("      <wsp:rsid wsp:val='007C5DD4'/>");
		out.println("      <wsp:rsid wsp:val='0086324B'/>");
		out.println("      <wsp:rsid wsp:val='00871D92'/>");
		out.println("      <wsp:rsid wsp:val='00A755CD'/>");
		out.println("      <wsp:rsid wsp:val='00B970BB'/>");
		out.println("      <wsp:rsid wsp:val='00C17EEA'/>");
		out.println("      <wsp:rsid wsp:val='00C448FF'/>");
		out.println("      <wsp:rsid wsp:val='00D64703'/>");
		out.println("      <wsp:rsid wsp:val='00DE0CB4'/>");
		out.println("      <wsp:rsid wsp:val='00DF13D8'/>");
		out.println("      <wsp:rsid wsp:val='00DF1632'/>");
		out.println("      <wsp:rsid wsp:val='00E04FA7'/>");
		out.println("    </wsp:rsids>");
		out.println("  </w:docPr>");
		
		HttpSession session = request.getSession(false);
		List list=new ArrayList();
		
		//來自學籍管理
		if(session.getAttribute("relult")==null){
			if(session.getAttribute("students")!=null){			
				
				List students=(List)session.getAttribute("students");
				StringBuilder sb=new StringBuilder();
				for(int i=0; i<students.size(); i++){
					
					sb.append(   "'"+((Map)students.get(i)).get("student_no")+"', ");
				}
				
				
				if(sb.length()>5){
					sb.delete(sb.length()-2, sb.length());
				}
				
				List stds=manager.ezGetBy("SELECT st.*, c.*, c5.name as schoolName, c51.name as deptName FROM " +
						"((stmd st LEFT JOIN Class c ON st.depart_class=c.ClassNo)LEFT JOIN " +
						"code5 c5 ON c5.idno=c.SchoolNo)LEFT JOIN code5 c51 ON c51.idno=c.DeptNo WHERE " +
						"c5.category='School' AND c51.category='Dept' AND st.student_no IN("+sb+")");
				
				Map std;
				List biGroup=new ArrayList();//大圈
				for(int i=0; i<stds.size(); i++){
					std=manager.ezGetMap("SELECT st.*, c.*, c5.name as schoolName, c51.name as deptName FROM " +
					"((stmd st LEFT JOIN Class c ON st.depart_class=c.ClassNo)LEFT JOIN " +
					"code5 c5 ON c5.idno=c.SchoolNo)LEFT JOIN code5 c51 ON c51.idno=c.DeptNo WHERE " +
					"c5.category='School' AND c51.category='Dept' AND st.student_no='"+((Map)stds.get(i)).get("student_no")+"'");
					std.put("myGroup", manager.CsGroup4One( ((Map)stds.get(i)).get("student_no").toString()  , std, false));
					biGroup.add(std);
				}
				
				List myGroup;
				
				float opt1;
				float opt2;
				float optOut;
				
				float MyOpt1;
				float MyOpt2;
				float MyOptOut;
				
				
				
				Map map;
				for(int i=0; i<biGroup.size(); i++){
					
					myGroup=(List)((Map)biGroup.get(i)).get("myGroup");
					for(int j=0; j<myGroup.size(); j++){
						opt1=Float.parseFloat(((Map)myGroup.get(j)).get("major").toString());
						opt2=Float.parseFloat(((Map)myGroup.get(j)).get("minor").toString());
						optOut=Float.parseFloat(((Map)myGroup.get(j)).get("outdept").toString());
						
						MyOpt1=Float.parseFloat(((Map)myGroup.get(j)).get("opt1").toString());
						MyOpt2=Float.parseFloat(((Map)myGroup.get(j)).get("opt2").toString());
						MyOptOut=Float.parseFloat(((Map)myGroup.get(j)).get("optOut").toString());	
						
						if(MyOpt1>0 || MyOpt2>0 || MyOptOut>0){					
							((Map)myGroup.get(j)).put("student_no", ((Map)biGroup.get(i)).get("student_no"));
							((Map)myGroup.get(j)).put("student_name", ((Map)biGroup.get(i)).get("student_name"));					
												
							//符合資格

							if(MyOpt1>=opt1 && MyOpt2>=opt2 && MyOptOut>=optOut){
								((Map)myGroup.get(j)).put("igot", true);
								list.add(myGroup.get(j));
							}
						
							
						}
					}			
				}
			}
		}else{
			//來自 資格審查
			
			list=(List)session.getAttribute("relult");
		}
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		out.println("  <w:body>");
		Map map;
		//float credit=0;
		for(int i=0; i<list.size(); i++){
			//System.out.println(list.get(i));
			map=manager.ezGetMap("SELECT d.school_name, d.fname, s.birthday, s.idno FROM " +
					"stmd s, Class c LEFT OUTER JOIN dept d ON d.no=c.Dept " +
					"WHERE s.depart_class=c.ClassNo AND s.student_no='"+((Map)list.get(i)).get("student_no")+"'");
			
			
			//System.out.println(map);
			out.println("    <w:p wsp:rsidR='006018BB' wsp:rsidRDefault='006018BB' wsp:rsidP='00132B0D'>");
			out.println("      <w:pPr>");
			out.println("        <w:spacing w:after='360'/>");
			out.println("      </w:pPr>");
			out.println("      <w:r>");
			out.println("        <w:rPr>");
			out.println("          <w:rFonts w:hint='fareast'/>");
			out.println("        </w:rPr>");
			out.println("        <w:br/>");
			out.println("      </w:r>");
			out.println("      <w:r>");
			out.println("        <w:rPr>");
			out.println("          <w:rFonts w:hint='fareast'/>");
			out.println("        </w:rPr>");
			out.println("        <w:br/>");
			out.println("      </w:r>");
			out.println("      <w:r>");
			out.println("        <w:rPr>");
			out.println("          <w:rFonts w:hint='fareast'/>");
			out.println("        </w:rPr>");
			out.println("        <w:br/>");
			out.println("      </w:r>");
			out.println("      <w:r>");
			out.println("        <w:rPr>");
			out.println("          <w:rFonts w:hint='fareast'/>");
			out.println("        </w:rPr>");
			out.println("        <w:br/>");
			out.println("      </w:r>");
			out.println("      <w:r>");
			out.println("        <w:rPr>");
			out.println("          <w:rFonts w:hint='fareast'/>");
			out.println("        </w:rPr>");
			out.println("        <w:br/>");
			out.println("      </w:r>");
			out.println("    </w:p>");
			out.println("    <w:p wsp:rsidR='006018BB' wsp:rsidRDefault='006018BB'>");
			out.println("      <w:pPr>");
			out.println("        <w:pStyle w:val='Web'/>");
			out.println("        <w:jc w:val='center'/>");
			out.println("      </w:pPr>");
			out.println("      <w:r>");
			out.println("        <w:rPr>");
			out.println("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:hint='fareast'/>");
			out.println("          <wx:font wx:val='標楷體'/>");
			out.println("          <w:b/>");
			out.println("          <w:b-cs/>");
			out.println("          <w:sz w:val='60'/>");
			out.println("          <w:sz-cs w:val='60'/>");
			out.println("        </w:rPr>");
			out.println("        <w:t>學程證明書</w:t>");
			out.println("      </w:r>");
			out.println("    </w:p>");
			out.println("    <w:p wsp:rsidR='00DF1632' wsp:rsidRPr='00DF1632' wsp:rsidRDefault='00DF1632' wsp:rsidP='00DF1632'>");
			out.println("      <w:pPr>");
			out.println("        <w:jc w:val='right'/>");
			out.println("        <w:rPr>");
			out.println("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體'/>");
			out.println("          <wx:font wx:val='標楷體'/>");
			out.println("          <w:b/>");
			out.println("          <w:b-cs/>");
			out.println("          <w:spacing w:val='6'/>");
			out.println("          <w:sz w:val='22'/>");
			out.println("          <w:sz-cs w:val='22'/>");
			out.println("        </w:rPr>");
			out.println("      </w:pPr>");
			out.println("      <w:r wsp:rsidRPr='00DF1632'>");
			out.println("        <w:rPr>");
			out.println("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:hint='fareast'/>");
			out.println("          <wx:font wx:val='標楷體'/>");
			out.println("          <w:b/>");
			out.println("          <w:b-cs/>");
			out.println("          <w:spacing w:val='6'/>");
			out.println("          <w:sz w:val='22'/>");
			out.println("          <w:sz-cs w:val='22'/>");
			out.println("        </w:rPr>");
			out.println("        <w:t>華科大教程字第</w:t>");
			out.println("      </w:r>");
			out.println("      <w:r>");
			out.println("        <w:rPr>");
			out.println("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:hint='fareast'/>");
			out.println("          <wx:font wx:val='標楷體'/>");
			out.println("          <w:b/>");
			out.println("          <w:b-cs/>");
			out.println("          <w:spacing w:val='6'/>");
			out.println("          <w:sz w:val='22'/>");
			out.println("          <w:sz-cs w:val='22'/>");
			out.println("        </w:rPr>");
			//out.println("        <w:t></w:t>");
			out.println("      </w:r>");
			out.println("      <w:proofErr w:type='spellStart'/>");
			out.println("      <w:r>");
			out.println("        <w:rPr>");
			out.println("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:hint='fareast'/>");
			out.println("          <wx:font wx:val='標楷體'/>");
			out.println("          <w:b/>");
			out.println("          <w:b-cs/>");
			out.println("          <w:spacing w:val='6'/>");
			out.println("          <w:sz w:val='22'/>");
			out.println("          <w:sz-cs w:val='22'/>");
			out.println("        </w:rPr>");
			out.println("        <w:t>"+((Map)list.get(i)).get("student_no")+"</w:t>");
			out.println("      </w:r>");
			out.println("      <w:proofErr w:type='spellEnd'/>");
			out.println("      <w:r wsp:rsidRPr='00DF1632'>");
			out.println("        <w:rPr>");
			out.println("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體'/>");
			out.println("          <wx:font wx:val='標楷體'/>");
			out.println("          <w:b/>");
			out.println("          <w:b-cs/>");
			out.println("          <w:spacing w:val='6'/>");
			out.println("          <w:sz w:val='22'/>");
			out.println("          <w:sz-cs w:val='22'/>");
			out.println("        </w:rPr>");
			out.println("        <w:t>號</w:t>");
			out.println("      </w:r>");
			out.println("    </w:p>");
			out.println("    <w:p wsp:rsidR='006018BB' wsp:rsidRDefault='00DF1632' wsp:rsidP='00DF1632'>");
			out.println("      <w:pPr>");
			out.println("        <w:jc w:val='right'/>");
			out.println("      </w:pPr>");
			out.println("      <w:r wsp:rsidRPr='00DF1632'>");
			out.println("        <w:rPr>");
			out.println("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:hint='fareast'/>");
			out.println("          <wx:font wx:val='標楷體'/>");
			out.println("          <w:b/>");
			out.println("          <w:b-cs/>");
			out.println("          <w:spacing w:val='6'/>");
			out.println("          <w:sz w:val='22'/>");
			out.println("          <w:sz-cs w:val='22'/>");
			out.println("        </w:rPr>");
			out.println("        <w:t>身分證字號</w:t>");
			out.println("      </w:r>");
			out.println("      <w:r>");
			out.println("        <w:rPr>");
			out.println("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:hint='fareast'/>");
			out.println("          <wx:font wx:val='標楷體'/>");
			out.println("          <w:b/>");
			out.println("          <w:b-cs/>");
			out.println("          <w:spacing w:val='6'/>");
			out.println("          <w:sz w:val='22'/>");
			out.println("          <w:sz-cs w:val='22'/>");
			out.println("        </w:rPr>");
			//out.println("        <w:t>$</w:t>");
			out.println("      </w:r>");
			out.println("      <w:proofErr w:type='spellStart'/>");
			out.println("      <w:r>");
			out.println("        <w:rPr>");
			out.println("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:hint='fareast'/>");
			out.println("          <wx:font wx:val='標楷體'/>");
			out.println("          <w:b/>");
			out.println("          <w:b-cs/>");
			out.println("          <w:spacing w:val='6'/>");
			out.println("          <w:sz w:val='22'/>");
			out.println("          <w:sz-cs w:val='22'/>");
			out.println("        </w:rPr>");
			out.println("        <w:t>"+map.get("idno")+"</w:t>");
			out.println("      </w:r>");
			out.println("      <w:proofErr w:type='spellEnd'/>");
			out.println("    </w:p>");
			out.println("    <w:p wsp:rsidR='00871D92' wsp:rsidRPr='007C5DD4' wsp:rsidRDefault='00871D92' wsp:rsidP='00871D92'>");
			out.println("      <w:pPr>");
			out.println("        <w:pStyle w:val='Web'/>");
			out.println("        <w:spacing w:after='240' w:after-autospacing='off'/>");
			out.println("        <w:jc w:val='both'/>");
			out.println("        <w:rPr>");
			out.println("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體'/>");
			out.println("          <wx:font wx:val='標楷體'/>");
			out.println("          <w:b/>");
			out.println("          <w:b-cs/>");
			out.println("          <w:sz w:val='46'/>");
			out.println("          <w:sz-cs w:val='46'/>");
			out.println("        </w:rPr>");
			out.println("      </w:pPr>");
			out.println("      <w:r wsp:rsidRPr='007C5DD4'>");
			out.println("        <w:rPr>");
			out.println("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:hint='fareast'/>");
			out.println("          <wx:font wx:val='標楷體'/>");
			out.println("          <w:b/>");
			out.println("          <w:b-cs/>");
			out.println("          <w:sz w:val='46'/>");
			out.println("          <w:sz-cs w:val='46'/>");
			out.println("        </w:rPr>");
			out.println("        <w:t>查</w:t>");
			out.println("      </w:r>");
			out.println("      <w:r wsp:rsidR='00DF1632'>");
			out.println("        <w:rPr>");
			out.println("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:hint='fareast'/>");
			out.println("          <wx:font wx:val='標楷體'/>");
			out.println("          <w:b/>");
			out.println("          <w:b-cs/>");
			out.println("          <w:sz w:val='46'/>");
			out.println("          <w:sz-cs w:val='46'/>");
			out.println("        </w:rPr>");
			//out.println("        <w:t>$</w:t>");
			out.println("      </w:r>");
			out.println("      <w:proofErr w:type='spellStart'/>");
			out.println("      <w:r wsp:rsidR='00DF1632'>");
			out.println("        <w:rPr>");
			out.println("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:hint='fareast'/>");
			out.println("          <wx:font wx:val='標楷體'/>");
			out.println("          <w:b/>");
			out.println("          <w:b-cs/>");
			out.println("          <w:sz w:val='46'/>");
			out.println("          <w:sz-cs w:val='46'/>");
			out.println("        </w:rPr>");
			out.println("        <w:t> "+map.get("school_name")+" "+map.get("fname")+" </w:t>");
			out.println("      </w:r>");
			out.println("      <w:proofErr w:type='spellEnd'/>");
			out.println("      <w:r wsp:rsidRPr='007C5DD4'>");
			out.println("        <w:rPr>");
			out.println("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體'/>");
			out.println("          <wx:font wx:val='標楷體'/>");
			out.println("          <w:b/>");
			out.println("          <w:b-cs/>");
			out.println("          <w:sz w:val='46'/>");
			out.println("          <w:sz-cs w:val='46'/>");
			out.println("        </w:rPr>");
			out.println("        <w:t>學生</w:t>");
			out.println("      </w:r>");
			out.println("      <w:r wsp:rsidR='00DF1632'>");
			out.println("        <w:rPr>");
			out.println("          <w:rFonts w:ascii='華康特粗楷體' w:fareast='華康特粗楷體' w:h-ansi='Arial' w:cs='Arial' w:hint='fareast'/>");
			out.println("          <wx:font wx:val='華康特粗楷體'/>");
			out.println("          <w:b/>");
			out.println("          <w:b-cs/>");
			out.println("          <w:sz w:val='46'/>");
			out.println("          <w:sz-cs w:val='46'/>");
			out.println("        </w:rPr>");
			//out.println("        <w:t>$</w:t>");
			out.println("      </w:r>");
			out.println("      <w:proofErr w:type='spellStart'/>");
			out.println("      <w:r wsp:rsidR='00DF1632'>");
			out.println("        <w:rPr>");
			out.println("          <w:rFonts w:ascii='華康特粗楷體' w:fareast='華康特粗楷體' w:h-ansi='Arial' w:cs='Arial' w:hint='fareast'/>");
			out.println("          <wx:font wx:val='華康特粗楷體'/>");
			out.println("          <w:b/>");
			out.println("          <w:b-cs/>");
			out.println("          <w:sz w:val='46'/>");
			out.println("          <w:sz-cs w:val='46'/>");
			out.println("        </w:rPr>");
			out.println("        <w:t> "+((Map)list.get(i)).get("student_name")+" </w:t>");
			out.println("      </w:r>");
			out.println("      <w:proofErr w:type='spellEnd'/>");
			out.println("      <w:r wsp:rsidRPr='007C5DD4'>");
			out.println("        <w:rPr>");
			out.println("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體'/>");
			out.println("          <wx:font wx:val='標楷體'/>");
			out.println("          <w:b/>");
			out.println("          <w:b-cs/>");
			out.println("          <w:sz w:val='46'/>");
			out.println("          <w:sz-cs w:val='46'/>");
			out.println("        </w:rPr>");
			out.println("        <w:t>係中華民國</w:t>");
			out.println("      </w:r>");
			out.println("      <w:r wsp:rsidR='00DF1632'>");
			out.println("        <w:rPr>");
			out.println("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:hint='fareast'/>");
			out.println("          <wx:font wx:val='標楷體'/>");
			out.println("          <w:b/>");
			out.println("          <w:b-cs/>");
			out.println("          <w:sz w:val='46'/>");
			out.println("          <w:sz-cs w:val='46'/>");
			out.println("        </w:rPr>");
			
			
			SimpleDateFormat sf=new SimpleDateFormat("yyyy-MM-dd");
			Calendar c=Calendar.getInstance();
			c.setTime(sf.parse(map.get("birthday").toString()));
			
			out.println("        <w:t>"+(c.get(Calendar.YEAR)-1911)+"</w:t>");
			out.println("      </w:r>");
			out.println("      <w:r wsp:rsidRPr='007C5DD4'>");
			out.println("        <w:rPr>");
			out.println("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體'/>");
			out.println("          <wx:font wx:val='標楷體'/>");
			out.println("          <w:b/>");
			out.println("          <w:b-cs/>");
			out.println("          <w:sz w:val='46'/>");
			out.println("          <w:sz-cs w:val='46'/>");
			out.println("        </w:rPr>");
			out.println("        <w:t>年</w:t>");
			out.println("      </w:r>");
			out.println("      <w:r wsp:rsidR='00DF1632'>");
			out.println("        <w:rPr>");
			out.println("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:hint='fareast'/>");
			out.println("          <wx:font wx:val='標楷體'/>");
			out.println("          <w:b/>");
			out.println("          <w:b-cs/>");
			out.println("          <w:sz w:val='46'/>");
			out.println("          <w:sz-cs w:val='46'/>");
			out.println("        </w:rPr>");
			out.println("        <w:t>"+(c.get(Calendar.MONTH)+1)+"</w:t>");
			out.println("      </w:r>");
			out.println("      <w:r wsp:rsidRPr='007C5DD4'>");
			out.println("        <w:rPr>");
			out.println("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體'/>");
			out.println("          <wx:font wx:val='標楷體'/>");
			out.println("          <w:b/>");
			out.println("          <w:b-cs/>");
			out.println("          <w:sz w:val='46'/>");
			out.println("          <w:sz-cs w:val='46'/>");
			out.println("        </w:rPr>");
			out.println("        <w:t>月</w:t>");
			out.println("      </w:r>");
			out.println("      <w:r wsp:rsidR='00DF1632'>");
			out.println("        <w:rPr>");
			out.println("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:hint='fareast'/>");
			out.println("          <wx:font wx:val='標楷體'/>");
			out.println("          <w:b/>");
			out.println("          <w:b-cs/>");
			out.println("          <w:sz w:val='46'/>");
			out.println("          <w:sz-cs w:val='46'/>");
			out.println("        </w:rPr>");
			out.println("        <w:t>"+(c.get(Calendar.DAY_OF_MONTH)+1)+"</w:t>");
			out.println("      </w:r>");
			out.println("      <w:r wsp:rsidRPr='007C5DD4'>");
			out.println("        <w:rPr>");
			out.println("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體'/>");
			out.println("          <wx:font wx:val='標楷體'/>");
			out.println("          <w:b/>");
			out.println("          <w:b-cs/>");
			out.println("          <w:sz w:val='46'/>");
			out.println("          <w:sz-cs w:val='46'/>");
			out.println("        </w:rPr>");
			out.println("        <w:t>日生在本校修習</w:t>");
			out.println("      </w:r>");
			out.println("      <w:r wsp:rsidR='00DF1632'>");
			out.println("        <w:rPr>");
			out.println("          <w:rFonts w:ascii='華康特粗楷體' w:fareast='華康特粗楷體' w:h-ansi='Times New Roman' w:cs='Times New Roman' w:hint='fareast'/>");
			out.println("          <wx:font wx:val='華康特粗楷體'/>");
			out.println("          <w:b/>");
			out.println("          <w:b-cs/>");
			out.println("          <w:sz w:val='46'/>");
			out.println("          <w:sz-cs w:val='46'/>");
			out.println("        </w:rPr>");
			//out.println("        <w:t>$</w:t>");
			out.println("      </w:r>");
			out.println("      <w:proofErr w:type='spellStart'/>");
			out.println("      <w:r wsp:rsidR='00DF1632'>");
			out.println("        <w:rPr>");
			out.println("          <w:rFonts w:ascii='華康特粗楷體' w:fareast='華康特粗楷體' w:h-ansi='Times New Roman' w:cs='Times New Roman' w:hint='fareast'/>");
			out.println("          <wx:font wx:val='華康特粗楷體'/>");
			out.println("          <w:b/>");
			out.println("          <w:b-cs/>");
			out.println("          <w:sz w:val='46'/>");
			out.println("          <w:sz-cs w:val='46'/>");
			out.println("        </w:rPr>");
			out.println("        <w:t> "+((Map)list.get(i)).get("cname")+" </w:t>");
			out.println("      </w:r>");
			out.println("      <w:proofErr w:type='spellEnd'/>");
			out.println("      <w:r wsp:rsidRPr='007C5DD4'>");
			out.println("        <w:rPr>");
			out.println("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體'/>");
			out.println("          <wx:font wx:val='標楷體'/>");
			out.println("          <w:b/>");
			out.println("          <w:b-cs/>");
			out.println("          <w:sz w:val='46'/>");
			out.println("          <w:sz-cs w:val='46'/>");
			out.println("        </w:rPr>");
			out.println("        <w:t>學程依規定修滿</w:t>");
			out.println("      </w:r>");
			out.println("      <w:r wsp:rsidR='00DF1632'>");
			out.println("        <w:rPr>");
			out.println("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:hint='fareast'/>");
			out.println("          <wx:font wx:val='標楷體'/>");
			out.println("          <w:b/>");
			out.println("          <w:b-cs/>");
			out.println("          <w:sz w:val='46'/>");
			out.println("          <w:sz-cs w:val='46'/>");
			out.println("        </w:rPr>");
			
			
			
			
			
			
			out.println("        <w:t>"+(int)(Float.parseFloat(((Map)list.get(i)).get("minor").toString())+(Float.parseFloat(((Map)list.get(i)).get("major").toString())))+"</w:t>");
			out.println("      </w:r>");
			out.println("      <w:r wsp:rsidRPr='007C5DD4'>");
			out.println("        <w:rPr>");
			out.println("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體'/>");
			out.println("          <wx:font wx:val='標楷體'/>");
			out.println("          <w:b/>");
			out.println("          <w:b-cs/>");
			out.println("          <w:sz w:val='46'/>");
			out.println("          <w:sz-cs w:val='46'/>");
			out.println("        </w:rPr>");
			out.println("        <w:t>學分成績及格發給證明</w:t>");
			out.println("      </w:r>");
			out.println("    </w:p>");
			out.println("    <w:p wsp:rsidR='006018BB' wsp:rsidRDefault='00871D92' wsp:rsidP='007C5DD4'>");
			out.println("      <w:pPr>");
			out.println("        <w:pStyle w:val='Web'/>");
			out.println("        <w:spacing w:after='240' w:after-autospacing='off'/>");
			out.println("        <w:ind w:first-line-chars='100' w:first-line='460'/>");
			out.println("      </w:pPr>");
			out.println("      <w:r wsp:rsidRPr='007C5DD4'>");
			out.println("        <w:rPr>");
			out.println("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:hint='fareast'/>");
			out.println("          <wx:font wx:val='標楷體'/>");
			out.println("          <w:b/>");
			out.println("          <w:b-cs/>");
			out.println("          <w:sz w:val='46'/>");
			out.println("          <w:sz-cs w:val='46'/>");
			out.println("        </w:rPr>");
			out.println("        <w:t>此證</w:t>");
			out.println("      </w:r>");
			out.println("      <w:r wsp:rsidR='006018BB' wsp:rsidRPr='007C5DD4'>");
			out.println("        <w:rPr>");
			out.println("          <w:rFonts w:hint='fareast'/>");
			out.println("          <w:b/>");
			out.println("          <w:sz w:val='46'/>");
			out.println("          <w:sz-cs w:val='46'/>");
			out.println("        </w:rPr>");
			out.println("        <w:br/>");
			out.println("      </w:r>");
			out.println("      <w:r wsp:rsidR='006018BB'>");
			out.println("        <w:rPr>");
			out.println("          <w:rFonts w:hint='fareast'/>");
			out.println("        </w:rPr>");
			out.println("        <w:br/>");
			out.println("      </w:r>");
			out.println("      <w:r wsp:rsidR='006018BB'>");
			out.println("        <w:rPr>");
			out.println("          <w:rFonts w:hint='fareast'/>");
			out.println("        </w:rPr>");
			out.println("        <w:br/>");
			out.println("      </w:r>");
			out.println("    </w:p>");
			out.println("    <w:p wsp:rsidR='0005604F' wsp:rsidRDefault='0005604F' wsp:rsidP='0005604F'>");
			out.println("      <w:pPr>");
			out.println("        <w:pStyle w:val='Web'/>");
			out.println("        <w:spacing w:after='240' w:after-autospacing='off'/>");
			out.println("      </w:pPr>");
			out.println("    </w:p>");
			out.println("    <w:tbl>");
			out.println("      <w:tblPr>");
			out.println("        <w:tblW w:w='5000' w:type='pct'/>");
			out.println("        <w:jc w:val='right'/>");
			out.println("        <w:tblCellSpacing w:w='15' w:type='dxa'/>");
			out.println("        <w:tblCellMar>");
			out.println("          <w:top w:w='15' w:type='dxa'/>");
			out.println("          <w:left w:w='15' w:type='dxa'/>");
			out.println("          <w:bottom w:w='15' w:type='dxa'/>");
			out.println("          <w:right w:w='15' w:type='dxa'/>");
			out.println("        </w:tblCellMar>");
			out.println("      </w:tblPr>");
			out.println("      <w:tblGrid>");
			out.println("        <w:gridCol w:w='8396'/>");
			out.println("      </w:tblGrid>");
			out.println("      <w:tr wsp:rsidR='006018BB'>");
			out.println("        <w:trPr>");
			out.println("          <w:tblCellSpacing w:w='15' w:type='dxa'/>");
			out.println("          <w:jc w:val='right'/>");
			out.println("        </w:trPr>");
			out.println("        <w:tc>");
			out.println("          <w:tcPr>");
			out.println("            <w:tcW w:w='0' w:type='auto'/>");
			out.println("            <w:vAlign w:val='center'/>");
			out.println("          </w:tcPr>");
			out.println("          <w:p wsp:rsidR='006018BB' wsp:rsidRDefault='006018BB'>");
			out.println("            <w:pPr>");
			out.println("              <w:jc w:val='right'/>");
			out.println("            </w:pPr>");
			out.println("          </w:p>");
			out.println("          <w:p wsp:rsidR='006018BB' wsp:rsidRDefault='006018BB'>");
			out.println("            <w:pPr>");
			out.println("              <w:pStyle w:val='Web'/>");
			out.println("              <w:spacing w:after='240' w:after-autospacing='off'/>");
			out.println("              <w:jc w:val='right'/>");
			out.println("            </w:pPr>");
			out.println("            <w:r>");
			out.println("              <w:br/>");
			out.println("            </w:r>");
			out.println("            <w:r>");
			out.println("              <w:br/>");
			out.println("            </w:r>");
			out.println("            <w:r>");
			out.println("              <w:br/>");
			out.println("            </w:r>");
			out.println("          </w:p>");
			out.println("        </w:tc>");
			out.println("      </w:tr>");
			out.println("    </w:tbl>");
			out.println("    <w:p wsp:rsidR='006018BB' wsp:rsidRDefault='006018BB'>");
			out.println("      <w:pPr>");
			out.println("        <w:jc w:val='center'/>");
			out.println("      </w:pPr>");
			out.println("      <w:r>");
			out.println("        <w:rPr>");
			out.println("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:hint='fareast'/>");
			out.println("          <wx:font wx:val='標楷體'/>");
			out.println("          <w:b/>");
			out.println("          <w:b-cs/>");
			out.println("          <w:spacing w:val='60'/>");
			out.println("          <w:sz w:val='44'/>");
			out.println("          <w:sz-cs w:val='44'/>");
			out.println("        </w:rPr>");
			out.println("        <w:t>中華民國</w:t>");
			out.println("      </w:r>");
			out.println("      <w:r wsp:rsidR='00DF1632'>");
			out.println("        <w:rPr>");
			out.println("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:hint='fareast'/>");
			out.println("          <wx:font wx:val='標楷體'/>");
			out.println("          <w:b/>");
			out.println("          <w:b-cs/>");
			out.println("          <w:spacing w:val='60'/>");
			out.println("          <w:sz w:val='44'/>");
			out.println("          <w:sz-cs w:val='44'/>");
			out.println("        </w:rPr>");
			//out.println("        <w:t>$</w:t>");
			out.println("      </w:r>");
			out.println("      <w:proofErr w:type='spellStart'/>");
			out.println("      <w:r wsp:rsidR='00DF1632'>");
			out.println("        <w:rPr>");
			out.println("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:hint='fareast'/>");
			out.println("          <wx:font wx:val='標楷體'/>");
			out.println("          <w:b/>");
			out.println("          <w:b-cs/>");
			out.println("          <w:spacing w:val='60'/>");
			out.println("          <w:sz w:val='44'/>");
			out.println("          <w:sz-cs w:val='44'/>");
			out.println("        </w:rPr>");
			out.println("        <w:t>"+(now.get(Calendar.YEAR)-1911)+"</w:t>");
			out.println("      </w:r>");
			out.println("      <w:proofErr w:type='spellEnd'/>");
			out.println("      <w:r>");
			out.println("        <w:rPr>");
			out.println("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:hint='fareast'/>");
			out.println("          <wx:font wx:val='標楷體'/>");
			out.println("          <w:b/>");
			out.println("          <w:b-cs/>");
			out.println("          <w:spacing w:val='60'/>");
			out.println("          <w:sz w:val='44'/>");
			out.println("          <w:sz-cs w:val='44'/>");
			out.println("        </w:rPr>");
			out.println("        <w:t>年</w:t>");
			out.println("      </w:r>");
			out.println("      <w:r wsp:rsidR='00DF1632'>");
			out.println("        <w:rPr>");
			out.println("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:hint='fareast'/>");
			out.println("          <wx:font wx:val='標楷體'/>");
			out.println("          <w:b/>");
			out.println("          <w:b-cs/>");
			out.println("          <w:spacing w:val='60'/>");
			out.println("          <w:sz w:val='44'/>");
			out.println("          <w:sz-cs w:val='44'/>");
			out.println("        </w:rPr>");
			out.println("        <w:t>"+(now.get(Calendar.MONTH)+1)+"</w:t>");
			out.println("      </w:r>");
			out.println("      <w:r>");
			out.println("        <w:rPr>");
			out.println("          <w:rFonts w:ascii='標楷體' w:fareast='標楷體' w:h-ansi='標楷體' w:hint='fareast'/>");
			out.println("          <wx:font wx:val='標楷體'/>");
			out.println("          <w:b/>");
			out.println("          <w:b-cs/>");
			out.println("          <w:spacing w:val='60'/>");
			out.println("          <w:sz w:val='44'/>");
			out.println("          <w:sz-cs w:val='44'/>");
			out.println("        </w:rPr>");
			out.println("        <w:t>月　 日</w:t>");
			out.println("      </w:r>");
			out.println("    </w:p>");
			out.println("    <w:p wsp:rsidR='006018BB' wsp:rsidRDefault='006018BB'/>");
			out.println("    <w:sectPr wsp:rsidR='006018BB' wsp:rsidSect='002958BE'>");
			out.println("      <w:pgSz w:w='11906' w:h='16838'/>");
			out.println("      <w:pgMar w:top='1440' w:right='1800' w:bottom='1440' w:left='1800' w:header='851' w:footer='992' w:gutter='0'/>");
			out.println("      <w:cols w:space='425'/>");
			out.println("      <w:docGrid w:line-pitch='360'/>");
			out.println("    </w:sectPr>");
			if(i<list.size()-1){
				out.println ("<w:br w:type='page'/>");
			}			
		}
		out.println("  </w:body>");		
		out.println("</w:wordDocument>");		
		out.flush();
		out.close();
		return null;		
	}

}
