package tw.edu.chit.model;

import java.util.Date;

/**
 * AdcdHistory generated by MyEclipse Persistence Tools
 */
public class AdcdHistory implements java.io.Serializable {

	private static final long serialVersionUID = 1167256573085669755L;

	private Integer oid;
	private Integer dtimeOid;
	private String studentNo;
	private String adddraw;
	private String modified;
	private Date lastModified;

	public AdcdHistory() {
	}

	public AdcdHistory(Integer oid, Integer dtimeOid, String studentNo,
			String adddraw, String modified, Date lastModified) {
		this.oid = oid;
		this.dtimeOid = dtimeOid;
		this.studentNo = studentNo;
		this.adddraw = adddraw;
		this.modified = modified;
		this.lastModified = lastModified;
	}

	public Integer getOid() {
		return this.oid;
	}

	public void setOid(Integer oid) {
		this.oid = oid;
	}

	public Integer getDtimeOid() {
		return this.dtimeOid;
	}

	public void setDtimeOid(Integer dtimeOid) {
		this.dtimeOid = dtimeOid;
	}

	public String getStudentNo() {
		return this.studentNo;
	}

	public void setStudentNo(String studentNo) {
		this.studentNo = studentNo;
	}

	public String getAdddraw() {
		return this.adddraw;
	}

	public void setAdddraw(String adddraw) {
		this.adddraw = adddraw;
	}

	public String getModified() {
		return this.modified;
	}

	public void setModified(String modified) {
		this.modified = modified;
	}

	public Date getLastModified() {
		return this.lastModified;
	}

	public void setLastModified(Date lastModified) {
		this.lastModified = lastModified;
	}

}