package tw.edu.chit.model;

/**
 * Adcd generated by MyEclipse - Hibernate Tools
 */

public class Adcd implements java.io.Serializable {

	private static final long serialVersionUID = -7462879399931797911L;
	
	private Integer oid;
	private String studepartClass;
	private String studentNo;
	private String adddraw;
	private Integer dtimeOid;

	/** default constructor */
	public Adcd() {
	}

	/** minimal constructor */
	public Adcd(Integer oid) {
		this.oid = oid;
	}

	/** full constructor */
	public Adcd(Integer oid, String studepartClass, String studentNo,
			String adddraw, Integer dtimeOid) {
		this.oid = oid;
		this.studepartClass = studepartClass;
		this.studentNo = studentNo;
		this.adddraw = adddraw;
		this.dtimeOid = dtimeOid;
	}

	public Integer getOid() {
		return this.oid;
	}

	public void setOid(Integer oid) {
		this.oid = oid;
	}

	public String getStudepartClass() {
		return this.studepartClass;
	}

	public void setStudepartClass(String studepartClass) {
		this.studepartClass = studepartClass;
	}

	public String getStudentNo() {
		return this.studentNo;
	}

	public void setStudentNo(String studentNo) {
		this.studentNo = studentNo;
	}

	public String getAdddraw() {
		return this.adddraw;
	}

	public void setAdddraw(String adddraw) {
		this.adddraw = adddraw;
	}

	public Integer getDtimeOid() {
		return this.dtimeOid;
	}

	public void setDtimeOid(Integer dtimeOid) {
		this.dtimeOid = dtimeOid;
	}

}