package tw.edu.chit.model;

/**
 * ClassCadre generated by MyEclipse - Hibernate Tools
 */

public class ClassCadre implements java.io.Serializable {

	private static final long serialVersionUID = -6965970671859749929L;
	
	private Integer oid;
	private Integer parentOid;
	private String classNo;
	private String studentNo;
	private String name;
	private String homePhone;
	private String cellPhone;
	private String email;
	private Short role;
	private String remark;
	private Integer pos;
	
	private Empl empl;

	// Constructors

	/** default constructor */
	public ClassCadre() {
	}

	// Property accessors

	public Integer getOid() {
		return this.oid;
	}

	public void setOid(Integer oid) {
		this.oid = oid;
	}

	public Integer getParentOid() {
		return this.parentOid;
	}

	public void setParentOid(Integer parentOid) {
		this.parentOid = parentOid;
	}

	public String getClassNo() {
		return this.classNo;
	}

	public void setClassNo(String classNo) {
		this.classNo = classNo;
	}

	public Short getRole() {
		return this.role;
	}

	public void setRole(Short role) {
		this.role = role;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Integer getPos() {
		return this.pos;
	}

	public void setPos(Integer pos) {
		this.pos = pos;
	}

	public String getCellPhone() {
		return cellPhone;
	}

	public void setCellPhone(String cellPhone) {
		this.cellPhone = cellPhone;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getHomePhone() {
		return homePhone;
	}

	public void setHomePhone(String homePhone) {
		this.homePhone = homePhone;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getStudentNo() {
		return studentNo;
	}

	public void setStudentNo(String studentNo) {
		this.studentNo = studentNo;
	}

	public Empl getEmpl() {
		return empl;
	}

	public void setEmpl(Empl empl) {
		this.empl = empl;
	}

}