package tw.edu.chit.model;

/**
 * Clazz generated by MyEclipse - Hibernate Tools
 */
public class Clazz extends ClazzBase implements java.io.Serializable {

	private static final long serialVersionUID = 377401393747875161L;

	private Integer oid;
	private String campusNo;
	private String schoolNo;
	private String schoolType;
	private String deptNo;
	private String classNo;
	private String className;
	private String shortName;
	private String grade;
	private String type;
	private String SeqNo;

	/** default constructor */
	public Clazz() {
	}
	
	public String getSeqNo() {
		return SeqNo;
	}

	public void setSeqNo(String seqNo) {
		SeqNo = seqNo;
	}

	public Clazz(String classNo) {
		this.classNo = classNo;
	}

	/** minimal constructor */
	public Clazz(String classNo, String className, String type) {
		this.classNo = classNo;
		this.className = className;
		this.type = type;
	}

	/** full constructor */
	public Clazz(String campusNo, String schoolNo, String deptNo,
			String classNo, String className, String shortName, String grade,
			String type) {
		this.campusNo = campusNo;
		this.schoolNo = schoolNo;
		this.deptNo = deptNo;
		this.classNo = classNo;
		this.className = className;
		this.shortName = shortName;
		this.grade = grade;
		this.type = type;
	}

	public Integer getOid() {
		return this.oid;
	}

	public void setOid(Integer oid) {
		this.oid = oid;
	}

	public String getCampusNo() {
		return this.campusNo;
	}

	public void setCampusNo(String campusNo) {
		this.campusNo = campusNo;
	}

	public String getSchoolNo() {
		return this.schoolNo;
	}

	public void setSchoolNo(String schoolNo) {
		this.schoolNo = schoolNo;
	}

	public String getSchoolType() {
		return schoolType;
	}

	public void setSchoolType(String schoolType) {
		this.schoolType = schoolType;
	}

	public String getDeptNo() {
		return this.deptNo;
	}

	public void setDeptNo(String deptNo) {
		this.deptNo = deptNo;
	}

	public String getClassNo() {
		return this.classNo;
	}

	public void setClassNo(String classNo) {
		this.classNo = classNo;
	}

	public String getClassName() {
		return this.className;
	}

	public void setClassName(String className) {
		this.className = className;
	}

	public String getShortName() {
		return this.shortName;
	}

	public void setShortName(String shortName) {
		this.shortName = shortName;
	}

	public String getGrade() {
		return this.grade;
	}

	public void setGrade(String grade) {
		this.grade = grade;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

}