package tw.edu.chit.model;

import java.util.Date;


/**
 * Coansw generated by MyEclipse - Hibernate Tools
 */

public class Coansw  implements java.io.Serializable {


    // Fields

     private Integer oid;
     private Date ddate;
     private String studentNo;
     private String answer;
     private Integer dtimeOid;
     private String type;


    // Constructors

    /** default constructor */
    public Coansw() {
    }


    /** full constructor */
    public Coansw(Date ddate, String studentNo, String answer, Integer dtimeOid, String type) {
        this.ddate = ddate;
        this.studentNo = studentNo;
        this.answer = answer;
        this.dtimeOid = dtimeOid;
        this.type = type;
    }


    // Property accessors

    public Integer getOid() {
        return this.oid;
    }

    public void setOid(Integer oid) {
        this.oid = oid;
    }

    public Date getDdate() {
        return this.ddate;
    }

    public void setDdate(Date ddate) {
        this.ddate = ddate;
    }

    public String getStudentNo() {
        return this.studentNo;
    }

    public void setStudentNo(String studentNo) {
        this.studentNo = studentNo;
    }

    public String getAnswer() {
        return this.answer;
    }

    public void setAnswer(String answer) {
        this.answer = answer;
    }

    public Integer getDtimeOid() {
        return this.dtimeOid;
    }

    public void setDtimeOid(Integer dtimeOid) {
        this.dtimeOid = dtimeOid;
    }

    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }









}