package tw.edu.chit.model;

/**
 * Code2 generated by MyEclipse - Hibernate Tools
 */
public class Code2 implements java.io.Serializable {

	private static final long serialVersionUID = -6571775913820009855L;

	private Integer oid;
	private String name;
	private String no;

	public Code2() {
	}

	public Code2(String no) {
		this.no = no;
	}

	public Code2(String name, String no) {
		this.name = name;
		this.no = no;
	}

	public Integer getOid() {
		return this.oid;
	}

	public void setOid(Integer oid) {
		this.oid = oid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getNo() {
		return this.no;
	}

	public void setNo(String no) {
		this.no = no;
	}

}