package tw.edu.chit.model;

/**
 * Code5 generated by MyEclipse - Hibernate Tools
 */
public class Code5 implements java.io.Serializable {

	private static final long serialVersionUID = 430330754419725643L;

	private Integer oid;
	private String name;
	private String category;
	private Integer sequence;
	private String idno;

	public Code5() {
	}

	public Code5(Integer oid) {
		this.oid = oid;
	}

	public String getCategory() {
		return category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getOid() {
		return oid;
	}

	public void setOid(Integer oid) {
		this.oid = oid;
	}

	public Integer getSequence() {
		return sequence;
	}

	public void setSequence(Integer sequence) {
		this.sequence = sequence;
	}

	public String getIdno() {
		return idno;
	}

	public void setIdno(String idno) {
		this.idno = idno;
	}

}