package tw.edu.chit.model;

/**
 * Code1 generated by MyEclipse - Hibernate Tools
 */
public class Code1 implements java.io.Serializable {

	private static final long serialVersionUID = 7423968366318984301L;

	private Integer oid;
	private String no;
	private String name;

	public Code1() {
	}

	public Code1(String no) {
		this.no = no;
	}

	public Code1(String no, String name) {
		this.no = no;
		this.name = name;
	}

	public Integer getOid() {
		return this.oid;
	}

	public void setOid(Integer oid) {
		this.oid = oid;
	}

	public String getNo() {
		return this.no;
	}

	public void setNo(String no) {
		this.no = no;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}