package tw.edu.chit.model;



/**
 * CoQuestion generated by MyEclipse - Hibernate Tools
 */

public class CoQuestion  implements java.io.Serializable {


    // Fields

     private Integer oid;
     private String type;
     private String options;
     private Integer parentOid;
     private String textValue;
     private Integer sequence;
     private String value;


    // Constructors

    /** default constructor */
    public CoQuestion() {
    }


    /** full constructor */
    public CoQuestion(String type, String options, Integer parentOid, String textValue, Integer sequence, String value) {
        this.type = type;
        this.options = options;
        this.parentOid = parentOid;
        this.textValue = textValue;
        this.sequence = sequence;
        this.value = value;
    }


    // Property accessors

    public Integer getOid() {
        return this.oid;
    }

    public void setOid(Integer oid) {
        this.oid = oid;
    }

    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getOptions() {
        return this.options;
    }

    public void setOptions(String options) {
        this.options = options;
    }

    public Integer getParentOid() {
        return this.parentOid;
    }

    public void setParentOid(Integer parentOid) {
        this.parentOid = parentOid;
    }

    public String getTextValue() {
        return this.textValue;
    }

    public void setTextValue(String textValue) {
        this.textValue = textValue;
    }

    public Integer getSequence() {
        return this.sequence;
    }

    public void setSequence(Integer sequence) {
        this.sequence = sequence;
    }

    public String getValue() {
        return this.value;
    }

    public void setValue(String value) {
        this.value = value;
    }









}