package tw.edu.chit.model;

import java.util.Date;

/**
 * CourseIntroduction generated by MyEclipse - Hibernate Tools
 */

public class CourseIntroduction implements java.io.Serializable {

	private static final long serialVersionUID = 5823604635357015314L;

	private Integer oid;
	private Integer dtimeOid;
	private Integer schoolYear;
	private Integer schoolTerm;
	private String departClass;
	private String cscode;
	private String engName;
	private String chiIntro;
	private String engIntro;
	private String bookSuggest;
	private Date lastModified;
	private Date suggestLastModified;

	/** default constructor */
	public CourseIntroduction() {
	}

	/** full constructor */
	public CourseIntroduction(Integer dtimeOid, Integer schoolYear,
			Integer schoolTerm, String chiIntro, String engIntro,
			Date lastModified, Date suggestLastModified) {
		this.dtimeOid = dtimeOid;
		this.schoolYear = schoolYear;
		this.schoolTerm = schoolTerm;
		this.chiIntro = chiIntro;
		this.engIntro = engIntro;
		this.lastModified = lastModified;
		this.suggestLastModified = suggestLastModified;
	}

	// Property accessors

	public Integer getOid() {
		return this.oid;
	}

	public void setOid(Integer oid) {
		this.oid = oid;
	}

	public Integer getDtimeOid() {
		return this.dtimeOid;
	}

	public void setDtimeOid(Integer dtimeOid) {
		this.dtimeOid = dtimeOid;
	}

	public Integer getSchoolYear() {
		return schoolYear;
	}

	public void setSchoolYear(Integer schoolYear) {
		this.schoolYear = schoolYear;
	}

	public Integer getSchoolTerm() {
		return schoolTerm;
	}

	public void setSchoolTerm(Integer schoolTerm) {
		this.schoolTerm = schoolTerm;
	}

	public String getDepartClass() {
		return departClass;
	}

	public void setDepartClass(String departClass) {
		this.departClass = departClass;
	}

	public String getCscode() {
		return cscode;
	}

	public void setCscode(String cscode) {
		this.cscode = cscode;
	}

	public String getEngName() {
		return engName;
	}

	public void setEngName(String engName) {
		this.engName = engName;
	}

	public String getChiIntro() {
		return this.chiIntro;
	}

	public void setChiIntro(String chiIntro) {
		this.chiIntro = chiIntro;
	}

	public String getEngIntro() {
		return this.engIntro;
	}

	public void setEngIntro(String engIntro) {
		this.engIntro = engIntro;
	}

	public String getBookSuggest() {
		return bookSuggest;
	}

	public void setBookSuggest(String bookSuggest) {
		this.bookSuggest = bookSuggest;
	}

	public Date getLastModified() {
		return this.lastModified;
	}

	public void setLastModified(Date lastModified) {
		this.lastModified = lastModified;
	}

	public Date getSuggestLastModified() {
		return suggestLastModified;
	}

	public void setSuggestLastModified(Date suggestLastModified) {
		this.suggestLastModified = suggestLastModified;
	}

}