package tw.edu.chit.model;

import java.util.Date;

/**
 * Csno generated by MyEclipse - Hibernate Tools
 */
public class Csno implements java.io.Serializable {

	private static final long serialVersionUID = 8302610595016611364L;

	private Integer oid;
	private String cscode;
	private String chiName;
	private String engName;
	private String literacyType;
	private String modifier;
	private Date lastModified;

	public Csno() {
	}

	public Csno(Integer oid, String cscode) {
		this.oid = oid;
		this.cscode = cscode;
	}

	public Csno(Integer oid, String cscode, String chiName, String engName) {
		this.oid = oid;
		this.cscode = cscode;
		this.chiName = chiName;
		this.engName = engName;
	}

	public Integer getOid() {
		return this.oid;
	}

	public void setOid(Integer oid) {
		this.oid = oid;
	}

	public String getCscode() {
		return this.cscode;
	}

	public void setCscode(String cscode) {
		this.cscode = cscode;
	}

	public String getChiName() {
		return this.chiName;
	}

	public void setChiName(String chiName) {
		this.chiName = chiName;
	}

	public String getEngName() {
		return this.engName;
	}

	public void setEngName(String engName) {
		this.engName = engName;
	}

	public String getLiteracyType() {
		return literacyType;
	}

	public void setLiteracyType(String literacyType) {
		this.literacyType = literacyType;
	}

	public String getModifier() {
		return modifier;
	}

	public void setModifier(String modifier) {
		this.modifier = modifier;
	}

	public Date getLastModified() {
		return lastModified;
	}

	public void setLastModified(Date lastModified) {
		this.lastModified = lastModified;
	}

}