package tw.edu.chit.model;

import java.io.ByteArrayOutputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 * Dilg generated by MyEclipse - Hibernate Tools
 */
public class Dilg extends DilgBase implements java.io.Serializable,
		tw.edu.chit.model.domain.DilgService {

	private static final long serialVersionUID = 8006336086880578386L;

	private Integer oid;
	private String departClass;
	private String studentNo;
	private Long weekNo; // 週次
	private Float weekDay; // 星期n
	private Date ddate;
	private String daynite;
	private Short abs0;
	private Short abs1;
	private Short abs2;
	private Short abs3;
	private Short abs4;
	private Short abs5;
	private Short abs6;
	private Short abs7;
	private Short abs8;
	private Short abs9;
	private Short abs10;
	private Short abs11;
	private Short abs12;
	private Short abs13;
	private Short abs14;
	private Short abs15;

	public Dilg() {
	}

	public Dilg(String departClass, String studentNo) {
		this.departClass = departClass;
		this.studentNo = studentNo;
	}

	public Dilg(String departClass, String studentNo, Long weekNo,
			Float weekDay, Date ddate, String daynite, Short abs0, Short abs1,
			Short abs2, Short abs3, Short abs4, Short abs5, Short abs6,
			Short abs7, Short abs8, Short abs9, Short abs10, Short abs11,
			Short abs12, Short abs13, Short abs14, Short abs15) {
		this.departClass = departClass;
		this.studentNo = studentNo;
		this.weekNo = weekNo;
		this.weekDay = weekDay;
		this.ddate = ddate;
		this.daynite = daynite;
		this.abs0 = abs0;
		this.abs1 = abs1;
		this.abs2 = abs2;
		this.abs3 = abs3;
		this.abs4 = abs4;
		this.abs5 = abs5;
		this.abs6 = abs6;
		this.abs7 = abs7;
		this.abs8 = abs8;
		this.abs9 = abs9;
		this.abs10 = abs10;
		this.abs11 = abs11;
		this.abs12 = abs12;
		this.abs13 = abs13;
		this.abs14 = abs14;
		this.abs15 = abs15;
	}

	public Integer getOid() {
		return this.oid;
	}

	public void setOid(Integer oid) {
		this.oid = oid;
	}

	public String getDepartClass() {
		return this.departClass;
	}

	public void setDepartClass(String departClass) {
		this.departClass = departClass;
	}

	public String getStudentNo() {
		return this.studentNo;
	}

	public void setStudentNo(String studentNo) {
		this.studentNo = studentNo;
	}

	public Long getWeekNo() {
		return this.weekNo;
	}

	public void setWeekNo(Long weekNo) {
		this.weekNo = weekNo;
	}

	public Float getWeekDay() {
		return this.weekDay;
	}

	public void setWeekDay(Float weekDay) {
		this.weekDay = weekDay;
	}

	public Date getDdate() {
		return this.ddate;
	}

	public void setDdate(Date ddate) {
		this.ddate = ddate;
	}

	public String getDaynite() {
		return this.daynite;
	}

	public void setDaynite(String daynite) {
		this.daynite = daynite;
	}

	public Short getAbs0() {
		return this.abs0;
	}

	public void setAbs0(Short abs0) {
		this.abs0 = abs0;
	}

	public Short getAbs1() {
		return this.abs1;
	}

	public void setAbs1(Short abs1) {
		this.abs1 = abs1;
	}

	public Short getAbs2() {
		return this.abs2;
	}

	public void setAbs2(Short abs2) {
		this.abs2 = abs2;
	}

	public Short getAbs3() {
		return this.abs3;
	}

	public void setAbs3(Short abs3) {
		this.abs3 = abs3;
	}

	public Short getAbs4() {
		return this.abs4;
	}

	public void setAbs4(Short abs4) {
		this.abs4 = abs4;
	}

	public Short getAbs5() {
		return this.abs5;
	}

	public void setAbs5(Short abs5) {
		this.abs5 = abs5;
	}

	public Short getAbs6() {
		return this.abs6;
	}

	public void setAbs6(Short abs6) {
		this.abs6 = abs6;
	}

	public Short getAbs7() {
		return this.abs7;
	}

	public void setAbs7(Short abs7) {
		this.abs7 = abs7;
	}

	public Short getAbs8() {
		return this.abs8;
	}

	public void setAbs8(Short abs8) {
		this.abs8 = abs8;
	}

	public Short getAbs9() {
		return this.abs9;
	}

	public void setAbs9(Short abs9) {
		this.abs9 = abs9;
	}

	public Short getAbs10() {
		return this.abs10;
	}

	public void setAbs10(Short abs10) {
		this.abs10 = abs10;
	}

	public Short getAbs11() {
		return this.abs11;
	}

	public void setAbs11(Short abs11) {
		this.abs11 = abs11;
	}

	public Short getAbs12() {
		return this.abs12;
	}

	public void setAbs12(Short abs12) {
		this.abs12 = abs12;
	}

	public Short getAbs13() {
		return this.abs13;
	}

	public void setAbs13(Short abs13) {
		this.abs13 = abs13;
	}

	public Short getAbs14() {
		return this.abs14;
	}

	public void setAbs14(Short abs14) {
		this.abs14 = abs14;
	}

	public Short getAbs15() {
		return this.abs15;
	}

	public void setAbs15(Short abs15) {
		this.abs15 = abs15;
	}

	public void setAbs(int period, Short status) {
		switch (period) {
			case 0:
				this.setAbs0(status);
				break;
			case 1:
				this.setAbs1(status);
				break;
			case 2:
				this.setAbs2(status);
				break;
			case 3:
				this.setAbs3(status);
				break;
			case 4:
				this.setAbs4(status);
				break;
			case 5:
				this.setAbs5(status);
				break;
			case 6:
				this.setAbs6(status);
				break;
			case 7:
				this.setAbs7(status);
				break;
			case 8:
				this.setAbs8(status);
				break;
			case 9:
				this.setAbs9(status);
				break;
			case 10:
				this.setAbs10(status);
				break;
			case 11:
				this.setAbs11(status);
				break;
			case 12:
				this.setAbs12(status);
				break;
			case 13:
				this.setAbs13(status);
				break;
			case 14:
				this.setAbs14(status);
				break;
			case 15:
				this.setAbs15(status);
				break;
		}
	}

	/**
	 * 取得 Dilg 某一節次之狀態
	 * 
	 * @param period
	 * @return
	 */
	public Short getAbs(int period) {
		Short status = null;
		switch (period) {
			case 0:
				status = this.getAbs0();
				break;
			case 1:
				status = this.getAbs1();
				break;
			case 2:
				status = this.getAbs2();
				break;
			case 3:
				status = this.getAbs3();
				break;
			case 4:
				status = this.getAbs4();
				break;
			case 5:
				status = this.getAbs5();
				break;
			case 6:
				status = this.getAbs6();
				break;
			case 7:
				status = this.getAbs7();
				break;
			case 8:
				status = this.getAbs8();
				break;
			case 9:
				status = this.getAbs9();
				break;
			case 10:
				status = this.getAbs10();
				break;
			case 11:
				status = this.getAbs11();
				break;
			case 12:
				status = this.getAbs12();
				break;
			case 13:
				status = this.getAbs13();
				break;
			case 14:
				status = this.getAbs14();
				break;
			case 15:
				status = this.getAbs15();
				break;
		}
		return status;
	}

	public byte[] serialize() throws IOException {
		DateFormat df = new SimpleDateFormat("yyyyMMdd");
		ByteArrayOutputStream baos = new ByteArrayOutputStream();
		DataOutputStream dos = new DataOutputStream(baos);
		dos.writeInt(oid);
		dos.writeUTF(departClass);
		dos.writeUTF(studentNo);
		dos.writeLong(weekNo);
		dos.writeFloat(weekDay);
		dos.writeUTF(df.format(ddate));
		dos.writeUTF(daynite);
		dos.writeShort(abs0);
		dos.writeShort(abs1);
		dos.writeShort(abs2);
		dos.writeShort(abs3);
		dos.writeShort(abs4);
		dos.writeShort(abs5);
		dos.writeShort(abs6);
		dos.writeShort(abs7);
		dos.writeShort(abs8);
		dos.writeShort(abs9);
		dos.writeShort(abs10);
		dos.writeShort(abs11);
		dos.writeShort(abs12);
		dos.writeShort(abs13);
		dos.writeShort(abs14);
		dos.writeShort(abs15);
		return baos.toByteArray();
	}

}