package tw.edu.chit.model;

/**
 * DtimeReserve generated by MyEclipse Persistence Tools
 */

public class DtimeReserve implements java.io.Serializable {

	// Fields

	private Integer oid;

	private Integer year;

	private String term;

	private String grade;

	private String departClass;

	private String cscode;

	private String opt;

	private Float credit;

	private Short thour;

	private String cyber;

	private String additionType;

	// Constructors

	/** default constructor */
	public DtimeReserve() {
	}

	/** minimal constructor */
	public DtimeReserve(String grade, String departClass) {
		this.grade = grade;
		this.departClass = departClass;
	}

	/** full constructor */
	public DtimeReserve(Integer year, String term, String grade,
			String departClass, String cscode, String opt, Float credit,
			Short thour, String cyber, String additionType) {
		this.year = year;
		this.term = term;
		this.grade = grade;
		this.departClass = departClass;
		this.cscode = cscode;
		this.opt = opt;
		this.credit = credit;
		this.thour = thour;
		this.cyber = cyber;
		this.additionType = additionType;
	}

	// Property accessors

	public Integer getOid() {
		return this.oid;
	}

	public void setOid(Integer oid) {
		this.oid = oid;
	}

	public Integer getYear() {
		return this.year;
	}

	public void setYear(Integer year) {
		this.year = year;
	}

	public String getTerm() {
		return this.term;
	}

	public void setTerm(String term) {
		this.term = term;
	}

	public String getGrade() {
		return this.grade;
	}

	public void setGrade(String grade) {
		this.grade = grade;
	}

	public String getDepartClass() {
		return this.departClass;
	}

	public void setDepartClass(String departClass) {
		this.departClass = departClass;
	}

	public String getCscode() {
		return this.cscode;
	}

	public void setCscode(String cscode) {
		this.cscode = cscode;
	}

	public String getOpt() {
		return this.opt;
	}

	public void setOpt(String opt) {
		this.opt = opt;
	}

	public Float getCredit() {
		return this.credit;
	}

	public void setCredit(Float credit) {
		this.credit = credit;
	}

	public Short getThour() {
		return this.thour;
	}

	public void setThour(Short thour) {
		this.thour = thour;
	}

	public String getCyber() {
		return this.cyber;
	}

	public void setCyber(String cyber) {
		this.cyber = cyber;
	}

	public String getAdditionType() {
		return this.additionType;
	}

	public void setAdditionType(String additionType) {
		this.additionType = additionType;
	}

}