package tw.edu.chit.model;

/**
 * DtimeReserveReady generated by MyEclipse Persistence Tools
 */

public class DtimeReserveReady implements java.io.Serializable {

	// Fields

	private Integer oid;

	private Integer year;

	private String term;

	private String departClass;

	private String cscode;

	private String techid;

	private String opt;

	private Float credit;

	private Short thour;

	private Short selectLimit;

	private String additionType;

	private String cyber;

	private String confirmType;

	// Constructors

	/** default constructor */
	public DtimeReserveReady() {
	}

	/** minimal constructor */
	public DtimeReserveReady(String departClass) {
		this.departClass = departClass;
	}

	/** full constructor */
	public DtimeReserveReady(Integer year, String term, String departClass,
			String cscode, String techid, String opt, Float credit,
			Short thour, Short selectLimit, String additionType, String cyber,
			String confirmType) {
		this.year = year;
		this.term = term;
		this.departClass = departClass;
		this.cscode = cscode;
		this.techid = techid;
		this.opt = opt;
		this.credit = credit;
		this.thour = thour;
		this.selectLimit = selectLimit;
		this.additionType = additionType;
		this.cyber = cyber;
		this.confirmType = confirmType;
	}

	// Property accessors

	public Integer getOid() {
		return this.oid;
	}

	public void setOid(Integer oid) {
		this.oid = oid;
	}

	public Integer getYear() {
		return this.year;
	}

	public void setYear(Integer year) {
		this.year = year;
	}

	public String getTerm() {
		return this.term;
	}

	public void setTerm(String term) {
		this.term = term;
	}

	public String getDepartClass() {
		return this.departClass;
	}

	public void setDepartClass(String departClass) {
		this.departClass = departClass;
	}

	public String getCscode() {
		return this.cscode;
	}

	public void setCscode(String cscode) {
		this.cscode = cscode;
	}

	public String getTechid() {
		return this.techid;
	}

	public void setTechid(String techid) {
		this.techid = techid;
	}

	public String getOpt() {
		return this.opt;
	}

	public void setOpt(String opt) {
		this.opt = opt;
	}

	public Float getCredit() {
		return this.credit;
	}

	public void setCredit(Float credit) {
		this.credit = credit;
	}

	public Short getThour() {
		return this.thour;
	}

	public void setThour(Short thour) {
		this.thour = thour;
	}

	public Short getSelectLimit() {
		return this.selectLimit;
	}

	public void setSelectLimit(Short selectLimit) {
		this.selectLimit = selectLimit;
	}

	public String getAdditionType() {
		return this.additionType;
	}

	public void setAdditionType(String additionType) {
		this.additionType = additionType;
	}

	public String getCyber() {
		return this.cyber;
	}

	public void setCyber(String cyber) {
		this.cyber = cyber;
	}

	public String getConfirmType() {
		return this.confirmType;
	}

	public void setConfirmType(String confirmType) {
		this.confirmType = confirmType;
	}

}