package tw.edu.chit.model;



/**
 * DtimeTeacher generated by MyEclipse - Hibernate Tools
 */

public class DtimeTeacher extends DtimeTchBase implements java.io.Serializable {


    // Fields    

     private Integer oid;
     private Integer dtimeOid;
     private String teachId;
     private Float hours;
     private Byte teach;
     private Byte fillscore;


    // Constructors

    /** default constructor */
    public DtimeTeacher() {
    }

	/** minimal constructor */
    public DtimeTeacher(Integer dtimeOid, Float hours, Byte teach, Byte fillscore) {
        this.dtimeOid = dtimeOid;
        this.hours = hours;
        this.teach = teach;
        this.fillscore = fillscore;
    }
    
    /** full constructor */
    public DtimeTeacher(Integer dtimeOid, String teachId, Float hours, Byte teach, Byte fillscore) {
        this.dtimeOid = dtimeOid;
        this.teachId = teachId;
        this.hours = hours;
        this.teach = teach;
        this.fillscore = fillscore;
    }

   
    // Property accessors

    public Integer getOid() {
        return this.oid;
    }
    
    public void setOid(Integer oid) {
        this.oid = oid;
    }

    public Integer getDtimeOid() {
        return this.dtimeOid;
    }
    
    public void setDtimeOid(Integer dtimeOid) {
        this.dtimeOid = dtimeOid;
    }

    public String getTeachId() {
        return this.teachId;
    }
    
    public void setTeachId(String teachId) {
        this.teachId = teachId;
    }

    public Float getHours() {
        return this.hours;
    }
    
    public void setHours(Float hours) {
        this.hours = hours;
    }

    public Byte getTeach() {
        return this.teach;
    }
    
    public void setTeach(Byte teach) {
        this.teach = teach;
    }

    public Byte getFillscore() {
        return this.fillscore;
    }
    
    public void setFillscore(Byte fillscore) {
        this.fillscore = fillscore;
    }
   








}