package tw.edu.chit.model;



/**
 * DtimeReserveClass generated by MyEclipse Persistence Tools
 */

public class DtimeReserveClass  implements java.io.Serializable {


    // Fields    

     private Integer oid;
     private Integer dtimeReserveReadyOid;
     private String begin;
     private String end;
     private String place;
     private Integer week;


    // Constructors

    /** default constructor */
    public DtimeReserveClass() {
    }

	/** minimal constructor */
    public DtimeReserveClass(Integer dtimeReserveReadyOid) {
        this.dtimeReserveReadyOid = dtimeReserveReadyOid;
    }
    
    /** full constructor */
    public DtimeReserveClass(Integer dtimeReserveReadyOid, String begin, String end, String place, Integer week) {
        this.dtimeReserveReadyOid = dtimeReserveReadyOid;
        this.begin = begin;
        this.end = end;
        this.place = place;
        this.week = week;
    }

   
    // Property accessors

    public Integer getOid() {
        return this.oid;
    }
    
    public void setOid(Integer oid) {
        this.oid = oid;
    }

    public Integer getDtimeReserveReadyOid() {
        return this.dtimeReserveReadyOid;
    }
    
    public void setDtimeReserveReadyOid(Integer dtimeReserveReadyOid) {
        this.dtimeReserveReadyOid = dtimeReserveReadyOid;
    }

    public String getBegin() {
        return this.begin;
    }
    
    public void setBegin(String begin) {
        this.begin = begin;
    }

    public String getEnd() {
        return this.end;
    }
    
    public void setEnd(String end) {
        this.end = end;
    }

    public String getPlace() {
        return this.place;
    }
    
    public void setPlace(String place) {
        this.place = place;
    }

    public Integer getWeek() {
        return this.week;
    }
    
    public void setWeek(Integer week) {
        this.week = week;
    }
   








}