package tw.edu.chit.model;

/**
 * DtimeReserveOpencs generated by MyEclipse Persistence Tools
 */

public class DtimeReserveOpencs implements java.io.Serializable {

	// Fields

	private Integer oid;

	private String departClass;

	private String cscode;

	private String cidno;

	private String sidno;

	private String didno;

	private String grade;

	private Integer dtimeOid;

	private String classNo;

	// Constructors

	/** default constructor */
	public DtimeReserveOpencs() {
	}

	/** full constructor */
	public DtimeReserveOpencs(String departClass, String cscode, String cidno,
			String sidno, String didno, String grade, Integer dtimeOid,
			String classNo) {
		this.departClass = departClass;
		this.cscode = cscode;
		this.cidno = cidno;
		this.sidno = sidno;
		this.didno = didno;
		this.grade = grade;
		this.dtimeOid = dtimeOid;
		this.classNo = classNo;
	}

	// Property accessors

	public Integer getOid() {
		return this.oid;
	}

	public void setOid(Integer oid) {
		this.oid = oid;
	}

	public String getDepartClass() {
		return this.departClass;
	}

	public void setDepartClass(String departClass) {
		this.departClass = departClass;
	}

	public String getCscode() {
		return this.cscode;
	}

	public void setCscode(String cscode) {
		this.cscode = cscode;
	}

	public String getCidno() {
		return this.cidno;
	}

	public void setCidno(String cidno) {
		this.cidno = cidno;
	}

	public String getSidno() {
		return this.sidno;
	}

	public void setSidno(String sidno) {
		this.sidno = sidno;
	}

	public String getDidno() {
		return this.didno;
	}

	public void setDidno(String didno) {
		this.didno = didno;
	}

	public String getGrade() {
		return this.grade;
	}

	public void setGrade(String grade) {
		this.grade = grade;
	}

	public Integer getDtimeOid() {
		return this.dtimeOid;
	}

	public void setDtimeOid(Integer dtimeOid) {
		this.dtimeOid = dtimeOid;
	}

	public String getClassNo() {
		return this.classNo;
	}

	public void setClassNo(String classNo) {
		this.classNo = classNo;
	}

}