package tw.edu.chit.model;

import java.util.Date;

/**
 * EpsActParameter generated by MyEclipse Persistence Tools
 */

public class EpsActParameter implements java.io.Serializable {

	// Fields

	private Integer oid;

	private String name;

	private Date signStart;

	private Date signEnd;

	private Date judgeStart;

	private Date judgeEnd;

	private Date end;

	// Constructors

	/** default constructor */
	public EpsActParameter() {
	}

	/** full constructor */
	public EpsActParameter(String name, Date signStart, Date signEnd,
			Date judgeStart, Date judgeEnd, Date end) {
		this.name = name;
		this.signStart = signStart;
		this.signEnd = signEnd;
		this.judgeStart = judgeStart;
		this.judgeEnd = judgeEnd;
		this.end = end;
	}

	// Property accessors

	public Integer getOid() {
		return this.oid;
	}

	public void setOid(Integer oid) {
		this.oid = oid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Date getSignStart() {
		return this.signStart;
	}

	public void setSignStart(Date signStart) {
		this.signStart = signStart;
	}

	public Date getSignEnd() {
		return this.signEnd;
	}

	public void setSignEnd(Date signEnd) {
		this.signEnd = signEnd;
	}

	public Date getJudgeStart() {
		return this.judgeStart;
	}

	public void setJudgeStart(Date judgeStart) {
		this.judgeStart = judgeStart;
	}

	public Date getJudgeEnd() {
		return this.judgeEnd;
	}

	public void setJudgeEnd(Date judgeEnd) {
		this.judgeEnd = judgeEnd;
	}

	public Date getEnd() {
		return this.end;
	}

	public void setEnd(Date end) {
		this.end = end;
	}

}