package tw.edu.chit.model;

/**
 * EpsVitae generated by MyEclipse Persistence Tools
 */

public class EpsVitae implements java.io.Serializable {

	// Fields

	private Integer oid;

	private String studentNo;

	private String contentZh;

	private String contentEn;

	// Constructors

	/** default constructor */
	public EpsVitae() {
	}

	/** full constructor */
	public EpsVitae(String studentNo, String contentZh, String contentEn) {
		this.studentNo = studentNo;
		this.contentZh = contentZh;
		this.contentEn = contentEn;
	}

	// Property accessors

	public Integer getOid() {
		return this.oid;
	}

	public void setOid(Integer oid) {
		this.oid = oid;
	}

	public String getStudentNo() {
		return this.studentNo;
	}

	public void setStudentNo(String studentNo) {
		this.studentNo = studentNo;
	}

	public String getContentZh() {
		return this.contentZh;
	}

	public void setContentZh(String contentZh) {
		this.contentZh = contentZh;
	}

	public String getContentEn() {
		return this.contentEn;
	}

	public void setContentEn(String contentEn) {
		this.contentEn = contentEn;
	}

}