package tw.edu.chit.model;

import java.util.Date;


/**
 * ExamDate generated by MyEclipse - Hibernate Tools
 */

public class ExamDate  implements java.io.Serializable {


    // Fields    

     private Integer oid;
     private String departClass;
     private Date date1;
     private Date date2;
     private Date date3;
     private Date date4;
     private Date date5;
     private Date begin1;
     private Date end1;
     private Date begin2;
     private Date end2;
     private Date begin3;
     private Date end3;
     private Date begin4;
     private Date end4;
     private Date begin5;
     private Date end5;
     private Date begin6;
     private Date end6;


    // Constructors

    /** default constructor */
    public ExamDate() {
    }

	/** minimal constructor */
    public ExamDate(String departClass) {
        this.departClass = departClass;
    }
    
    /** full constructor */
    public ExamDate(String departClass, Date date1, Date date2, Date date3, Date date4, Date date5, Date begin1, Date end1, Date begin2, Date end2, Date begin3, Date end3, Date begin4, Date end4, Date begin5, Date end5, Date begin6, Date end6) {
        this.departClass = departClass;
        this.date1 = date1;
        this.date2 = date2;
        this.date3 = date3;
        this.date4 = date4;
        this.date5 = date5;
        this.begin1 = begin1;
        this.end1 = end1;
        this.begin2 = begin2;
        this.end2 = end2;
        this.begin3 = begin3;
        this.end3 = end3;
        this.begin4 = begin4;
        this.end4 = end4;
        this.begin5 = begin5;
        this.end5 = end5;
        this.begin6 = begin6;
        this.end6 = end6;
    }

   
    // Property accessors

    public Integer getOid() {
        return this.oid;
    }
    
    public void setOid(Integer oid) {
        this.oid = oid;
    }

    public String getDepartClass() {
        return this.departClass;
    }
    
    public void setDepartClass(String departClass) {
        this.departClass = departClass;
    }

    public Date getDate1() {
        return this.date1;
    }
    
    public void setDate1(Date date1) {
        this.date1 = date1;
    }

    public Date getDate2() {
        return this.date2;
    }
    
    public void setDate2(Date date2) {
        this.date2 = date2;
    }

    public Date getDate3() {
        return this.date3;
    }
    
    public void setDate3(Date date3) {
        this.date3 = date3;
    }

    public Date getDate4() {
        return this.date4;
    }
    
    public void setDate4(Date date4) {
        this.date4 = date4;
    }

    public Date getDate5() {
        return this.date5;
    }
    
    public void setDate5(Date date5) {
        this.date5 = date5;
    }

    public Date getBegin1() {
        return this.begin1;
    }
    
    public void setBegin1(Date begin1) {
        this.begin1 = begin1;
    }

    public Date getEnd1() {
        return this.end1;
    }
    
    public void setEnd1(Date end1) {
        this.end1 = end1;
    }

    public Date getBegin2() {
        return this.begin2;
    }
    
    public void setBegin2(Date begin2) {
        this.begin2 = begin2;
    }

    public Date getEnd2() {
        return this.end2;
    }
    
    public void setEnd2(Date end2) {
        this.end2 = end2;
    }

    public Date getBegin3() {
        return this.begin3;
    }
    
    public void setBegin3(Date begin3) {
        this.begin3 = begin3;
    }

    public Date getEnd3() {
        return this.end3;
    }
    
    public void setEnd3(Date end3) {
        this.end3 = end3;
    }

    public Date getBegin4() {
        return this.begin4;
    }
    
    public void setBegin4(Date begin4) {
        this.begin4 = begin4;
    }

    public Date getEnd4() {
        return this.end4;
    }
    
    public void setEnd4(Date end4) {
        this.end4 = end4;
    }

    public Date getBegin5() {
        return this.begin5;
    }
    
    public void setBegin5(Date begin5) {
        this.begin5 = begin5;
    }

    public Date getEnd5() {
        return this.end5;
    }
    
    public void setEnd5(Date end5) {
        this.end5 = end5;
    }

    public Date getBegin6() {
        return this.begin6;
    }
    
    public void setBegin6(Date begin6) {
        this.begin6 = begin6;
    }

    public Date getEnd6() {
        return this.end6;
    }
    
    public void setEnd6(Date end6) {
        this.end6 = end6;
    }
   








}