package tw.edu.chit.model;

import java.util.Date;

/**
 * MasterData generated by MyEclipse - Hibernate Tools
 */
public class MasterData implements java.io.Serializable {

	private static final long serialVersionUID = -7891909410610463418L;

	private Integer oid;
	private Short schoolYear;
	private Short schoolTerm;
	private String studentNo;
	private String thesesChiname;
	private String thesesEngname;
	private Float thesesScore;
	private Float evgr1Score;
	private Float graduateScore;
	private Date onlineFileDate;
	private String remark;

	/** default constructor */
	public MasterData() {
	}

	/** minimal constructor */
	public MasterData(String studentNo) {
		this.studentNo = studentNo;
	}

	/** full constructor */
	public MasterData(Short schoolYear, Short schoolTerm, String studentNo,
			String thesesChiname, String thesesEngname, Float thesesScore,
			Float evgr1Score, Float graduateScore, Date onlineFileDate, 
			String remark) {
		this.schoolYear = schoolYear;
		this.schoolTerm = schoolTerm;
		this.studentNo = studentNo;
		this.thesesChiname = thesesChiname;
		this.thesesEngname = thesesEngname;
		this.thesesScore = thesesScore;
		this.evgr1Score = evgr1Score;
		this.graduateScore = graduateScore;
		this.onlineFileDate = onlineFileDate;
		this.remark = remark;
	}

	// Property accessors

	public Integer getOid() {
		return this.oid;
	}

	public void setOid(Integer oid) {
		this.oid = oid;
	}

	public Short getSchoolYear() {
		return this.schoolYear;
	}

	public void setSchoolYear(Short schoolYear) {
		this.schoolYear = schoolYear;
	}

	public Short getSchoolTerm() {
		return this.schoolTerm;
	}

	public void setSchoolTerm(Short schoolTerm) {
		this.schoolTerm = schoolTerm;
	}

	public String getStudentNo() {
		return this.studentNo;
	}

	public void setStudentNo(String studentNo) {
		this.studentNo = studentNo.toUpperCase();
	}

	public String getThesesChiname() {
		return this.thesesChiname;
	}

	public void setThesesChiname(String thesesChiname) {
		this.thesesChiname = thesesChiname;
	}

	public String getThesesEngname() {
		return this.thesesEngname;
	}

	public void setThesesEngname(String thesesEngname) {
		this.thesesEngname = thesesEngname;
	}

	public Float getThesesScore() {
		return this.thesesScore;
	}

	public void setThesesScore(Float thesesScore) {
		this.thesesScore = thesesScore;
	}

	public Float getEvgr1Score() {
		return this.evgr1Score;
	}

	public void setEvgr1Score(Float evgr1Score) {
		this.evgr1Score = evgr1Score;
	}

	public Float getGraduateScore() {
		return this.graduateScore;
	}

	public void setGraduateScore(Float graduateScore) {
		this.graduateScore = graduateScore;
	}

	public Date getOnlineFileDate() {
		return onlineFileDate;
	}

	public void setOnlineFileDate(Date onlineFileDate) {
		this.onlineFileDate = onlineFileDate;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}