package tw.edu.chit.model;

/**
 * Module generated by MyEclipse - Hibernate Tools
 */

public class Module implements java.io.Serializable {

	private static final long serialVersionUID = -9219409992156782389L;

	private Integer oid;
	private String name;
	private String label;
	private String icon;
	private String action;
	private Integer parentOid;
	private Integer sequence;
	private Integer level;
	private Byte inetUse;
	private Byte inetEnable;
	private String color;
	// Constructors

	public String getColor() {
		return color;
	}

	public void setColor(String color) {
		this.color = color;
	}

	/** default constructor */
	public Module() {
	}

	/** minimal constructor */
	public Module(String name, String label, String action, Integer parentOid,
			Integer sequence, Integer level, Byte inetUse, Byte inetEnable, String color) {
		this.name = name;
		this.label = label;
		this.action = action;
		this.parentOid = parentOid;
		this.sequence = sequence;
		this.level = level;
		this.inetUse = inetUse;
		this.inetEnable = inetEnable;
		this.color=color;
	}

	/** full constructor */
	public Module(String name, String label, String icon, String action,
			Integer parentOid, Integer sequence, Integer level, Byte inetUse,
			Byte inetEnable, String color) {
		this.name = name;
		this.label = label;
		this.icon = icon;
		this.action = action;
		this.parentOid = parentOid;
		this.sequence = sequence;
		this.level = level;
		this.inetUse = inetUse;
		this.inetEnable = inetEnable;
		this.color=color;
	}

	// Property accessors

	public Integer getOid() {
		return this.oid;
	}

	public void setOid(Integer oid) {
		this.oid = oid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getLabel() {
		return this.label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	public String getIcon() {
		return this.icon;
	}

	public void setIcon(String icon) {
		this.icon = icon;
	}

	public String getAction() {
		return this.action;
	}

	public void setAction(String action) {
		this.action = action;
	}

	public Integer getParentOid() {
		return this.parentOid;
	}

	public void setParentOid(Integer parentOid) {
		this.parentOid = parentOid;
	}

	public Integer getSequence() {
		return this.sequence;
	}

	public void setSequence(Integer sequence) {
		this.sequence = sequence;
	}

	public Integer getLevel() {
		return this.level;
	}

	public void setLevel(Integer level) {
		this.level = level;
	}

	public Byte getInetUse() {
		return this.inetUse;
	}

	public void setInetUse(Byte inetUse) {
		this.inetUse = inetUse;
	}

	public Byte getInetEnable() {
		return this.inetEnable;
	}

	public void setInetEnable(Byte inetEnable) {
		this.inetEnable = inetEnable;
	}

}