package tw.edu.chit.model;

import java.util.Date;



/**
 * Optime1 generated by MyEclipse - Hibernate Tools
 */

public class Optime1 extends OptimeBase implements java.io.Serializable {


    // Fields    

     private Integer oid;
     private String level;	//1:期中, 2:期末, 3:畢業, 4:暑修, 5:操行, 6:教學評量
     private String depart;
     private String beginDate;
     private String beginTime;
     private String endDate;
     private String endTime;
     private Date viewDate;


    // Constructors

    /** default constructor */
    public Optime1() {
    }

	/** minimal constructor */
    public Optime1(String level, String depart) {
        this.level = level;
        this.depart = depart;
    }
    
    /** full constructor */
    public Optime1(String level, String depart, String beginDate, String beginTime, String endDate, String endTime, Date viewDate) {
        this.level = level;
        this.depart = depart;
        this.beginDate = beginDate;
        this.beginTime = beginTime;
        this.endDate = endDate;
        this.endTime = endTime;
        this.viewDate = viewDate;
    }

   
    // Property accessors

    public Integer getOid() {
        return this.oid;
    }
    
    public void setOid(Integer oid) {
        this.oid = oid;
    }

    public String getLevel() {
        return this.level;
    }
    
    public void setLevel(String level) {
        this.level = level;
    }

    public String getDepart() {
        return this.depart;
    }
    
    public void setDepart(String depart) {
        this.depart = depart;
    }

    public String getBeginDate() {
        return this.beginDate;
    }
    
    public void setBeginDate(String beginDate) {
        this.beginDate = beginDate;
    }

    public String getBeginTime() {
        return this.beginTime;
    }
    
    public void setBeginTime(String beginTime) {
        this.beginTime = beginTime;
    }

    public String getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(String endDate) {
        this.endDate = endDate;
    }

    public String getEndTime() {
        return this.endTime;
    }
    
    public void setEndTime(String endTime) {
        this.endTime = endTime;
    }
    
    public Date getViewDate() {
		return this.viewDate;
	}

	public void setViewDate(Date viewDate) {
		this.viewDate = viewDate;
	}

}