package tw.edu.chit.model;



/**
 * Regs generated by MyEclipse - Hibernate Tools
 */

public class Regs extends RegsBase implements java.io.Serializable {


    // Fields    

     private Integer oid;
     private String studentNo;
     private Double score01;
     private Double score02;
     private Double score03;
     private Double score04;
     private Double score05;
     private Double score06;
     private Double score07;
     private Double score08;
     private Double score09;
     private Double score10;
     private Double score11;
     private Double score12;
     private Double score13;
     private Double score14;
     private Double score15;
     private Double score16;	//平時成績
     private Double score17;	//平時成績(比例30%)
     private Double score18;
     private Double score19;	//期中成績
     private Double score20;	//期中成績(比例30%)
     private Double score21;	//期末成績
     private Double score22;	//期末成績(比例40%)
     private Double score23;	//學期成績
     private Integer dtimeOid;


    // Constructors

    /** default constructor */
    public Regs() {
    }

    
    /** full constructor */
    public Regs(String studentNo, Double score01, Double score02, Double score03, Double score04, Double score05, Double score06, Double score07, Double score08, Double score09, Double score10, Double score11, Double score12, Double score13, Double score14, Double score15, Double score16, Double score17, Double score18, Double score19, Double score20, Double score21, Double score22, Double score23, Integer dtimeOid) {
        this.studentNo = studentNo;
        this.score01 = score01;
        this.score02 = score02;
        this.score03 = score03;
        this.score04 = score04;
        this.score05 = score05;
        this.score06 = score06;
        this.score07 = score07;
        this.score08 = score08;
        this.score09 = score09;
        this.score10 = score10;
        this.score11 = score11;
        this.score12 = score12;
        this.score13 = score13;
        this.score14 = score14;
        this.score15 = score15;
        this.score16 = score16;
        this.score17 = score17;
        this.score18 = score18;
        this.score19 = score19;
        this.score20 = score20;
        this.score21 = score21;
        this.score22 = score22;
        this.score23 = score23;
        this.dtimeOid = dtimeOid;
    }

   
    // Property accessors

    public Integer getOid() {
        return this.oid;
    }
    
    public void setOid(Integer oid) {
        this.oid = oid;
    }

    public String getStudentNo() {
        return this.studentNo;
    }
    
    public void setStudentNo(String studentNo) {
        this.studentNo = studentNo;
    }

    public Double getScore01() {
        return this.score01;
    }
    
    public void setScore01(Double score01) {
        this.score01 = score01;
    }

    public Double getScore02() {
        return this.score02;
    }
    
    public void setScore02(Double score02) {
        this.score02 = score02;
    }

    public Double getScore03() {
        return this.score03;
    }
    
    public void setScore03(Double score03) {
        this.score03 = score03;
    }

    public Double getScore04() {
        return this.score04;
    }
    
    public void setScore04(Double score04) {
        this.score04 = score04;
    }

    public Double getScore05() {
        return this.score05;
    }
    
    public void setScore05(Double score05) {
        this.score05 = score05;
    }

    public Double getScore06() {
        return this.score06;
    }
    
    public void setScore06(Double score06) {
        this.score06 = score06;
    }

    public Double getScore07() {
        return this.score07;
    }
    
    public void setScore07(Double score07) {
        this.score07 = score07;
    }

    public Double getScore08() {
        return this.score08;
    }
    
    public void setScore08(Double score08) {
        this.score08 = score08;
    }

    public Double getScore09() {
        return this.score09;
    }
    
    public void setScore09(Double score09) {
        this.score09 = score09;
    }

    public Double getScore10() {
        return this.score10;
    }
    
    public void setScore10(Double score10) {
        this.score10 = score10;
    }

    public Double getScore11() {
        return this.score11;
    }
    
    public void setScore11(Double score11) {
        this.score11 = score11;
    }

    public Double getScore12() {
        return this.score12;
    }
    
    public void setScore12(Double score12) {
        this.score12 = score12;
    }

    public Double getScore13() {
        return this.score13;
    }
    
    public void setScore13(Double score13) {
        this.score13 = score13;
    }

    public Double getScore14() {
        return this.score14;
    }
    
    public void setScore14(Double score14) {
        this.score14 = score14;
    }

    public Double getScore15() {
        return this.score15;
    }
    
    public void setScore15(Double score15) {
        this.score15 = score15;
    }

    public Double getScore16() {
        return this.score16;
    }
    
    public void setScore16(Double score16) {
        this.score16 = score16;
    }

    public Double getScore17() {
        return this.score17;
    }
    
    public void setScore17(Double score17) {
        this.score17 = score17;
    }

    public Double getScore18() {
        return this.score18;
    }
    
    public void setScore18(Double score18) {
        this.score18 = score18;
    }

    public Double getScore19() {
        return this.score19;
    }
    
    public void setScore19(Double score19) {
        this.score19 = score19;
    }

    public Double getScore20() {
        return this.score20;
    }
    
    public void setScore20(Double score20) {
        this.score20 = score20;
    }

    public Double getScore21() {
        return this.score21;
    }
    
    public void setScore21(Double score21) {
        this.score21 = score21;
    }

    public Double getScore22() {
        return this.score22;
    }
    
    public void setScore22(Double score22) {
        this.score22 = score22;
    }

    public Double getScore23() {
        return this.score23;
    }
    
    public void setScore23(Double score23) {
        this.score23 = score23;
    }

    public Integer getDtimeOid() {
        return this.dtimeOid;
    }
    
    public void setDtimeOid(Integer dtimeOid) {
        this.dtimeOid = dtimeOid;
    }
   








}