package tw.edu.chit.model;

/**
 * Sabbr generated by MyEclipse Persistence Tools
 */

public class Sabbr implements java.io.Serializable {

	// Fields

	private Integer oid;

	private String no;

	private String name;

	// Constructors

	/** default constructor */
	public Sabbr() {
	}

	/** minimal constructor */
	public Sabbr(String no) {
		this.no = no;
	}

	/** full constructor */
	public Sabbr(String no, String name) {
		this.no = no;
		this.name = name;
	}

	// Property accessors

	public Integer getOid() {
		return this.oid;
	}

	public void setOid(Integer oid) {
		this.oid = oid;
	}

	public String getNo() {
		return this.no;
	}

	public void setNo(String no) {
		this.no = no;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}