package tw.edu.chit.model;

import java.util.Date;

/**
 * Sdilg generated by MyEclipse Persistence Tools
 */

public class Sdilg implements java.io.Serializable {

	// Fields

	private Integer oid;

	private Short seqno;

	private String departClass;

	private String studentNo;

	private Integer weekNo;

	private Integer weekDay;

	private Date ddate;

	private String daynite;

	private String abs1;

	private String abs2;

	private String abs3;

	private String abs4;

	private String abs5;

	private String abs6;

	private String abs7;

	private String abs8;

	private String abs9;

	private String abs10;

	private String abs11;

	// Constructors

	/** default constructor */
	public Sdilg() {
	}

	/** full constructor */
	public Sdilg(Short seqno, String departClass, String studentNo,
			Integer weekNo, Integer weekDay, Date ddate, String daynite,
			String abs1, String abs2, String abs3, String abs4, String abs5,
			String abs6, String abs7, String abs8, String abs9, String abs10,
			String abs11) {
		this.seqno = seqno;
		this.departClass = departClass;
		this.studentNo = studentNo;
		this.weekNo = weekNo;
		this.weekDay = weekDay;
		this.ddate = ddate;
		this.daynite = daynite;
		this.abs1 = abs1;
		this.abs2 = abs2;
		this.abs3 = abs3;
		this.abs4 = abs4;
		this.abs5 = abs5;
		this.abs6 = abs6;
		this.abs7 = abs7;
		this.abs8 = abs8;
		this.abs9 = abs9;
		this.abs10 = abs10;
		this.abs11 = abs11;
	}

	// Property accessors

	public Integer getOid() {
		return this.oid;
	}

	public void setOid(Integer oid) {
		this.oid = oid;
	}

	public Short getSeqno() {
		return this.seqno;
	}

	public void setSeqno(Short seqno) {
		this.seqno = seqno;
	}

	public String getDepartClass() {
		return this.departClass;
	}

	public void setDepartClass(String departClass) {
		this.departClass = departClass;
	}

	public String getStudentNo() {
		return this.studentNo;
	}

	public void setStudentNo(String studentNo) {
		this.studentNo = studentNo;
	}

	public Integer getWeekNo() {
		return this.weekNo;
	}

	public void setWeekNo(Integer weekNo) {
		this.weekNo = weekNo;
	}

	public Integer getWeekDay() {
		return this.weekDay;
	}

	public void setWeekDay(Integer weekDay) {
		this.weekDay = weekDay;
	}

	public Date getDdate() {
		return this.ddate;
	}

	public void setDdate(Date ddate) {
		this.ddate = ddate;
	}

	public String getDaynite() {
		return this.daynite;
	}

	public void setDaynite(String daynite) {
		this.daynite = daynite;
	}

	public String getAbs1() {
		return this.abs1;
	}

	public void setAbs1(String abs1) {
		this.abs1 = abs1;
	}

	public String getAbs2() {
		return this.abs2;
	}

	public void setAbs2(String abs2) {
		this.abs2 = abs2;
	}

	public String getAbs3() {
		return this.abs3;
	}

	public void setAbs3(String abs3) {
		this.abs3 = abs3;
	}

	public String getAbs4() {
		return this.abs4;
	}

	public void setAbs4(String abs4) {
		this.abs4 = abs4;
	}

	public String getAbs5() {
		return this.abs5;
	}

	public void setAbs5(String abs5) {
		this.abs5 = abs5;
	}

	public String getAbs6() {
		return this.abs6;
	}

	public void setAbs6(String abs6) {
		this.abs6 = abs6;
	}

	public String getAbs7() {
		return this.abs7;
	}

	public void setAbs7(String abs7) {
		this.abs7 = abs7;
	}

	public String getAbs8() {
		return this.abs8;
	}

	public void setAbs8(String abs8) {
		this.abs8 = abs8;
	}

	public String getAbs9() {
		return this.abs9;
	}

	public void setAbs9(String abs9) {
		this.abs9 = abs9;
	}

	public String getAbs10() {
		return this.abs10;
	}

	public void setAbs10(String abs10) {
		this.abs10 = abs10;
	}

	public String getAbs11() {
		return this.abs11;
	}

	public void setAbs11(String abs11) {
		this.abs11 = abs11;
	}

}