package tw.edu.chit.model;

/**
 * Sdtime generated by MyEclipse Persistence Tools
 */

public class Sdtime implements java.io.Serializable {

	// Fields

	private Integer oid;

	private Short seqno;

	private String departClass;

	private String cscode;

	private String which;

	private String techid;

	private String opt;

	private Double credit;

	private Short thour;

	private String clascode;

	private String day1;

	private String day2;

	private String day3;

	private String day4;

	private String day5;

	private String day6;

	private String day7;

	private Short stuSelect;

	private String status;

	// Constructors

	/** default constructor */
	public Sdtime() {
	}

	/** minimal constructor */
	public Sdtime(String departClass, String cscode, String status) {
		this.departClass = departClass;
		this.cscode = cscode;
		this.status = status;
	}

	/** full constructor */
	public Sdtime(Short seqno, String departClass, String cscode, String which,
			String techid, String opt, Double credit, Short thour,
			String clascode, String day1, String day2, String day3,
			String day4, String day5, String day6, String day7,
			Short stuSelect, String status) {
		this.seqno = seqno;
		this.departClass = departClass;
		this.cscode = cscode;
		this.which = which;
		this.techid = techid;
		this.opt = opt;
		this.credit = credit;
		this.thour = thour;
		this.clascode = clascode;
		this.day1 = day1;
		this.day2 = day2;
		this.day3 = day3;
		this.day4 = day4;
		this.day5 = day5;
		this.day6 = day6;
		this.day7 = day7;
		this.stuSelect = stuSelect;
		this.status = status;
	}

	// Property accessors

	public Integer getOid() {
		return this.oid;
	}

	public void setOid(Integer oid) {
		this.oid = oid;
	}

	public Short getSeqno() {
		return this.seqno;
	}

	public void setSeqno(Short seqno) {
		this.seqno = seqno;
	}

	public String getDepartClass() {
		return this.departClass;
	}

	public void setDepartClass(String departClass) {
		this.departClass = departClass;
	}

	public String getCscode() {
		return this.cscode;
	}

	public void setCscode(String cscode) {
		this.cscode = cscode;
	}

	public String getWhich() {
		return this.which;
	}

	public void setWhich(String which) {
		this.which = which;
	}

	public String getTechid() {
		return this.techid;
	}

	public void setTechid(String techid) {
		this.techid = techid;
	}

	public String getOpt() {
		return this.opt;
	}

	public void setOpt(String opt) {
		this.opt = opt;
	}

	public Double getCredit() {
		return this.credit;
	}

	public void setCredit(Double credit) {
		this.credit = credit;
	}

	public Short getThour() {
		return this.thour;
	}

	public void setThour(Short thour) {
		this.thour = thour;
	}

	public String getClascode() {
		return this.clascode;
	}

	public void setClascode(String clascode) {
		this.clascode = clascode;
	}

	public String getDay1() {
		return this.day1;
	}

	public void setDay1(String day1) {
		this.day1 = day1;
	}

	public String getDay2() {
		return this.day2;
	}

	public void setDay2(String day2) {
		this.day2 = day2;
	}

	public String getDay3() {
		return this.day3;
	}

	public void setDay3(String day3) {
		this.day3 = day3;
	}

	public String getDay4() {
		return this.day4;
	}

	public void setDay4(String day4) {
		this.day4 = day4;
	}

	public String getDay5() {
		return this.day5;
	}

	public void setDay5(String day5) {
		this.day5 = day5;
	}

	public String getDay6() {
		return this.day6;
	}

	public void setDay6(String day6) {
		this.day6 = day6;
	}

	public String getDay7() {
		return this.day7;
	}

	public void setDay7(String day7) {
		this.day7 = day7;
	}

	public Short getStuSelect() {
		return this.stuSelect;
	}

	public void setStuSelect(Short stuSelect) {
		this.stuSelect = stuSelect;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}