package tw.edu.chit.model;



/**
 * SeldStuFilter generated by MyEclipse - Hibernate Tools
 */

public class SeldStuFilter  implements java.io.Serializable {


    // Fields

     private Integer oid;
     private String stdepartClass;
     private String studentNo;
     private String csdepartClass;
     private String cscode;
     private String type;
     private String sterm;
     private String note;
     private Integer dtimeOid;


    // Constructors

    /** default constructor */
    public SeldStuFilter() {
    }

	/** minimal constructor */
    public SeldStuFilter(Integer dtimeOid) {
        this.dtimeOid = dtimeOid;
    }

    /** full constructor */
    public SeldStuFilter(String stdepartClass, String studentNo, String csdepartClass, String cscode, String type, String sterm, String note, Integer dtimeOid) {
        this.stdepartClass = stdepartClass;
        this.studentNo = studentNo;
        this.csdepartClass = csdepartClass;
        this.cscode = cscode;
        this.type = type;
        this.sterm = sterm;
        this.note = note;
        this.dtimeOid = dtimeOid;
    }


    // Property accessors

    public Integer getOid() {
        return this.oid;
    }

    public void setOid(Integer oid) {
        this.oid = oid;
    }

    public String getStdepartClass() {
        return this.stdepartClass;
    }

    public void setStdepartClass(String stdepartClass) {
        this.stdepartClass = stdepartClass;
    }

    public String getStudentNo() {
        return this.studentNo;
    }

    public void setStudentNo(String studentNo) {
        this.studentNo = studentNo;
    }

    public String getCsdepartClass() {
        return this.csdepartClass;
    }

    public void setCsdepartClass(String csdepartClass) {
        this.csdepartClass = csdepartClass;
    }

    public String getCscode() {
        return this.cscode;
    }

    public void setCscode(String cscode) {
        this.cscode = cscode;
    }

    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getSterm() {
        return this.sterm;
    }

    public void setSterm(String sterm) {
        this.sterm = sterm;
    }

    public String getNote() {
        return this.note;
    }

    public void setNote(String note) {
        this.note = note;
    }

    public Integer getDtimeOid() {
        return this.dtimeOid;
    }

    public void setDtimeOid(Integer dtimeOid) {
        this.dtimeOid = dtimeOid;
    }









}