package tw.edu.chit.model;

/**
 * SseldReject generated by MyEclipse Persistence Tools
 */

public class SseldReject implements java.io.Serializable {

	// Fields

	private Integer oid;

	private Short seqno;

	private String stdepartClass;

	private String studentNo;

	private String csdepartClass;

	private String cscode;

	private String which;

	private Double score;

	// Constructors

	/** default constructor */
	public SseldReject() {
	}

	/** full constructor */
	public SseldReject(Short seqno, String stdepartClass, String studentNo,
			String csdepartClass, String cscode, String which, Double score) {
		this.seqno = seqno;
		this.stdepartClass = stdepartClass;
		this.studentNo = studentNo;
		this.csdepartClass = csdepartClass;
		this.cscode = cscode;
		this.which = which;
		this.score = score;
	}

	// Property accessors

	public Integer getOid() {
		return this.oid;
	}

	public void setOid(Integer oid) {
		this.oid = oid;
	}

	public Short getSeqno() {
		return this.seqno;
	}

	public void setSeqno(Short seqno) {
		this.seqno = seqno;
	}

	public String getStdepartClass() {
		return this.stdepartClass;
	}

	public void setStdepartClass(String stdepartClass) {
		this.stdepartClass = stdepartClass;
	}

	public String getStudentNo() {
		return this.studentNo;
	}

	public void setStudentNo(String studentNo) {
		this.studentNo = studentNo;
	}

	public String getCsdepartClass() {
		return this.csdepartClass;
	}

	public void setCsdepartClass(String csdepartClass) {
		this.csdepartClass = csdepartClass;
	}

	public String getCscode() {
		return this.cscode;
	}

	public void setCscode(String cscode) {
		this.cscode = cscode;
	}

	public String getWhich() {
		return this.which;
	}

	public void setWhich(String which) {
		this.which = which;
	}

	public Double getScore() {
		return this.score;
	}

	public void setScore(Double score) {
		this.score = score;
	}

}