package tw.edu.chit.model;

/**
 * Sseld generated by MyEclipse Persistence Tools
 */

public class Sseld implements java.io.Serializable {

	// Fields

	private Integer oid;

	private Short seqno;

	private String stdepartClass;

	private String studentNo;

	private String csdepartClass;

	private String cscode;

	private String which;

	private Double score;

	private Float sc1;

	private Float sc2;

	private Float sc3;

	private Float sc4;

	private Float medScore;

	private Float endScore;

	private Float freeScore;

	// Constructors

	/** default constructor */
	public Sseld() {
	}

	/** full constructor */
	public Sseld(Short seqno, String stdepartClass, String studentNo,
			String csdepartClass, String cscode, String which, Double score,
			Float sc1, Float sc2, Float sc3, Float sc4, Float medScore,
			Float endScore, Float freeScore) {
		this.seqno = seqno;
		this.stdepartClass = stdepartClass;
		this.studentNo = studentNo;
		this.csdepartClass = csdepartClass;
		this.cscode = cscode;
		this.which = which;
		this.score = score;
		this.sc1 = sc1;
		this.sc2 = sc2;
		this.sc3 = sc3;
		this.sc4 = sc4;
		this.medScore = medScore;
		this.endScore = endScore;
		this.freeScore = freeScore;
	}

	// Property accessors

	public Integer getOid() {
		return this.oid;
	}

	public void setOid(Integer oid) {
		this.oid = oid;
	}

	public Short getSeqno() {
		return this.seqno;
	}

	public void setSeqno(Short seqno) {
		this.seqno = seqno;
	}

	public String getStdepartClass() {
		return this.stdepartClass;
	}

	public void setStdepartClass(String stdepartClass) {
		this.stdepartClass = stdepartClass;
	}

	public String getStudentNo() {
		return this.studentNo;
	}

	public void setStudentNo(String studentNo) {
		this.studentNo = studentNo;
	}

	public String getCsdepartClass() {
		return this.csdepartClass;
	}

	public void setCsdepartClass(String csdepartClass) {
		this.csdepartClass = csdepartClass;
	}

	public String getCscode() {
		return this.cscode;
	}

	public void setCscode(String cscode) {
		this.cscode = cscode;
	}

	public String getWhich() {
		return this.which;
	}

	public void setWhich(String which) {
		this.which = which;
	}

	public Double getScore() {
		return this.score;
	}

	public void setScore(Double score) {
		this.score = score;
	}

	public Float getSc1() {
		return this.sc1;
	}

	public void setSc1(Float sc1) {
		this.sc1 = sc1;
	}

	public Float getSc2() {
		return this.sc2;
	}

	public void setSc2(Float sc2) {
		this.sc2 = sc2;
	}

	public Float getSc3() {
		return this.sc3;
	}

	public void setSc3(Float sc3) {
		this.sc3 = sc3;
	}

	public Float getSc4() {
		return this.sc4;
	}

	public void setSc4(Float sc4) {
		this.sc4 = sc4;
	}

	public Float getMedScore() {
		return this.medScore;
	}

	public void setMedScore(Float medScore) {
		this.medScore = medScore;
	}

	public Float getEndScore() {
		return this.endScore;
	}

	public void setEndScore(Float endScore) {
		this.endScore = endScore;
	}

	public Float getFreeScore() {
		return this.freeScore;
	}

	public void setFreeScore(Float freeScore) {
		this.freeScore = freeScore;
	}

}