package tw.edu.chit.model;

import java.util.Date;

/**
 * StdAdcd generated by MyEclipse - Hibernate Tools
 */

public class StdAdcd implements java.io.Serializable {

	private static final long serialVersionUID = 8891508965534778061L;

	private Integer oid;
	private String studentNo;
	private Date lastModified;
	private String adddraw;
	private Integer dtimeOid;

	// Constructors

	/** default constructor */
	public StdAdcd() {
	}

	/** full constructor */
	public StdAdcd(String studentNo, Date lastModified, String adddraw,
			Integer dtimeOid) {
		this.studentNo = studentNo;
		this.lastModified = lastModified;
		this.adddraw = adddraw;
		this.dtimeOid = dtimeOid;
	}

	// Property accessors

	public Integer getOid() {
		return this.oid;
	}

	public void setOid(Integer oid) {
		this.oid = oid;
	}

	public String getStudentNo() {
		return studentNo;
	}

	public void setStudentNo(String studentNo) {
		this.studentNo = studentNo;
	}

	public Date getLastModified() {
		return this.lastModified;
	}

	public void setLastModified(Date lastModified) {
		this.lastModified = lastModified;
	}

	public String getAdddraw() {
		return this.adddraw;
	}

	public void setAdddraw(String adddraw) {
		this.adddraw = adddraw;
	}

	public Integer getDtimeOid() {
		return this.dtimeOid;
	}

	public void setDtimeOid(Integer dtimeOid) {
		this.dtimeOid = dtimeOid;
	}

}