package tw.edu.chit.model;

import java.sql.Blob;



/**
 * StdImage4t generated by MyEclipse Persistence Tools
 */

public class StdImage4t  implements java.io.Serializable {


    // Fields    

     private Integer oid;
     private String studentNo;
     private String idno;
     private Blob image;


    // Constructors

    /** default constructor */
    public StdImage4t() {
    }

    
    /** full constructor */
    public StdImage4t(String studentNo, String idno, Blob image) {
        this.studentNo = studentNo;
        this.idno = idno;
        this.image = image;
    }

   
    // Property accessors

    public Integer getOid() {
        return this.oid;
    }
    
    public void setOid(Integer oid) {
        this.oid = oid;
    }

    public String getStudentNo() {
        return this.studentNo;
    }
    
    public void setStudentNo(String studentNo) {
        this.studentNo = studentNo;
    }

    public String getIdno() {
        return this.idno;
    }
    
    public void setIdno(String idno) {
        this.idno = idno;
    }

    public Blob getImage() {
        return this.image;
    }
    
    public void setImage(Blob image) {
        this.image = image;
    }
   








}