package tw.edu.chit.model;

import java.util.Date;

/**
 * StdOpinionSuggestion generated by MyEclipse - Hibernate Tools
 */
public class StdOpinionSuggestion implements java.io.Serializable {

	private static final long serialVersionUID = -6927021422930805622L;

	private Integer oid;
	private String schoolYear;
	private String schoolTerm;
	private Integer studentOid;
	private String email;
	private String topic;
	private Date date;
	private String target;
	private String place;
	private String content;
	private Date lastModified;

	public StdOpinionSuggestion() {
	}

	public StdOpinionSuggestion(Integer oid, Integer studentOid) {
		this.oid = oid;
		this.studentOid = studentOid;
	}

	public StdOpinionSuggestion(Integer oid, Integer studentOid, String email,
			String topic, Date date, String target, String place, String content) {
		this.oid = oid;
		this.studentOid = studentOid;
		this.email = email;
		this.topic = topic;
		this.date = date;
		this.target = target;
		this.place = place;
		this.content = content;
	}

	public String getSchoolYear() {
		return schoolYear;
	}

	public void setSchoolYear(String schoolYear) {
		this.schoolYear = schoolYear;
	}

	public String getSchoolTerm() {
		return schoolTerm;
	}

	public void setSchoolTerm(String schoolTerm) {
		this.schoolTerm = schoolTerm;
	}

	public Integer getOid() {
		return this.oid;
	}

	public void setOid(Integer oid) {
		this.oid = oid;
	}

	public Integer getStudentOid() {
		return this.studentOid;
	}

	public void setStudentOid(Integer studentOid) {
		this.studentOid = studentOid;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getTopic() {
		return this.topic;
	}

	public void setTopic(String topic) {
		this.topic = topic;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public String getTarget() {
		return this.target;
	}

	public void setTarget(String target) {
		this.target = target;
	}

	public String getPlace() {
		return this.place;
	}

	public void setPlace(String place) {
		this.place = place;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Date getLastModified() {
		return lastModified;
	}

	public void setLastModified(Date lastModified) {
		this.lastModified = lastModified;
	}

}