package tw.edu.chit.model;



/**
 * Subs generated by MyEclipse - Hibernate Tools
 */

public class Subs  implements java.io.Serializable {


    // Fields    

     private Integer oid;
     private String no;
     private String name;
     private Double first;
     private Double second;
     private Double third;
     private Double fourth;
     private Double fifth;
     private Double sixth;


    // Constructors

    /** default constructor */
    public Subs() {
    }

    
    /** full constructor */
    public Subs(String no, String name, Double first, Double second, Double third, Double fourth, Double fifth, Double sixth) {
        this.no = no;
        this.name = name;
        this.first = first;
        this.second = second;
        this.third = third;
        this.fourth = fourth;
        this.fifth = fifth;
        this.sixth = sixth;
    }

   
    // Property accessors

    public Integer getOid() {
        return this.oid;
    }
    
    public void setOid(Integer oid) {
        this.oid = oid;
    }

    public String getNo() {
        return this.no;
    }
    
    public void setNo(String no) {
        this.no = no;
    }

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public Double getFirst() {
        return this.first;
    }
    
    public void setFirst(Double first) {
        this.first = first;
    }

    public Double getSecond() {
        return this.second;
    }
    
    public void setSecond(Double second) {
        this.second = second;
    }

    public Double getThird() {
        return this.third;
    }
    
    public void setThird(Double third) {
        this.third = third;
    }

    public Double getFourth() {
        return this.fourth;
    }
    
    public void setFourth(Double fourth) {
        this.fourth = fourth;
    }

    public Double getFifth() {
        return this.fifth;
    }
    
    public void setFifth(Double fifth) {
        this.fifth = fifth;
    }

    public Double getSixth() {
        return this.sixth;
    }
    
    public void setSixth(Double sixth) {
        this.sixth = sixth;
    }
   








}