package tw.edu.chit.model;

import java.util.Date;

/**
 * Sweek generated by MyEclipse Persistence Tools
 */

public class Sweek implements java.io.Serializable {

	// Fields

	private Integer oid;

	private String daynite;

	private Short seqno;

	private Date wdate;

	// Constructors

	/** default constructor */
	public Sweek() {
	}

	/** minimal constructor */
	public Sweek(Date wdate) {
		this.wdate = wdate;
	}

	/** full constructor */
	public Sweek(String daynite, Short seqno, Date wdate) {
		this.daynite = daynite;
		this.seqno = seqno;
		this.wdate = wdate;
	}

	// Property accessors

	public Integer getOid() {
		return this.oid;
	}

	public void setOid(Integer oid) {
		this.oid = oid;
	}

	public String getDaynite() {
		return this.daynite;
	}

	public void setDaynite(String daynite) {
		this.daynite = daynite;
	}

	public Short getSeqno() {
		return this.seqno;
	}

	public void setSeqno(Short seqno) {
		this.seqno = seqno;
	}

	public Date getWdate() {
		return this.wdate;
	}

	public void setWdate(Date wdate) {
		this.wdate = wdate;
	}

}