package tw.edu.chit.model;

/**
 * Syllabu generated by MyEclipse Persistence Tools
 */

public class Syllabu implements java.io.Serializable {

	// Fields

	private Integer oid;

	private Integer parentOid;

	private String topic;

	private String content;

	private String hours;

	private String week;

	private String remarks;

	private Integer pos;

	// Constructors

	/** default constructor */
	public Syllabu() {
	}

	/** minimal constructor */
	public Syllabu(Integer parentOid, Integer pos) {
		this.parentOid = parentOid;
		this.pos = pos;
	}

	/** full constructor */
	public Syllabu(Integer parentOid, String topic, String content,
			String hours, String week, String remarks, Integer pos) {
		this.parentOid = parentOid;
		this.topic = topic;
		this.content = content;
		this.hours = hours;
		this.week = week;
		this.remarks = remarks;
		this.pos = pos;
	}

	// Property accessors

	public Integer getOid() {
		return this.oid;
	}

	public void setOid(Integer oid) {
		this.oid = oid;
	}

	public Integer getParentOid() {
		return this.parentOid;
	}

	public void setParentOid(Integer parentOid) {
		this.parentOid = parentOid;
	}

	public String getTopic() {
		return this.topic;
	}

	public void setTopic(String topic) {
		this.topic = topic;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public String getHours() {
		return this.hours;
	}

	public void setHours(String hours) {
		this.hours = hours;
	}

	public String getWeek() {
		return this.week;
	}

	public void setWeek(String week) {
		this.week = week;
	}

	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	public Integer getPos() {
		return this.pos;
	}

	public void setPos(Integer pos) {
		this.pos = pos;
	}

}