package tw.edu.chit.model;

/**
 * Syllabus generated by MyEclipse - Hibernate Tools
 */

public class Syllabus implements java.io.Serializable {

	private static final long serialVersionUID = 2884684976450573001L;

	private Integer oid;
	private Integer parentOid;
	private String topic;
	private String content;
	private String hours;
	private String week;
	private String remarks;
	private Integer pos;
	private CourseSyllabus courseSyllabus;

	// Constructors

	/** default constructor */
	public Syllabus() {
	}

	/** full constructor */
	public Syllabus(Integer parentOid, String topic, String content,
			String hours, String week, String remarks,
			CourseSyllabus courseSyllabus) {
		this.parentOid = parentOid;
		this.topic = topic;
		this.content = content;
		this.hours = hours;
		this.week = week;
		this.remarks = remarks;
		this.courseSyllabus = courseSyllabus;
	}

	// Property accessors

	public Integer getOid() {
		return this.oid;
	}

	public void setOid(Integer oid) {
		this.oid = oid;
	}

	public Integer getParentOid() {
		return this.parentOid;
	}

	public void setParentOid(Integer parentOid) {
		this.parentOid = parentOid;
	}

	public String getTopic() {
		return this.topic;
	}

	public void setTopic(String topic) {
		this.topic = topic;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public String getHours() {
		return this.hours;
	}

	public void setHours(String hours) {
		this.hours = hours;
	}

	public String getWeek() {
		return this.week;
	}

	public void setWeek(String week) {
		this.week = week;
	}

	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	public CourseSyllabus getCourseSyllabus() {
		return courseSyllabus;
	}

	public void setCourseSyllabus(CourseSyllabus courseSyllabus) {
		this.courseSyllabus = courseSyllabus;
	}

	public Integer getPos() {
		return pos;
	}

	public void setPos(Integer pos) {
		this.pos = pos;
	}

}