package tw.edu.chit.model;



/**
 * Parameter generated by MyEclipse - Hibernate Tools
 */

public class SysParameter  implements java.io.Serializable {


    // Fields    

     private Integer oid;
     private String name;
     private String value;
     private String category;


    // Constructors

    /** default constructor */
    public SysParameter() {
    }

	/** minimal constructor */
    public SysParameter(String name) {
        this.name = name;
    }
    
    /** full constructor */
    public SysParameter(String name, String value, String category) {
        this.name = name;
        this.value = value;
        this.category = category;
    }

   
    // Property accessors

    public Integer getOid() {
        return this.oid;
    }
    
    public void setOid(Integer oid) {
        this.oid = oid;
    }

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }

    public String getCategory() {
        return this.category;
    }
    
    public void setCategory(String category) {
        this.category = category;
    }
   








}