package tw.edu.chit.model;

/**
 * TeacherOfficeLocation generated by MyEclipse - Hibernate Tools
 */

public class TeacherOfficeLocation implements java.io.Serializable {

	private static final long serialVersionUID = -4077176814785096456L;

	private Integer oid;
	private String roomId;
	private String remark;
	private String extension;

	private Empl empl;

	/** default constructor */
	public TeacherOfficeLocation() {
	}

	/** minimal constructor */
	public TeacherOfficeLocation(Integer oid) {
		this.oid = oid;
	}

	/** full constructor */
	public TeacherOfficeLocation(Integer oid, String location, String remark,
			String extension) {
		this.oid = oid;
		this.roomId = location;
		this.remark = remark;
		this.extension = extension;
	}

	public Integer getOid() {
		return this.oid;
	}

	public void setOid(Integer oid) {
		this.oid = oid;
	}

	public String getRoomId() {
		return this.roomId;
	}

	public void setRoomId(String RoomId) {
		this.roomId = RoomId;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getExtension() {
		return this.extension;
	}

	public void setExtension(String extension) {
		this.extension = extension;
	}

	public Empl getEmpl() {
		return empl;
	}

	public void setEmpl(Empl empl) {
		this.empl = empl;
	}

}