package tw.edu.chit.model;

/**
 * Tranno generated by MyEclipse Persistence Tools
 */

public class Tranno implements java.io.Serializable {

	// Fields

	private Integer oid;

	private String studentNo;

	private String schlName;

	private String permissionNo;

	// Constructors

	/** default constructor */
	public Tranno() {
	}

	/** minimal constructor */
	public Tranno(String studentNo) {
		this.studentNo = studentNo;
	}

	/** full constructor */
	public Tranno(String studentNo, String schlName, String permissionNo) {
		this.studentNo = studentNo;
		this.schlName = schlName;
		this.permissionNo = permissionNo;
	}

	// Property accessors

	public Integer getOid() {
		return this.oid;
	}

	public void setOid(Integer oid) {
		this.oid = oid;
	}

	public String getStudentNo() {
		return this.studentNo;
	}

	public void setStudentNo(String studentNo) {
		this.studentNo = studentNo;
	}

	public String getSchlName() {
		return this.schlName;
	}

	public void setSchlName(String schlName) {
		this.schlName = schlName;
	}

	public String getPermissionNo() {
		return this.permissionNo;
	}

	public void setPermissionNo(String permissionNo) {
		this.permissionNo = permissionNo;
	}

}