package tw.edu.chit.model;

import java.util.Date;

/**
 * Tran generated by MyEclipse Persistence Tools
 */

public class Tran implements java.io.Serializable {

	// Fields

	private Integer oid;

	private String studentNo;

	private String oldDepartClass;

	private String newDepartClass;

	private Short occurYear;

	private String occurTerm;

	private Date occurDate;

	private String occurDocno;

	// Constructors

	/** default constructor */
	public Tran() {
	}

	/** minimal constructor */
	public Tran(String studentNo, String oldDepartClass, String newDepartClass,
			Short occurYear, String occurTerm) {
		this.studentNo = studentNo;
		this.oldDepartClass = oldDepartClass;
		this.newDepartClass = newDepartClass;
		this.occurYear = occurYear;
		this.occurTerm = occurTerm;
	}

	/** full constructor */
	public Tran(String studentNo, String oldDepartClass, String newDepartClass,
			Short occurYear, String occurTerm, Date occurDate, String occurDocno) {
		this.studentNo = studentNo;
		this.oldDepartClass = oldDepartClass;
		this.newDepartClass = newDepartClass;
		this.occurYear = occurYear;
		this.occurTerm = occurTerm;
		this.occurDate = occurDate;
		this.occurDocno = occurDocno;
	}

	// Property accessors

	public Integer getOid() {
		return this.oid;
	}

	public void setOid(Integer oid) {
		this.oid = oid;
	}

	public String getStudentNo() {
		return this.studentNo;
	}

	public void setStudentNo(String studentNo) {
		this.studentNo = studentNo;
	}

	public String getOldDepartClass() {
		return this.oldDepartClass;
	}

	public void setOldDepartClass(String oldDepartClass) {
		this.oldDepartClass = oldDepartClass;
	}

	public String getNewDepartClass() {
		return this.newDepartClass;
	}

	public void setNewDepartClass(String newDepartClass) {
		this.newDepartClass = newDepartClass;
	}

	public Short getOccurYear() {
		return this.occurYear;
	}

	public void setOccurYear(Short occurYear) {
		this.occurYear = occurYear;
	}

	public String getOccurTerm() {
		return this.occurTerm;
	}

	public void setOccurTerm(String occurTerm) {
		this.occurTerm = occurTerm;
	}

	public Date getOccurDate() {
		return this.occurDate;
	}

	public void setOccurDate(Date occurDate) {
		this.occurDate = occurDate;
	}

	public String getOccurDocno() {
		return this.occurDocno;
	}

	public void setOccurDocno(String occurDocno) {
		this.occurDocno = occurDocno;
	}

}