package tw.edu.chit.model;



/**
 * UnitBelong generated by MyEclipse - Hibernate Tools
 */

public class UnitBelong  implements java.io.Serializable {


    // Fields    

     private Integer oid;
     private Integer empOid;
     private String unitNo;


    // Constructors

    /** default constructor */
    public UnitBelong() {
    }

    
    /** full constructor */
    public UnitBelong(Integer oid, Integer empOid, String unitNo) {
        this.oid = oid;
        this.empOid = empOid;
        this.unitNo = unitNo;
    }

   
    // Property accessors

    public Integer getOid() {
        return this.oid;
    }
    
    public void setOid(Integer oid) {
        this.oid = oid;
    }

    public Integer getEmpOid() {
        return this.empOid;
    }
    
    public void setEmpOid(Integer empOid) {
        this.empOid = empOid;
    }

    public String getUnitNo() {
        return this.unitNo;
    }
    
    public void setUnitNo(String unitNo) {
        this.unitNo = unitNo;
    }
   








}