package tw.edu.chit.model;

import java.util.Date;

/**
 * Wwpass generated by MyEclipse Persistence Tools
 */

public class WwPass implements java.io.Serializable {

	// Fields

	private String username;

	private String password;

	private String priority;

	private String informixPass;

	private Date updated;

	private String secondName;
	
	private Date online;
	
	/** full constructor */
	public WwPass(String password, String priority, String informixPass,
			Date updated, String secondName, Date online) {
		this.password = password;
		this.priority = priority;
		this.informixPass = informixPass;
		this.updated = updated;
		this.secondName = secondName;
		this.online=online;
	}

	// Constructors

	public Date getOnline() {
		return this.online;
	}

	public void setOnline(Date online) {
		this.online = online;
	}

	/** default constructor */
	public WwPass() {
	}

	

	// Property accessors

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getPriority() {
		return this.priority;
	}

	public void setPriority(String priority) {
		this.priority = priority;
	}

	public String getInformixPass() {
		return this.informixPass;
	}

	public void setInformixPass(String informixPass) {
		this.informixPass = informixPass;
	}

	public Date getUpdated() {
		return this.updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

	public String getSecondName() {
		return this.secondName;
	}

	public void setSecondName(String secondName) {
		this.secondName = secondName;
	}

}